### ISSUE TITLE
mtk hwnat貌似未启用

### ISSUE THREAD

**Issue by zheshifandian** [hanwckf/immortalwrt-mt798x#1]
编译时也选了kmod-mtk-hwnat(应该是这个名)
turboacc只有flow加速
日志里也没有相关log

**Comment by hanwckf** [comment]
这个不要选择，默认使用新版hnat驱动

**Comment by padavanonly** [comment]
另外不能启用flow offload，否则mtk hnat会失效

**Comment by AlphaAnother** [comment]
这个是因为defconfig选中了kmod-nf-flow 然后在menuconfig时哪怕选中turboacc并取消了nf-flow子选项 编译出来的固件初次启动还是会执行turboacc启动flow offload
