### ISSUE TITLE
关于MT7981更换1G内存不识别的问题

### ISSUE THREAD

**Issue by thunder361** [hanwckf/immortalwrt-mt798x#10]
大大你好，我手里有几种MT7981的板子，在硬改内存时候发现总是卡死不开机，后来发现是BL问题，更换了360T7后可以顺利识别，但是1G也是只能识别为512M内存，确认颗粒是单晶颗粒，想问问是否有内存控制的地方，如何着手修改

**Comment by ningsibuqu** [comment]
不支持1g

**Comment by thunder361** [comment]
> 



> 
MT2500是支持1G，只不过是DDR4

**Comment by thunder361** [comment]
> 不支持1g

MT2500是支持1G的，只不过是DDR4

**Comment by hanwckf** [comment]
mt798x ddr3最大只支持512M，DDR4才能上2G

**Comment by thunder361** [comment]
> mt798x ddr3最大只支持512M，DDR4才能上2G

谢谢回复，懂了
