### ISSUE TITLE
在什么情况下会出现'Ethernet HNAT Disabled'?

### ISSUE THREAD

**Issue by initzhu** [hanwckf/immortalwrt-mt798x#104]
### Describe the bug

网络加速设置-快速转发引擎 出现
MediaTek HNAT / Ethernet HNAT Disabled | 绿 / 红

使用默认设置(deconfig/ax3000.*)只勾选turhoacc和 加入个人所使用的插件包互刷
即 带“插件”和不带“插件”的包互刷 问题依旧
检查网络相关配置文件 在“luci需要进行处理才能正常使用”后对比 发现无区别

快速转发引擎的其他设置:
启用以太网 HNAT
启用以太网 IPv6 HNAT
启用无线 HNAT
xt_FULLCONENAT
cubic

在编译之前已经执行过如下命令且无报错
git pull
./scripts/feeds update -a
./scripts/feeds install -a
make defconfig
make download -j8

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

mt7981

### Device

MT3000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by initzhu** [comment]
在日志中有如下内容

Enable hnat ipv6
Wed Aug  9 03:33:06 2023 kern.info kernel: [  231.747858] hnat hook is going to be disabled !
Wed Aug  9 03:34:30 2023 kern.info kernel: [  315.527283] hnat hook is going to be enabled !
Wed Aug  9 03:34:30 2023 kern.info kernel: [  315.531921] Enable hnat ipv6

**Comment by initzhu** [comment]
只要插入网线(配置过接口/网桥)就会出现“MediaTek HNAT / Ethernet HNAT Disabled”
恢复出厂设置依旧可复现

**Comment by czkwg8** [comment]
可能让大哥写日志的时候顺便也把原因写进去容易找一点
好像有pptp连接的时候会disable
l2tp我们这个应该没加进去

**Comment by hanwckf** [comment]
看下你安装的是luci-app-turboacc还是luci-app-turboacc-mtk

**Comment by initzhu** [comment]
使用"luci-app-turboacc-mtk"后 问题解决 
在git pull时注意到了这个软件包的加入 我没注意到 
当"luci-app-turboacc"被勾选时"luci-app-turboacc-mtk"会被隐藏

谢谢dalao解惑~
