### ISSUE TITLE
mt798x-7.6.6.1-src.tar.xz驱动包ePAeLNA iPAiLNA是两个文本信息？

### ISSUE THREAD

**Issue by benboguan** [hanwckf/immortalwrt-mt798x#109]
hanwckf大，是放错文件了吗？
![屏幕截图 2023-08-29 221010](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/834a2a92-4144-4536-b6d6-868bf9fdf649)
![屏幕截图 2023-08-29 221224](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/80f28402-b4d6-43c9-8cc1-23671fa68cd5)

**Comment by hanwckf** [comment]
这个是mtk的驱动包里漏掉了，实际上也没有影响，因为首先是读取本机Factory分区作为EEPROM
