### ISSUE TITLE
想更新一下 uboot，但报错

### ISSUE THREAD

**Issue by ningsibuqu** [hanwckf/immortalwrt-mt798x#11]
mtd write mt7981_360t7-fip-fixed-parts_atf-20231013_mtk-20230718_24.09.21.bin FIP

**Comment by lalasou** [comment]
先看看  cat /proc/mtd  名字是大写还是小写

装个mtd-rw 就可以读写这个分区了

**Comment by ningsibuqu** [comment]
> mtd-rw

root@ImmortalWrt:~# cat  /proc/mtd
dev:    size   erasesize  name
mtd0: 08000000 00020000 "spi0.0"
mtd1: 00100000 00020000 "BL2"
mtd2: 00080000 00020000 "u-boot-env"
mtd3: 00200000 00020000 "Factory"
mtd4: 00200000 00020000 "FIP"
mtd5: 06c00000 00020000 "ubi"
mtd6: 00100000 00020000 "stock-config"
mtd7: 00080000 00020000 "stock-factory"
mtd8: 00400000 00020000 "stock-log"


看是这样 接下来怎么操作呢？谢谢大佬神速回复

**Comment by lalasou** [comment]
很明显大写  或者直接mtd4

**Comment by ningsibuqu** [comment]
> 很明显大写 或者直接mtd4

谢谢，可以了，但为什么教程是小写...
