### ISSUE TITLE
能否适配一下H3C NX30 Pro 112M大分区？

### ISSUE THREAD

**Issue by Azreulo** [hanwckf/immortalwrt-mt798x#112]
### Describe the bug

如题，H3C里面只找到小分区的方案，空间不够装东西，能否适配一下112M大分区？

padavanonly/immortalwrtARM里面有112M的配置方案，但是不知如何移植。

求适配。

### ImmortalWrt version

latest

### ImmortalWrt target/subtarget

H3C NX30 Pro

### Device

H3C NX30 Pro

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
nx30pro因原厂yaffs分区的原因，不要使用原厂分区以外的任何大分区布局，否则可能导致nmbm错误标记坏块
