### ISSUE TITLE
添加wpad编译失败

### ISSUE THREAD

**Issue by longzhenren** [hanwckf/immortalwrt-mt798x#113]
### Describe the bug

branch: openwrt-21.02
.config file: https://github.com/longzhenren/AX6000-build/blob/main/.config
Error log: https://github.com/longzhenren/AX6000-build/actions/runs/6122479360/job/16618333230
description:
    ERROR: package/network/services/hostapd failed to build (build variant: wpad-full-internal).
请问应该如何修复？

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

mediatek/MT7986

### Device

XiaoMi Redmi Router AX6000

### Image kind

Self-built image

### Steps to reproduce

启动Actions，编译中报错    ERROR: package/network/services/hostapd failed to build (build variant: wpad-full-internal).

### Actual behaviour

    ERROR: package/network/services/hostapd failed to build (build variant: wpad-full-internal).

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
闭源无线驱动不支持与mac80211有关的任何软件包，必须使用本仓库里`defconfig`目录内的.config作为模板

**Comment by longzhenren** [comment]
> 闭源无线驱动不支持与mac80211有关的任何软件包，必须使用本仓库里`defconfig`目录内的.config作为模板

确实是使用了defconfig中的Ax6000的config 手动添加了wpad依赖用于无线桥接校园网进行EAP认证之用
