### ISSUE TITLE
Won't boot with WINBOND 25N01KVZEIR spi nand

### ISSUE THREAD

**Issue by GEEKiDoS** [hanwckf/immortalwrt-mt798x#114]
Just bought 2 360T7 routers, the first one with `ESMT F50L1G41LB` works perfectly fine.
another one comes with `WINBOND 25N01KVZEIR` just boot loops.

![1a49eac27b408147d78bde730ac1781e](https://github.com/hanwckf/immortalwrt-mt798x/assets/14933408/36e193cf-9de7-45d7-910c-b3cf5afbda4f)

Here's the log:

```log
[    0.538883] spi-nand spi0.0: calibration result: 0x3
[    0.543948] spi-nand spi0.0: unknown raw ID efae2100
[    0.548925] spi-nand: probe of spi0.0 failed with error -524
```
then kernel panic was occurred
```
[    7.640266] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    7.647736] Please append a correct "root=" boot option; here are the available partitions:
[    7.656081] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    7.664327] SMP: stopping secondary CPUs
[    7.668237] Kernel Offset: disabled
[    7.671712] CPU features: 0x00002,20002008
[    7.675792] Memory Limit: none
[    7.682394] Rebooting in 1 seconds..
```

I guess it was missing driver

**Comment by hanwckf** [comment]
Which version of the firmware you are using?

**Comment by GEEKiDoS** [comment]
https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=mediatek%2Ffilogic&id=qihoo_360t7-ubootmod
This one, r27537-7613856e97

**Comment by GEEKiDoS** [comment]
I have saw the commits, seems like it already fixed in this repo, but not fixed from the firmware selector. 
I'm going to build the firmware myself now, sorry for bothering.

**Comment by hanwckf** [comment]
> https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=mediatek%2Ffilogic&id=qihoo_360t7-ubootmod This one, r27537-7613856e97

This website use https://github.com/immortalwrt/immortalwrt as source code, which based on latest linux kernel and mt76 wireless driver.
