### ISSUE TITLE
2.4G WiFi 怎么设置才能消除 IOS 提示 「低安全性」提醒

### ISSUE THREAD

**Issue by ningsibuqu** [hanwckf/immortalwrt-mt798x#12]
![Y 25B_~K0GT5FKMY2A E5NC](https://user-images.githubusercontent.com/51028975/205439508-4c94ff79-b2fe-4ed6-b327-479c2873f19b.png)
![image](https://user-images.githubusercontent.com/51028975/205439530-aaa64df9-2bbb-4daf-97d8-46887fa20a4e.png)
已设置但不管用，谢谢。

**Comment by sdf8057** [comment]
算法选强制ccmp

**Comment by ningsibuqu** [comment]
> 强制ccmp

找不到...
![image](https://user-images.githubusercontent.com/51028975/205443206-75f978db-784d-4e22-a541-ae2a98a52f35.png)
下面都不可以选择
