### ISSUE TITLE
[功能请求] [MT7986] 支持 TUF-AX6000

### ISSUE THREAD

**Issue by cherinyy** [hanwckf/immortalwrt-mt798x#127]
TUF-AX6000（TX-AX6000）

https://github.com/openwrt/openwrt/commit/d522ccecb28f941aadcaf7a50cd6daa861f468a7
https://github.com/openwrt/openwrt/commit/0c3f4bd85ee6067588a81843a403850ab0082270

https://github.com/immortalwrt/immortalwrt/commit/d522ccecb28f941aadcaf7a50cd6daa861f468a7
https://github.com/immortalwrt/immortalwrt/commit/0c3f4bd85ee6067588a81843a403850ab0082270

~~这个不是重点，我主要是发现华硕提供的源代码中有不一样的 wocpu 固件：https://www.asus.com.cn/networking-iot-servers/wifi-routers/asus-gaming-routers/tx-ax6000/helpdesk_download/?model2Name=TX-AX6000~~

~~在`驱动程序和工具软件`标签页中，选择`操作系统`为`其他`即可下载源代码。~~

**Comment by ningsibuqu** [comment]
不一样是指👀

**Comment by cherinyy** [comment]
> 不一样是指

我只是单纯地比了下文件大小，我也不知道有没有用，没深入了解过。

**Comment by hanwckf** [comment]
华硕这个源码用的是更老的7.6.4.0无线驱动，以及2022年的wacpu/wocpu fw

**Comment by weitao1209** [comment]
能支持华硕TX-AX6000吗

**Comment by MYSY0327** [comment]
immortalwrt官方已经支持了

**Comment by Jackboy001** [comment]
immortalwrt官方用的驅動好像不能硬件加速？
