### ISSUE TITLE
隔离到新建接口的ra1被重新加入了br-lan

### ISSUE THREAD

**Issue by AlphaAnother** [hanwckf/immortalwrt-mt798x#13]
360T7
11月24号前我按照luci-app-guestwifi的init文件流程，新建了第二个2.4Gwifi ra1给iot设备，在接口新建了一个静态地址开dhcp服务器，接口的luci页面选上了ra1作为设备，防火墙配好了接口与内网lan隔离，之前工作正常，不过在前几天更新到最新commit后发现开机自动把ra1加入了br-lan，好像同时也连着新建接口，开机后iot设备获取到了lan口的dhcp地址（lan口的dhcp开了强制）尝试`brctl delif br-lan ra1`后正常了。
可否添加个选项不绑定指定的无线接口？

**Comment by hanwckf** [comment]
后续将完善无线脚本，可单独配置每个vif的启停状态及是否加入到br-lan

**Comment by qingxiwa** [comment]
> 360T7
> 11月24号前我按照luci-app-guestwifi的init文件流程，新建了第二个2.4Gwifi ra1给iot设备，在接口新建了一个静态地址开dhcp服务器，接口的luci页面选上了ra1作为设备，防火墙配好了接口与内网lan隔离，之前工作正常，不过在前几天更新到最新commit后发现开机自动把ra1加入了br-lan，好像同时也连着新建接口，开机后iot设备获取到了lan口的dhcp地址（lan口的dhcp开了强制）尝试`brctl delif br-lan ra1`后正常了。
> 可否添加个选项不绑定指定的无线接口？

原来默认绑定到br-lan，在没更新选项前，先用你的方法实现guest Wi-Fi。

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/3951b5a04a113e6cd50b4bcec4cea75b2f5e1bc0
