### ISSUE TITLE
无法持久化禁用 Wi-FI 接口，移除接口配置会导致设备配置丢失

### ISSUE THREAD

**Issue by cherinyy** [hanwckf/immortalwrt-mt798x#132]
### Describe the bug

无法持久化禁用无线接口，一旦网络配置有所变动，或者重启路由器，就会重新启用。

而如果选择移除接口配置，就会丢失设备配置。

![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/9050713/ff2815b2-cc10-44b7-bc5b-c1da363b3972)

### ImmortalWrt version

r0-ae0c192

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M

### Image kind

Self-built image

### Steps to reproduce

禁用 `ra0`  和 `rax0` 接口
或
删除 `ra0`  和 `rax0` 接口配置

### Actual behaviour

只是临时禁用接口
或
设备配置全部丢失

### Expected behaviour

持久化禁用接口
或
正常删除接口配置

### Additional info

因为我是拿来当 STA 无线中继客户端的，有线使用，所以不需要它作为 AP。

但是除了在 /etc/rc.local 添加，目前没有一个很好的方式来开机时禁用接口。而且一旦网络配置发生变动，就会导致它们重新启用。

```
sleep 15
ifconfig ra0 down
ifconfig rax0 down
```

相关议题：#79

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
目前已经支持无线dev层的禁用/启用（即能单独控制2.4g或者5g的启停），vif层的独立控制（如ra0, rax0, apcli0, apclix0）的功能未来再加上去

**Comment by hanwckf** [comment]
使用mtwifi-cfg应该可以单独控制vif接口的启停
