### ISSUE TITLE
RAX3000M-ERROR: package/feeds/packages/wget failed to build (build variant: ssl).

### ISSUE THREAD

**Issue by bwnqx** [hanwckf/immortalwrt-mt798x#133]
### Describe the bug

RAX3000M使用云编译报错，同版本编译360T7正常无报错。

### ImmortalWrt version

最新

### ImmortalWrt target/subtarget

最新

### Device

rax3000m

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by xiangfeidexiaohuo** [comment]
一样 就单单rax3000m 报错。。。

https://github.com/immortalwrt/immortalwrt/issues/1077 这里有答案 把wgetssl降级 就成 ，我试过没问题

**Comment by cherinyy** [comment]
Duplicate of #131

**Comment by bwnqx** [comment]
10/4编译已正常
