### ISSUE TITLE
mt_wifi WPS功能探讨！

### ISSUE THREAD

**Issue by benboguan** [hanwckf/immortalwrt-mt798x#134]
闲来无事几天，从你上传的wax220-gpl源码中抠出来WPS功能部分代码，测试初步可用。
@hanwckf 大佬，请问你开始就没做WPS，是因为有什么硬性BUG吗？
![屏幕截图 2023-10-02 165238](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/a794c0a8-fae4-49ec-9b11-bebfd669e9a4)
![屏幕截图 2023-10-02 165301](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/94cc3d81-4e15-412c-837e-afcc1c3db303)
![屏幕截图 2023-10-02 165310](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/dd1f5a48-6473-4a77-ac21-343c23471dd0)
![屏幕截图 2023-10-02 165343](https://github.com/hanwckf/immortalwrt-mt798x/assets/108057862/dc39e301-eaca-4054-bcd3-e29f8c59837a)

**Comment by sdf8057** [comment]
没有客户端支持wps功能了

**Comment by benboguan** [comment]
关联BUG太多，关了！
