### ISSUE TITLE
H3C NX30 Pro固件的交换机设置没有WAN口

### ISSUE THREAD

**Issue by jerryhan77** [hanwckf/immortalwrt-mt798x#138]
### Describe the bug

NX30 Pro固件的交换机设置页面中只有3个LAN口和对应的CPU接口(CPU-eth0)。
<img width="950" alt="NX30Pro_Switch" src="https://github.com/hanwckf/immortalwrt-mt798x/assets/2269263/fef257b0-0442-4594-8f03-79c2239db1b2">

而类似方案的360 T7固件可以设置WAN口和对应CPU接口(CPU-eth1)
<img width="950" alt="360T7_Switch" src="https://github.com/hanwckf/immortalwrt-mt798x/assets/2269263/490e68f7-5b81-4be3-9eb8-4598a2be3257">

不确定是适配Bug还是硬件限制。

### ImmortalWrt version

LATEST

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

H3C NX30 Pro

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by benboguan** [comment]
wan直连的CPU吧！

**Comment by hanwckf** [comment]
nx30pro硬件就是这样的，wan口直连cpu到gmac2，不需要经过交换机
