### ISSUE TITLE
ASR3000的固件编译出来刷机之后没有无线功能

### ISSUE THREAD

**Issue by lpflhh** [hanwckf/immortalwrt-mt798x#142]
### Describe the bug

ASR3000的固件编译出来刷机之后没有无线功能

### ImmortalWrt version

21

### ImmortalWrt target/subtarget

ASR3000的固件编译出来刷机之后没有无线功能

### Device

ASR3000

### Image kind

Official downloaded image

### Steps to reproduce

ASR3000的固件编译出来刷机之后没有无线功能

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by nature2608** [comment]
#52 请查看这个issus

**Comment by initzhu** [comment]
你make menuconfig的时候，读取一下 deconfig下面的带有'ax3000'的配置文件 然后编译即可

**Comment by lpflhh** [comment]
> 你make menuconfig的时候，读取一下 deconfig下面的带有'ax3000'的配置文件 然后编译即可

谢谢，已经搞定，建议把这个写入项目说明中

**Comment by lpflhh** [comment]
> #52 请查看这个issus

谢谢，已经搞定，建议把这个写入项目说明中
