### ISSUE TITLE
[功能请求]对透明代理的支持

### ISSUE THREAD

**Issue by initzhu** [hanwckf/immortalwrt-mt798x#143]
iptables-mod-socket
我尝试使用23.05的相关makefile进行配置。但是失败，提示缺少kmod-ipt-socket
我找不到这个能在哪里添加
https://openwrt.org/packages/pkgdata/iptables-mod-socket
https://openwrt.org/packages/pkgdata/kmod-ipt-socket

还有 dalao您的blog下线了
https://cmi.hanwckf.top/p/immortalwrt-mt798x/

**Comment by benboguan** [comment]
packages依赖包你可以尝试去天灵那边反馈试试！或者你自己fork后加入package
编译试试！
