### ISSUE TITLE
5G无线中继无法锁定BSSID

### ISSUE THREAD

**Issue by lllAlex2333** [hanwckf/immortalwrt-mt798x#164]
当前环境下存在同名的WIFI且信道相同，我在luci中无线中继设置选择的信号最强的那个wifi，但是会自动中继信号弱的那个，重启无线后变正常。
但是重启路由器后又自动中继到信号弱的那个wifi。
（已经勾选mac中继，但是没有效果）

**Comment by hanwckf** [comment]
尝试在无线dat文件（/etc/wireless/mediatek/）里修改`ApCliBssid`为目标ap的bssid，看看能不能指定

**Comment by lllAlex2333** [comment]
感谢H大回复，我按照你说的修改了（/etc/wireless/mediatek/）目录下DBDC_card0.dat与mt7981.dbdc.b1.dat两个文件中的ApCliBssid。目前中继正常，稳定运行3天，没有再出现我上面描述的问题。

**Comment by hanwckf** [comment]
> 感谢H大回复，我按照你说的修改了（/etc/wireless/mediatek/）目录下DBDC_card0.dat与mt7981.dbdc.b1.dat两个文件中的ApCliBssid。目前中继正常，稳定运行3天，没有再出现我上面描述的问题。

只修改mt7981.dbdc.bX.dat就可以了，DBDC_card0.dat是无线驱动自动合并生产的，这个配置项后续会加到luci配置里面

**Comment by hanwckf** [comment]
新版mtwifi-cfg配置界面里只需要在apcli接口设置里填入BSSID即可绑定上级AP的BSSID

**Comment by phoenixxie0** [comment]
目前似乎再次出现了这个问题，测试环境是AP+AC的组网环境，用360T7的5G中继某个指定的AP的BSSID。然而，360T7会自动连接其他的AP，查看AP的连接日志，并没有出现关于负载均衡或者弱信号剔除导致的漫游情况。并且已经按照上面的提示，检查了mt7981.dbdc.bX.dat文件，是包含又BSSID信息的。
