### ISSUE TITLE
nx30pro 使用默认配置 没有无线的luci

### ISSUE THREAD

**Issue by Potterli20** [hanwckf/immortalwrt-mt798x#167]
### Describe the bug

编译[log.txt](https://github.com/hanwckf/immortalwrt-mt798x/files/13398743/log.txt)

这个是配置文件
[config.txt](https://github.com/hanwckf/immortalwrt-mt798x/files/13398749/config.txt)

### ImmortalWrt version

21.01

### ImmortalWrt target/subtarget

21.01

### Device

nx 30pro

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 0x5826** [comment]
你从deconfig里复制7981的配置在这个基础上改就好了

**Comment by Potterli20** [comment]
> 你从deconfig里复制7981的配置在这个基础上改就好了

那就是不用make那个配置界面？
一弄就炸？

**Comment by padavanonly** [comment]
你从deconfig里复制7981的配置在这个基础上改就好了 +1

**Comment by xktx11** [comment]
使用defconfig目录内预置的配置文件作为配置模板，并运行make menuconfig进行配置

# 对于mt7981，推荐使用mt7981-ax3000.config
cp -f defconfig/mt7981-ax3000.config .config

# 对于mt7986，推荐使用mt7986-ax6000.config
# cp -f defconfig/mt7986-ax6000.config .config

make menuconfig

**Comment by Potterli20** [comment]
请问各位大佬
bin如何换itb
之前是刷imm固件23.05
但21.02的固件没有itb

**Comment by Potterli20** [comment]
请能和lede那边一样？
我这边刷不进去，编译出来格式是bin

**Comment by 0x5826** [comment]
nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
开源的uboot只能刷开源23.05固件
闭源的uboot刷闭源的固件

**Comment by Potterli20** [comment]
> nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
> 开源的uboot只能刷开源23.05固件
> 闭源的uboot刷闭源的固件

那闭源的uboot也没有啊
但是我刷了另一个uboot也没有办法启动

**Comment by 0x5826** [comment]
> > nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
> > 开源的uboot只能刷开源23.05固件
> > 闭源的uboot刷闭源的固件
> 
> 那闭源的uboot也没有啊 但是我刷了另一个uboot也没有办法启动

没办法直接送到你嘴里，自己去看看以下链接，另外可以保证固件和uboot肯定没问题（因为我测试了
https://cmi.hanwckf.top/p/mt798x-uboot-usage/
https://github.com/hanwckf/bl-mt798x

如果实在不懂，付费找人支持吧。

**Comment by Potterli20** [comment]
> > > nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
> > > 开源的uboot只能刷开源23.05固件
> > > 闭源的uboot刷闭源的固件
> > 
> > 那闭源的uboot也没有啊 但是我刷了另一个uboot也没有办法启动
> 
> 没办法直接送到你嘴里，自己去看看以下链接，另外可以保证固件和uboot肯定没问题（因为我测试了
> https://cmi.hanwckf.top/p/mt798x-uboot-usage/
> https://github.com/hanwckf/bl-mt798x
> 
> 如果实在不懂，付费找人支持吧。

我测试
nx30pro是没有无线的
太奇怪了
就默认配置，什么都没有调，都是没有无线

**Comment by 0x5826** [comment]
> > > > nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
> > > > 开源的uboot只能刷开源23.05固件
> > > > 闭源的uboot刷闭源的固件
> > > 
> > > 
> > > 那闭源的uboot也没有啊 但是我刷了另一个uboot也没有办法启动
> > 
> > 
> > 没办法直接送到你嘴里，自己去看看以下链接，另外可以保证固件和uboot肯定没问题（因为我测试了
> > https://cmi.hanwckf.top/p/mt798x-uboot-usage/
> > https://github.com/hanwckf/bl-mt798x
> > 如果实在不懂，付费找人支持吧。
> 
> 我测试 nx30pro是没有无线的 太奇怪了 就默认配置，什么都没有调，都是没有无线

刚编译了测试了下跟其他mt7981一样都有无线配置项且无线测试正常

**Comment by Potterli20** [comment]
> > > > > nbmn支持问题导致了，开源的uboot和闭源固件不兼容，记住就行了
> > > > > 开源的uboot只能刷开源23.05固件
> > > > > 闭源的uboot刷闭源的固件
> > > > 
> > > > 
> > > > 那闭源的uboot也没有啊 但是我刷了另一个uboot也没有办法启动
> > > 
> > > 
> > > 没办法直接送到你嘴里，自己去看看以下链接，另外可以保证固件和uboot肯定没问题（因为我测试了
> > > https://cmi.hanwckf.top/p/mt798x-uboot-usage/
> > > https://github.com/hanwckf/bl-mt798x
> > > 如果实在不懂，付费找人支持吧。
> > 
> > 我测试 nx30pro是没有无线的 太奇怪了 就默认配置，什么都没有调，都是没有无线
> 
> 刚编译了测试了下跟其他mt7981一样都有无线配置项且无线测试正常

好奇怪，我的nx30pro没有无线配置
