### ISSUE TITLE
360T7编译失败

### ISSUE THREAD

**Issue by siren202101** [hanwckf/immortalwrt-mt798x#17]
make[3]: Entering directory '/home/lmg/immortalwrt-mt798x/package/libs/nettle'
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/udns-0.4/.pkgdir/libudns/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.libudns_installed
echo "libudns" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/udns.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/feeds/packages/libs/udns'
time: package/feeds/packages/udns/compile#0.32#0.11#0.60
make[3]: Entering directory '/home/lmg/immortalwrt-mt798x/feeds/packages/lang/golang/golang'
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.libnfnetlink-1.0.2.tar.bz2.flock -c '    /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "libnfnetlink-1.0.2.tar.bz2" "b064c7c3d426efb4786e60a8e6859b82ee2f2c5e49ffeea640cfe4fe33cbc376" "" "http://www.netfilter.org/projects/libnfnetlink/files/" "ftp://ftp.netfilter.org/pub/libnfnetlink/"    '
mkdir -p /home/lmg/immortalwrt-mt798x/dl
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.nettle-3.6.tar.gz.flock -c '     /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "nettle-3.6.tar.gz" "d24c0d0f2abffbc8f4f34dcf114b0f131ec3774895f3555922fe2f40f3d5e3f1" "" "@GNU/nettle"    '
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.pcre-8.44.tar.bz2.flock -c '     /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "pcre-8.44.tar.bz2" "19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d" "" "@SF/pcre"    '
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
echo '0' | cmp -s - /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libnfnetlink.version || { echo '0' > /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libnfnetlink.version;  } 
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/libnfnetlink-1.0.2/.pkgdir/libnfnetlink/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.libnfnetlink_installed
echo "libnfnetlink" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libnfnetlink.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/package/libs/libnfnetlink'
time: package/libs/libnfnetlink/compile#0.27#0.11#0.56
make[3]: Entering directory '/home/lmg/immortalwrt-mt798x/feeds/packages/devel/gn'
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
echo '8' | cmp -s - /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libnettle.version || { echo '8' > /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libnettle.version;  } 
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/pcre-8.44/.pkgdir/libpcre/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/nettle-3.6/.pkgdir/libnettle/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.libnettle_installed
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.libpcre_installed
echo "libnettle" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/nettle.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/package/libs/nettle'
time: package/libs/nettle/compile#0.33#0.13#0.61
echo "libpcre" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/pcre.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/package/libs/pcre'
time: package/libs/pcre/compile#0.37#0.13#0.78
make[3]: Entering directory '/home/lmg/immortalwrt-mt798x/feeds/packages/libs/libcap-ng'
make[3]: Entering directory '/home/lmg/immortalwrt-mt798x/feeds/packages/net/vlmcsd'
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.go1.4-bootstrap-20171003.tar.gz.flock -c '       /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "go1.4-bootstrap-20171003.tar.gz" "f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96fe1102f0cb5c3e52" "" "https://dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju.edu.cn/golang/" "https://go.dev/dl/"    '
MAKEFLAGS="--jobserver-auth=3,4" /home/lmg/immortalwrt-mt798x/staging_dir/host/bin/ninja   -C /home/lmg/immortalwrt-mt798x/build_dir/hostpkg/gn-2022-11-10-1c4151ff/out
ninja: Entering directory `/home/lmg/immortalwrt-mt798x/build_dir/hostpkg/gn-2022-11-10-1c4151ff/out'
[1/285] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
/bin/sh: 1: clang++: not found
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/lmg/immortalwrt-mt798x/build_dir/hostpkg/gn-2022-11-10-1c4151ff/.built] Error 1
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/feeds/packages/devel/gn'
time: package/feeds/packages/gn/host-compile#0.15#0.06#0.30
    ERROR: package/feeds/packages/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/gn/host/compile] Error 1
make[2]: *** Waiting for unfinished jobs....
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.libcap-ng-0.8.1.tar.gz.flock -c '        /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "libcap-ng-0.8.1.tar.gz" "f06b17aaca029e245c9a26c698c6cc8a1cf42b58483d93e94ee02b478bdc1055" "" "https://people.redhat.com/sgrubb/libcap-ng"    '
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.vlmcsd-svn1113.tar.gz.flock -c '         /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "vlmcsd-svn1113.tar.gz" "62f55c48f5de1249c2348ab6b96dabbe7e38899230954b0c8774efb01d9c42cc" "" "https://codeload.github.com/Wind4/vlmcsd/tar.gz/svn1113?"    '
mkdir -p /home/lmg/immortalwrt-mt798x/dl
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.go1.18.8.src.tar.gz.flock -c '   /home/lmg/immortalwrt-mt798x/scripts/download.pl "/home/lmg/immortalwrt-mt798x/dl" "go1.18.8.src.tar.gz" "1f79802305015479e77d8c641530bc54ec994657d5c5271e0172eb7118346a12" "" "https://dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju.edu.cn/golang/" "https://go.dev/dl/"    '
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/libcap-ng-0.8.1/.pkgdir/libcap-ng/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
mkdir -p /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.libcap-ng_installed
SHELL= flock /home/lmg/immortalwrt-mt798x/tmp/.root-copy.flock -c 'cp -fpR /home/lmg/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/vlmcsd-svn1113/.pkgdir/vlmcsd/. /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.vlmcsd_installed
echo "libcap-ng" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/libcap-ng.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/feeds/packages/libs/libcap-ng'
time: package/feeds/packages/libcap-ng/compile#0.27#0.12#0.49
echo "vlmcsd" >> /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/vlmcsd.default.install
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/feeds/packages/net/vlmcsd'
time: package/feeds/packages/vlmcsd/compile#0.32#0.11#0.48
make[3]: Leaving directory '/home/lmg/immortalwrt-mt798x/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#0.77#0.42#1.28
make[2]: Leaving directory '/home/lmg/immortalwrt-mt798x'
make[1]: *** [package/Makefile:110: /home/lmg/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/lmg/immortalwrt-mt798x'
make[1]: Leaving directory '/home/lmg/immortalwrt-mt798x'
make: *** [/home/lmg/immortalwrt-mt798x/include/toplevel.mk:230: world] Error 2

**Comment by lalasou** [comment]
看了看你的 action 脚本
明显有问题....

和别人的比对下（虽然我的也有些小问题但是能用）

@hanwckf 大佬没直接出releases固件
感觉你还是直接用237大佬的固件吧

**Comment by hcym** [comment]
你就按照hanw的编译一次，不要加其他的，我都编译三次了，就是ttl没有输出，不知道是不是w11害的

**Comment by hanwckf** [comment]
看起来是缺少clang++的依赖

**Comment by ningsibuqu** [comment]
> 看了看你的 action 脚本 明显有问题....
> 
> 和别人的比对下（虽然我的也有些小问题但是能用）
> 
> @hanwckf 大佬没直接出releases固件 感觉你还是直接用237大佬的固件吧



> 看了看你的 action 脚本 明显有问题....
> 
> 和别人的比对下（虽然我的也有些小问题但是能用）
> 
> @hanwckf 大佬没直接出releases固件 感觉你还是直接用237大佬的固件吧

好像没人做纯净版的。
