### ISSUE TITLE
小米 AX3000T LAN1 和 LAN3 反了

### ISSUE THREAD

**Issue by iKirby** [hanwckf/immortalwrt-mt798x#170]
### Describe the bug

小米 AX3000T，接入网口是第一个和第二个，但是在“交换机”界面查看显示已接入的是第二个和第三个。测试发现 1 和 3 反了。

### ImmortalWrt version

r0-d63a69e

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

Xiaomi Mi Router AX3000T

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
因为AX3000T没有标注LAN次序，指定靠近电源接口的网口为WAN，然后依次是LAN1 LAN2 LAN3，与WR30U保持一致

**Comment by iKirby** [comment]
多谢解释。不好意思当时犯傻了，下意识以为从正面看的顺序才是对的
