### ISSUE TITLE
修改默认WIFI SSID不起作用

### ISSUE THREAD

**Issue by chentengming** [hanwckf/immortalwrt-mt798x#173]
### Describe the bug

修改mac80211.sh文件里面的set wireless.default_radio${devidx}.ssid=xxxxxx 不起作用，请问需要怎么改？

### ImmortalWrt version

r0-a57d347

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360 T7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
这是闭源驱动，没有用到mac80211。ssid在dat文件里
https://github.com/hanwckf/immortalwrt-mt798x/tree/openwrt-21.02/package/mtk/drivers/wifi-profile/files

**Comment by benboguan** [comment]
237大佬正解！

**Comment by xktx11** [comment]
# 修改闭源驱动2G wifi名称
sed -i 's/MT7981_AX3000_2.4G/ASR3000_2.4G/g' package/mtk/drivers/wifi-profile/files/mt7981/mt7981.dbdc.b0.dat

# 修改闭源驱动5G wifi名称
sed -i 's/MT7981_AX3000_5G/ASR3000_5G/g' package/mtk/drivers/wifi-profile/files/mt7981/mt7981.dbdc.b1.dat
