### ISSUE TITLE
[功能请求] [MT7986] 将 tp-xdr608x 的DTS文件分区和openwrt的分区调整为一致

### ISSUE THREAD

**Issue by resnou** [hanwckf/immortalwrt-mt798x#177]
这个是本项目的分区   
https://github.com/hanwckf/immortalwrt-mt798x/blob/openwrt-21.02/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-tl-xdr-common.dtsi

这是openwrt的分区
https://github.com/openwrt/openwrt/blob/main/target/linux/mediatek/dts/mt7986a-tplink-tl-xdr-common.dtsi

**Comment by padavanonly** [comment]
大多数人用的是那个带web界面的uboot，因而分区和lean仓库的用的同一个。
本仓库的很多机型分区都与主线op不同，如果有需求的自己改dts或者发pr加上主线分区dts支持。

**Comment by resnou** [comment]
> 大多数人用的是那个带web界面的uboot，因而分区和lean仓库的用的同一个。 本仓库的很多机型分区都与主线op不同，如果有需求的自己改dts或者发pr加上主线分区dts支持。

好吧，pr主线分区dts支持我不会，我还是手动修改分区吧。感谢提供tp-xdr608x的支持。

**Comment by resnou** [comment]
@padavanonly 大佬你好，我今天刷了那个[带web界面的uboot ](https://www.right.com.cn/forum/thread-8275955-1-1.html)
目前只能成功启动他帖子中的固件，其余的固件可以刷入，但是无法启动。
这个仓库的固件，你在恩山发的[固件](https://www.right.com.cn/forum/thread-8279716-1-1.html)，都没办法成功启动。
我看那个带web界面的uboot的上传日期是2024年，感觉是他更新了uboot，是不是分区修改了？

**Comment by resnou** [comment]
cat /proc/mtd 
```
dev:    size   erasesize  name
mtd0: 00100000 00020000 "bl2"
mtd1: 00060000 00020000 "config"
mtd2: 00060000 00020000 "factory"
mtd3: 001c0000 00020000 "reserved"
mtd4: 00200000 00020000 "fip"
mtd5: 07800000 00020000 "ubi"
```
