### ISSUE TITLE
TxRate=0 会导致小米ax3000t的MT7981.1.2@apclix0 5g热点扫描失败

### ISSUE THREAD

**Issue by seiry** [hanwckf/immortalwrt-mt798x#190]
### Describe the bug

https://github.com/hanwckf/immortalwrt-mt798x/commit/4a5fefb8ec64b916ab8e5699c86960d6821983bc#diff-15f7c83800ee51a3ea7ce46fcc1ddeff11c29808d3b66ac472a056e965f46ac5R344

这个commit中添加了`TxRate=0`，扫描5ghz 接入点时会导致`/luci/admin/network/wifi/apcli_scan/apclix0`接口超时。 

<img width="1100" alt="image" src="https://github.com/hanwckf/immortalwrt-mt798x/assets/4397354/eab6ff77-a4aa-4432-95e7-763daea6b969">

删除`/etc/wireless/mediatek/mt7981.dbdc.b1.dat`中的`TxRate=0`可以修复。同时，给老版本的编译产物增加`TxRate=0`可以复现该bug。

另外我在`MTK_Wi-Fi_SoftAP_Software_Programming_Guide`中也没有找到关于TxRate的具体说明

### ImmortalWrt version

r0-d2ecc79

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

Xiaomi Mi Router AX3000T

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
准备去除这个dat配置项目

**Comment by seiry** [comment]
@hanwckf 哈哈 辛苦大佬啦！
昨天提了issue之后又排查了一下，好像bug不只是dat那么简单，应该是`mtkwifi.scan_ap`会导致当前连接的wifi阻塞/断开，所以就关掉了issue。
再次说声感谢！哈哈

**Comment by hanwckf** [comment]
> @hanwckf 哈哈 辛苦大佬啦！ 昨天提了issue之后又排查了一下，好像bug不只是dat那么简单，应该是`mtkwifi.scan_ap`会导致当前连接的wifi阻塞/断开，所以就关掉了issue。 再次说声感谢！哈哈

我昨天也测试了下，TxRate跟这个问题无关，因为mt798x这代无线驱动在apcli扫描的时候遍历监听每个信道的时间较长，会导致对应频段已连接的无线设备断开，所以扫描的时候需要用有线或者另外一个频段来连接路由器操作
