### ISSUE TITLE
mtwifi-cfg.config和普通.config有什么区别？

### ISSUE THREAD

**Issue by wwwz251** [hanwckf/immortalwrt-mt798x#193]
大佬，defconfig目录下，多了mtwifi-cfg.config分支，这个和普通的.config有什么区别？翻了半天历史记录，好像没有说明

**Comment by w22gb8** [comment]
貌似现在最新的代码是openwrt原始wifi管理方式，mtwifi是之前的。

**Comment by Ljzkirito** [comment]
mtwifi-cfg.config是原生无线管理界面，普通的.config是luci-app-mtk，mtk管理界面。
个人建议使用mtwifi-cfg.config，且从普通的.config升级时，需要不勾选保留配置升级[即切换不同的管理界面时需要清空配置]，否则可能会无法启动WiFi。
![0](https://github.com/hanwckf/immortalwrt-mt798x/assets/66788052/655274e9-b17b-4116-83b5-7b2f66738fdc)
这是原生无线管理界面

**Comment by hanwckf** [comment]
https://cmi.hanwckf.top/p/immortalwrt-mt798x/

**Comment by iseeyou** [comment]
我使用mtwifi-cfg.config编译，但是网络 - 无线里面 无线安全 里面没有加密选项，MAC 过滤 高级设置 也没有菜单。
要勾选哪个？？？ @Ljzkirito

**Comment by hanwckf** [comment]
> 我使用mtwifi-cfg.config编译，但是网络 - 无线里面 无线安全 里面没有加密选项，MAC 过滤 高级设置 也没有菜单。 要勾选哪个？？？ @Ljzkirito

清空浏览器缓存

**Comment by nary24** [comment]
> 我使用mtwifi-cfg.config编译，但是网络 - 无线里面 无线安全 里面没有加密选项，MAC 过滤 高级设置 也没有菜单。 要勾选哪个？？？ @Ljzkirito

请问一下你这个解决了吗，我也遇到没有加密选项

**Comment by iseeyou** [comment]
> > 我使用mtwifi-cfg.config编译，但是网络 - 无线里面 无线安全 里面没有加密选项，MAC 过滤 高级设置 也没有菜单。 要勾选哪个？？？ @Ljzkirito
> 
> 请问一下你这个解决了吗，我也遇到没有加密选项

清空浏览器缓存

**Comment by nary24** [comment]
> > > 我使用mtwifi-cfg.config编译，但是网络 - 无线里面 无线安全 里面没有加密选项，MAC 过滤 高级设置 也没有菜单。 要勾选哪个？？？ @Ljzkirito
> > 
> > 
> > 请问一下你这个解决了吗，我也遇到没有加密选项
> 
> 清空浏览器缓存

好谢谢，执行清空了缓存了也没有。 后面我在immortalwrt的在线编译了
