### ISSUE TITLE
多wifi接口开机偶尔遇到个别无线不能启动的状况

### ISSUE THREAD

**Issue by w22gb8** [hanwckf/immortalwrt-mt798x#194]
### Describe the bug

2.4G/5G都开3个接入点，有时会遇到开机5G能全部启动，2.4G ra0能启动，ra1 ra2没启动
有没有方法避免这种情况，当前用脚本判断没启动ifconfig ra1 up

### ImmortalWrt version

21.02-SNAPSHOT, r0-6267349

### ImmortalWrt target/subtarget

21.02-SNAPSHOT, r0-6267349

### Device

redmi ax6000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
试一下用最新源码并选择`mt7986-ax6000-mtwifi-cfg.config`作为模板配置，开启多MBSSID时候要分别操作2个频段，不要一次新增
https://cmi.hanwckf.top/p/immortalwrt-mt798x/#mtwifi%E6%97%A0%E7%BA%BF%E9%85%8D%E7%BD%AE%E5%B7%A5%E5%85%B7%E8%AF%B4%E6%98%8E

**Comment by w22gb8** [comment]
> 试一下用最新源码并选择`mt7986-ax6000-mtwifi-cfg.config`作为模板配置，开启多MBSSID时候要分别操作2个频段，不要一次新增 https://cmi.hanwckf.top/p/immortalwrt-mt798x/#mtwifi%E6%97%A0%E7%BA%BF%E9%85%8D%E7%BD%AE%E5%B7%A5%E5%85%B7%E8%AF%B4%E6%98%8E

有时间我试试
