### ISSUE TITLE
请问 HNAT bind rate threshold (pps) 选项值如何填写？

### ISSUE THREAD

**Issue by chika0801** [hanwckf/immortalwrt-mt798x#195]
### Describe the bug

使用最新源码编译固件，在网络加速菜单中有

Enable ethernet HNAT for MACVLAN WAN device 默认选中

HNAT bind rate threshold (pps) 值是留空，会要求填写。不填写不会有异常。如果填写，有什么推荐标准或常用值吗？

![屏幕截图 2023-12-17 155636](https://github.com/hanwckf/immortalwrt-mt798x/assets/88967758/afb35626-f41e-49e5-9789-06176d1635ce)

### ImmortalWrt version

	ImmortalWrt 21.02-SNAPSHOT r20460-96d850d02a / LuCI openwrt-21.02 branch git-23.098.38725-847bd6b

### ImmortalWrt target/subtarget

mediatek/mt7986

### Device

AX6000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by BGzEroll** [comment]
貌似默认是30，开了eqos-mtk后会变成5

**Comment by chika0801** [comment]
感谢您的回答。

**Comment by hanwckf** [comment]
ppe驱动默认值是30pps，留空也就是30，代表新增连接的包速率达到30pps时才会被hnat加速。调低此阈值可让连接更容易被hnat加速，但也会导致ppe entry更容易被用光（每1个连接要占用2个ppe entry）。eqos将此值调低是为了尽可能让所有连接被ppe接管，以达到利用hqos进行限速的目的
