### ISSUE TITLE
如何开启两个PPE?

### ISSUE THREAD

**Issue by jxc98728** [hanwckf/immortalwrt-mt798x#198]
你好，我想问一下要如何config，可以开启两个MT7986的第二个PPE呢？

双PPE是否在高并发场景（比如BT）下有较好的提升？

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/blob/c19e6411670f55a55703f645dbf3b5d67cfb6a78/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-xiaomi-redmi-router-ax6000.dtsi#L132

只需要在设备树的hnat节点设置`mtketh-ppe-num = <2>;`

开启2个PPE后，WAN->LAN/WiFi方向的流量会使用PPE1进行加速，其它方向的流量仍然使用PPE0，并且HNAT驱动需要占用更多内存

每个PPE的entry数当前设置为32k，使用1个PPE时，最多可以加速16k个NAT连接；使用2个PPE时，最多可以加速32k个NAT连接（每个NAT连接需要占用2个PPE entry，分别为入站和出站方向）

**Comment by lalasou** [comment]
> https://github.com/hanwckf/immortalwrt-mt798x/blob/c19e6411670f55a55703f645dbf3b5d67cfb6a78/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-xiaomi-redmi-router-ax6000.dtsi#L132
> 
> 
> 
> 只需要在设备树的hnat节点设置`mtketh-ppe-num = <2>;`
> 
> 
> 
> 开启2个PPE后，WAN->LAN/WiFi方向的流量会使用PPE1进行加速，其它方向的流量仍然使用PPE0，并且HNAT驱动需要占用更多内存
> 
> 
> 
> 每个PPE的entry数当前设置为32k，使用1个PPE时，最多可以加速16k个NAT连接；使用2个PPE时，最多可以加速32k个NAT连接（每个NAT连接需要占用2个PPE entry，分别为入站和出站方向）

不需要config 配置的话  红米6000dtsi默认就是开启2个了对吧  直接编译不用管这部分了？

**Comment by hanwckf** [comment]
> > https://github.com/hanwckf/immortalwrt-mt798x/blob/c19e6411670f55a55703f645dbf3b5d67cfb6a78/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-xiaomi-redmi-router-ax6000.dtsi#L132
> > 
> > 只需要在设备树的hnat节点设置`mtketh-ppe-num = <2>;`
> > 开启2个PPE后，WAN->LAN/WiFi方向的流量会使用PPE1进行加速，其它方向的流量仍然使用PPE0，并且HNAT驱动需要占用更多内存
> > 每个PPE的entry数当前设置为32k，使用1个PPE时，最多可以加速16k个NAT连接；使用2个PPE时，最多可以加速32k个NAT连接（每个NAT连接需要占用2个PPE entry，分别为入站和出站方向）
> 
> 不需要config 配置的话 红米6000dtsi默认就是开启2个了对吧 直接编译不用管这部分了？

https://github.com/hanwckf/immortalwrt-mt798x/commit/c5668fe0823e700621a8d11f0a66bc5b3c7209c9

rax3000m和红米ax6000默认开启了

**Comment by muziling** [comment]
360 t7 512内存加上 mtketh-ppe-num = <2>;  也能开启两个ppe吗？  开启后只会增加内存占用，会有其它问题不，如果没问题的话，我就自己编译加上，反正512内存还空着280M没用。

**Comment by hanwckf** [comment]
> 360 t7 512内存加上 mtketh-ppe-num = <2>; 也能开启两个ppe吗？ 开启后只会增加内存占用，会有其它问题不，如果没问题的话，我就自己编译加上，反正512内存还空着280M没用。

可以开启，目前没发现啥问题

另外对于JCG Q30和CT3003这两个仅使用GMAC1的路由器，开启2个PPE后与1PPE是完全一样的，没有任何作用

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/0e595386ae39594c580c4d0d4bae978f4be733a3

给hnat驱动增加了一个ppe_cnt选项。如果已在dts里已经设置了`mtketh-ppe-num`属性，那么hnat驱动将直接使用dts里配置的ppe数量；如果dts里没有`mtketh-ppe-num`，那么hnat驱动会根据传入的`ppe_cnt`参数进行初始化，默认值为1。

在openwrt里直接修改`/etc/modules.d/20-mediatek_hnat`即可设置`ppe_cnt`参数，重启后生效。重启后使用`dmesg |grep "ppe num"`验证是否修改正常。

在256M内存的360T7上，开启2PPE后将额外占用约6M内存，开机后可用内存约为94M

**Comment by muziling** [comment]
我编译出来的固件没有 /etc/modules.d/20-mediatek_hnat 这个文件，是创建这个文件，文件内容写1或者2就可以了？
```
CONFIG_PACKAGE_kmod-mediatek_hnat=y
```
需要把y改成m才会有这个文件？默认defconfig里的配置应该是y

**Comment by hanwckf** [comment]
> 我编译出来的固件没有 /etc/modules.d/20-mediatek_hnat 这个文件，是创建这个文件，文件内容写1或者2就可以了？
> 
> ```
> CONFIG_PACKAGE_kmod-mediatek_hnat=y
> ```
> 
> 需要把y改成m才会有这个文件？默认defconfig里的配置应该是y

拉取最新源码后`make clean`再编译应该就有了，不需要动defconfig

**Comment by ningsibuqu** [comment]
256m 360t7 推荐上 2ppe 吗

**Comment by lalasou** [comment]
> 256m 360t7 推荐上 2ppe 吗
> 
> 

6m 内存占用  内存够用果断上

**Comment by ningsibuqu** [comment]
> > 256m 360t7 推荐上 2ppe 吗
> 
> 6m 内存占用 内存够用果断上

https://github.com/ningsibuqu/immortalwrt-mt798x/commit/b363a1e8ddaeada1ac7d8a3fc91a703c694c9bb3

就改这里就好了对吗？帮忙看看谢谢啦

**Comment by lalasou** [comment]
> > > 256m 360t7 推荐上 2ppe 吗
> 
> > 
> 
> > 6m 内存占用 内存够用果断上
> 
> 
> 
> https://github.com/ningsibuqu/immortalwrt-mt798x/commit/b363a1e8ddaeada1ac7d8a3fc91a703c694c9bb3
> 
> 
> 
> 就改这里就好了对吗？帮忙看看谢谢啦

上面大佬说了 最新版不用这样改了  麻烦

在openwrt里直接修改/etc/modules.d/20-mediatek_hnat即可设置ppe_cnt参数，重启后生效。重启后使用dmesg |grep "ppe num"验证是否修改正常。

**Comment by ningsibuqu** [comment]
开机94 用了几个小时稳定91 t7 256

**Comment by libiunc** [comment]
> https://github.com/hanwckf/immortalwrt-mt798x/blob/c19e6411670f55a55703f645dbf3b5d67cfb6a78/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-xiaomi-redmi-router-ax6000.dtsi#L132
> 
> 只需要在设备树的hnat节点设置`mtketh-ppe-num = <2>;`
> 
> 开启2个PPE后，WAN->LAN/WiFi方向的流量会使用PPE1进行加速，其它方向的流量仍然使用PPE0，并且HNAT驱动需要占用更多内存
> 
> 每个PPE的entry数当前设置为32k，使用1个PPE时，最多可以加速16k个NAT连接；使用2个PPE时，最多可以加速32k个NAT连接（每个NAT连接需要占用2个PPE entry，分别为入站和出站方向）

wifi->wifi 的流量也会走ppe进行加速吗? 
我在两个连接到wifi设备(mt7921->ax200)拉iperf3的时候发现cpu有很高的占用.怀疑加速失效,或者说wifi->wifi是没有加速的?
使用最新源码编译,使用luci-app-mtk进行无线配置,无线设置保持默认

**Comment by hanwckf** [comment]
> > https://github.com/hanwckf/immortalwrt-mt798x/blob/c19e6411670f55a55703f645dbf3b5d67cfb6a78/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7986a-xiaomi-redmi-router-ax6000.dtsi#L132
> > 
> > 只需要在设备树的hnat节点设置`mtketh-ppe-num = <2>;`
> > 开启2个PPE后，WAN->LAN/WiFi方向的流量会使用PPE1进行加速，其它方向的流量仍然使用PPE0，并且HNAT驱动需要占用更多内存
> > 每个PPE的entry数当前设置为32k，使用1个PPE时，最多可以加速16k个NAT连接；使用2个PPE时，最多可以加速32k个NAT连接（每个NAT连接需要占用2个PPE entry，分别为入站和出站方向）
> 
> wifi->wifi 的流量也会走ppe进行加速吗? 我在两个连接到wifi设备(mt7921->ax200)拉iperf3的时候发现cpu有很高的占用.怀疑加速失效,或者说wifi->wifi是没有加速的? 使用最新源码编译,使用luci-app-mtk进行无线配置,无线设置保持默认

无线到无线的硬件加速，目前只能支持不同无线虚拟接口下的加速，例如：5g rax0 <-> 2.4g ra0，5g rax0 <-> 5g rax1，5g rax0 <-> 5g apclix0等，同一个虚拟接口内关联的无线设备之间不支持加速

**Comment by hanwckf** [comment]
最新提交 https://github.com/hanwckf/immortalwrt-mt798x/commit/be2b71c18cca3ee26b22f4fce6a5ddcc1a9eddf4 已经将dts内的`mtketh-ppe-num`设置项删除，所有机型都统一使用`luci-app-turboacc-mtk`界面设置ppe数量（重启后生效）。
