### ISSUE TITLE
c19e641新版本switch 更新后 ，需要重新配置路由器吗？

### ISSUE THREAD

**Issue by hwlon** [hanwckf/immortalwrt-mt798x#199]
上次更新新版本后，就出现过恢复原先路由配置文件，能拨号成功，但很快连不上网络，重启后又好了，所以没在意。昨晚c19e641新版本switch 更新后 ，还是原先的路由配置文件，每次重启连上网络然后又很快直接连不上网络了， 初步排查估计与softetherVPN有关系，关掉后重启能正常连上网络，暂已回退96d850d，正常。c19e641新版本需要重新配置路由器吗？

**Comment by hanwckf** [comment]
不要恢复任何旧版本的配置文件，建议恢复出厂设置。sevpn没用过不清楚
