### ISSUE TITLE
HE模式 在首页概况里不会显示详细的一些信息

### ISSUE THREAD

**Issue by ghost** [hanwckf/immortalwrt-mt798x#200]
![Screenshot_20231224_163739](https://github.com/hanwckf/immortalwrt-mt798x/assets/154394145/25f1f3ac-89d0-473a-bbff-35f73c938f7b)
如图，HE(wifi6)模式下在首页-概况不会显示 mcs 等信息 VHT(wifi5)设备可以正常显示，这个问题只存在于首页-概况页面，在无线页面HE(wifi6)也是可以正常显示的

**Comment by benboguan** [comment]
其实就是/www/luci-static/resources/view/status/include/60_wifi.js被压缩了，和替换的wireless.js不匹配，可以用LUCI仓库的自己替换掉60_wifi.js试试，或者等等大佬修复吧！

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/luci/commit/5829eabba50ec0afa17d2ee486bc90dc15180c34
