### ISSUE TITLE
请问 ipv6获取比v4慢3s左右dropbear  必须手动重启才行 怎么改能不用手动

### ISSUE THREAD

**Issue by lalasou** [hanwckf/immortalwrt-mt798x#201]
请问 pppoe ipv6获取比v4慢3s左右dropbear 必须手动重启ipv6能连接到 怎么改能不用手动

个人问题 小白懂得太少啊       Dropbear 接口那里 设置未指定就行了

**Comment by xlighting2017** [comment]
仿照 `/etc/hotplug.d/iface/` 下面现成的例子， 写一个脚本，在 特定 interface 起来的时候，手动 sleep 一会儿，再运行/重启 dropbear

**Comment by lalasou** [comment]
> 仿照 `/etc/hotplug.d/iface/` 下面现成的例子， 写一个脚本，在 特定 interface 起来的时候，手动 sleep 一会儿，再运行/重启 dropbear


谢谢大佬  我试试  
这个 下面的脚本是同时运行的吧   
sleep  不会影响其他进程吧

**Comment by lalasou** [comment]
大概写了一下 看看情况吧

#!/bin/sh
if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ]; then
    sleep 5
    /etc/init.d/dropbear restart
    logger -t ssh "------RESTART  SSSH----------------------"
    if [ -f /tmp/log/smartdns/smartdns.log ]; then
    /etc/init.d/smartdns reload
    rm /tmp/log/smartdns/smartdns.log
    logger -t smartdns "------RESTART SMARTDNS----------------------"
    fi
fi
