### ISSUE TITLE
新的无线配置“mtwifi-cfg”的2点疑问请教

### ISSUE THREAD

**Issue by gavin8282** [hanwckf/immortalwrt-mt798x#204]
### Describe the bug

1、为何只有在2.4G配置中有“无线硬件加速”选项？
2、源码中有“Probe 802.11v support”“Probe 802.11r support”的内容，但是编译后却看不到。有没有计划？

### ImmortalWrt version

无

### ImmortalWrt target/subtarget

无

### Device

mt7981

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
whnat，dtim间隔，beacon间隔这三个设置在mtk sdk无线控制脚本里属于chip cfg，对于dbdc芯片而言需要两个频段同步设置，所以只保留2.4g部分的选项（因为2.4g频段的主接口ra0是dbdc主接口，修改2.4g频段的设置后，脚本会自动将这些设置同步到5g频段）

wireless.js里存在的那些11kvr设置是openwrt原有mac80211开源无线驱动的设置项目，与mtwifi闭源驱动无关所以不会显示，仅为了方便浏览代码修改记录所以保留这部分代码，以后会考虑将wappd mapd等加入，实现更好的漫游支持

**Comment by gavin8282** [comment]
> whnat，dtim间隔，beacon间隔这三个设置在mtk sdk无线控制脚本里属于chip cfg，对于dbdc芯片而言需要两个频段同步设置，所以只保留2.4g部分的选项（因为2.4g频段的主接口ra0是dbdc主接口，修改2.4g频段的设置后，脚本会自动将这些设置同步到5g频段）
> 
> wireless.js里存在的那些11kvr设置是openwrt原有mac80211开源无线驱动的设置项目，与mtwifi闭源驱动无关所以不会显示，仅为了方便浏览代码修改记录所以保留这部分代码，以后会考虑将wappd mapd等加入，实现更好的漫游支持

哦，明白了。期待您的更新

**Comment by gavin8282** [comment]
> whnat，dtim间隔，beacon间隔这三个设置在mtk sdk无线控制脚本里属于chip cfg，对于dbdc芯片而言需要两个频段同步设置，所以只保留2.4g部分的选项（因为2.4g频段的主接口ra0是dbdc主接口，修改2.4g频段的设置后，脚本会自动将这些设置同步到5g频段）
> 
> wireless.js里存在的那些11kvr设置是openwrt原有mac80211开源无线驱动的设置项目，与mtwifi闭源驱动无关所以不会显示，仅为了方便浏览代码修改记录所以保留这部分代码，以后会考虑将wappd mapd等加入，实现更好的漫游支持

还有个情况，不知道是不是个例。同样的硬件如果使用新的“mtwifi-cfg”，无线速率比使用旧的要好一些。

**Comment by hanwckf** [comment]
> > whnat，dtim间隔，beacon间隔这三个设置在mtk sdk无线控制脚本里属于chip cfg，对于dbdc芯片而言需要两个频段同步设置，所以只保留2.4g部分的选项（因为2.4g频段的主接口ra0是dbdc主接口，修改2.4g频段的设置后，脚本会自动将这些设置同步到5g频段）
> > wireless.js里存在的那些11kvr设置是openwrt原有mac80211开源无线驱动的设置项目，与mtwifi闭源驱动无关所以不会显示，仅为了方便浏览代码修改记录所以保留这部分代码，以后会考虑将wappd mapd等加入，实现更好的漫游支持
> 
> 还有个情况，不知道是不是个例。同样的硬件如果使用新的“mtwifi-cfg”，无线速率比使用旧的要好一些。

无论是新的mtwifi-cfg还是旧的luci app mtk，最终都是把无线设置写入dat文件生效的，实际上无线底层设置不会有任何区别
