### ISSUE TITLE
请问无线功率在哪里调整？

### ISSUE THREAD

**Issue by hxlls** [hanwckf/immortalwrt-mt798x#206]
看到恩山上237176253大佬的固件提到使用NX30PRO的高功率设置，5G相比默认增加了2dbm，请问，这个是应该修改源码什么位置达成的呢

**Comment by hxlls** [comment]
已解决

**Comment by s890214** [comment]
怎么解决的老哥,方案发一下呗,捡个漏也调一下

**Comment by chuds001** [comment]
@hxlls 能把修改无线功率的调整方法说一下吗？谢谢！
