### ISSUE TITLE
能否隐藏“架构”项的温度显示

### ISSUE THREAD

**Issue by exlulu** [hanwckf/immortalwrt-mt798x#220]
### Describe the bug

[此版](https://github.com/hanwckf/immortalwrt-mt798x/commit/41208baa4ddf6c57ecd51c7ab0067cfeb1c21b3b)隐藏了频率显示，但是多了温度显示，能否也隐藏掉？

![1](https://github.com/hanwckf/immortalwrt-mt798x/assets/35789196/cc5dde3e-55f4-475d-82d6-fe89b1cb6e92)

### ImmortalWrt version

41208baa4ddf6c57ecd51c7ab0067cfeb1c21b3b

### ImmortalWrt target/subtarget

360t7

### Device

360t7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by MeIsReallyBa** [comment]
一直都有温度显示，何谈“多了”

**Comment by exlulu** [comment]
> 一直都有温度显示，何谈“多了”

没看到我发的图吗？”架构“ 项和“温度“ 项都显示CPU温度，还不同步，这不是多了吗？而且 架构 项以前是显示频率，最近的41208ba才取消的，取消显示频率之后就变成现在那样显示温度了

**Comment by exlulu** [comment]
就算删掉温度代码还会有个括号。。
![2](https://github.com/hanwckf/immortalwrt-mt798x/assets/35789196/1f4a48f6-d9f7-483e-bb42-d5b94a4dd866)
