### ISSUE TITLE
安卓无线设备休眠一段时间后，ipv6网络连不通

### ISSUE THREAD

**Issue by pcslide** [hanwckf/immortalwrt-mt798x#225]
### Describe the bug

安卓无线设备休眠一段时间后，查看ipv6状态，地址信息仍在，但是无法连通ipv6网络。
表面的现象为，设备休眠一段时间后，淘宝之类支持ipv6的应用加载页面缓慢或无法加载页面。此时，ping 网关 local link ipv6地址是通的，但ping 公网ipv6 不通。这时关闭wifi后重开，立即能连回ipv6网络。
大概尝试了修改路由器wifi，mtu，广播设置，RA设置，都只能稍微改善这个问题，使得ipv6中断不那么频繁，并不能根治这问题。

备注：
网络拓扑方面，路由器作为ap使用，上联接线连在lan口，其他有线设备也连在lan口，本机ipv6 RA关闭，使用同一子网的光猫处理ipv6 RA 。
IOS的设备刚开始也遇到这样的问题，但把路由器 dl ofdma 和 dl mu-mimo两项关闭后，再也没遇到过ipv6中断。
之前用的路由器，使用自编译的 https://github.com/hanwckf/rt-n56u  固件，一样的网络拓扑，从来没遇到过类似问题。

### ImmortalWrt version

r20499-474b512901

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by jionkitten** [comment]
同样的问题，无线加密换成 WPA2/WPA3 后就没再出现了

**Comment by pcslide** [comment]
@jionkitten 
还真是这样，谢谢。可否告知你遇到问题的终端设备是什么牌子的？

我的n个小米的手机：自带无线模块是wifi6的设备，通过wpa2登录，一段时间ipv6会断。自带无线模块是wifi5的设备，通过wpa2登录就没问题。无奈我有台无线模块是wifi6的设备，仍然留在android 10，可能小米编译的时候没加wpa3参数，即使路由器切到wpa2/wpa3，它依然wpa2登录，ipv6会断。

我随便看了下wpa3/2的文档，也没看出是什么特性造成这样的区别。

发现原来自己用的android 10底层的miui后面还有几个新版本，升级了下，新版能用wpa3，问题解决了。

**Comment by hcym** [comment]
这个没有，我是重度6的用户，很敏感
就是今天最新版容易内存飙升导致挂机
快一年没刷了，哭哭

**Comment by pcslide** [comment]
@hcym 看这周反复改hnat的代码里有kernel panic，memory leak这样的字眼，编译的时候一般会选的更早的代码稳定期

**Comment by luckymoon** [comment]
我也有一样的问题，手机熄屏一会就连接不上ipv6地址了，用[test](https://testipv6.cn/)测试外网没有ipv6, 尝试了你的方法将无线加密改成wpa2/wpa3混合，还是没有解决。 只能不断重连wifi...郁闷
