### ISSUE TITLE
编译SSR无法使用，无限重启

### ISSUE THREAD

**Issue by Ailina0728** [hanwckf/immortalwrt-mt798x#228]
### Describe the bug

系统日志
Sun Jan 14 20:45:50 2024 daemon.info dnsmasq[11250]: Connected to system UBus
Sun Jan 14 20:46:08 2024 daemon.err uhttpd[2431]: Model vssr/log returns SimpleForm but is dispatched via cbi(),
Sun Jan 14 20:46:08 2024 daemon.err uhttpd[2431]: please change admin/services/vssr/log to use the form() action instead.
Sun Jan 14 20:46:10 2024 daemon.err uhttpd[2431]: Model vssr/log returns SimpleForm but is dispatched via cbi(),
Sun Jan 14 20:46:10 2024 daemon.err uhttpd[2431]: please change admin/services/vssr/log to use the form() action instead.
Sun Jan 14 20:46:21 2024 cron.err crond[11590]: crond (busybox 1.33.2) started, log level 5
Sun Jan 14 20:46:21 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:46:21 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:46:21 2024 daemon.info dnsmasq[11816]: Connected to system UBus
Sun Jan 14 20:47:12 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:12 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:12 2024 daemon.info dnsmasq[12333]: Connected to system UBus
Sun Jan 14 20:47:12 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:12 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:13 2024 daemon.info dnsmasq[12533]: Connected to system UBus
Sun Jan 14 20:47:24 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:24 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:24 2024 daemon.info dnsmasq[12909]: Connected to system UBus
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: ipset v7.6: Error in line 1: Set cannot be created: set with the same name already exists
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: iptables v1.8.7 (legacy): host/network `ERROR' not found
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: Try `iptables -h' or 'iptables --help' for more information.
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: ipset v7.6: Missing second mandatory argument to command add
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: Try `ipset help' for more information.
Sun Jan 14 20:47:32 2024 user.err ssr-rules[13193]: Start failed!
Sun Jan 14 20:47:32 2024 daemon.err uhttpd[2431]: ssr-rules[13193]: Start failed!
Sun Jan 14 20:47:32 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:32 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:32 2024 daemon.info dnsmasq[13448]: Connected to system UBus
Sun Jan 14 20:47:34 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:34 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:34 2024 daemon.info dnsmasq[13690]: Connected to system UBus
Sun Jan 14 20:47:40 2024 user.err ssr-rules[13902]: Start failed!
Sun Jan 14 20:47:40 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:47:40 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:47:41 2024 daemon.info dnsmasq[14155]: Connected to system UBus
Sun Jan 14 20:48:02 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:48:05 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:48:05 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:48:05 2024 daemon.info dnsmasq[14524]: Connected to system UBus
Sun Jan 14 20:48:12 2024 user.err ssr-rules[14720]: Start failed!
Sun Jan 14 20:48:12 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:48:12 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:48:12 2024 daemon.info dnsmasq[14974]: Connected to system UBus
Sun Jan 14 20:48:42 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:48:46 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:48:46 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:48:46 2024 daemon.info dnsmasq[15415]: Connected to system UBus
Sun Jan 14 20:48:52 2024 user.err ssr-rules[15621]: Start failed!
Sun Jan 14 20:48:52 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:48:52 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:48:53 2024 daemon.info dnsmasq[15875]: Connected to system UBus
Sun Jan 14 20:49:23 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:49:26 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:49:26 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:49:26 2024 daemon.info dnsmasq[16319]: Connected to system UBus
Sun Jan 14 20:49:33 2024 user.err ssr-rules[16525]: Start failed!
Sun Jan 14 20:49:33 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:49:33 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:49:33 2024 daemon.info dnsmasq[16779]: Connected to system UBus
Sun Jan 14 20:50:03 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:50:06 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:50:06 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:50:06 2024 daemon.info dnsmasq[17206]: Connected to system UBus
Sun Jan 14 20:50:13 2024 user.err ssr-rules[17403]: Start failed!
Sun Jan 14 20:50:13 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:50:13 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:50:13 2024 daemon.info dnsmasq[17657]: Connected to system UBus
Sun Jan 14 20:50:43 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:50:47 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:50:47 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:50:47 2024 daemon.info dnsmasq[18056]: Connected to system UBus
Sun Jan 14 20:50:53 2024 user.err ssr-rules[18263]: Start failed!
Sun Jan 14 20:50:53 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:50:53 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:50:54 2024 daemon.info dnsmasq[18517]: Connected to system UBus
Sun Jan 14 20:51:24 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:51:27 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:51:27 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:51:27 2024 daemon.info dnsmasq[18961]: Connected to system UBus
Sun Jan 14 20:51:34 2024 user.err ssr-rules[19167]: Start failed!
Sun Jan 14 20:51:34 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:51:34 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:51:34 2024 daemon.info dnsmasq[19444]: Connected to system UBus
Sun Jan 14 20:52:04 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:52:07 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:52:07 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:52:07 2024 daemon.info dnsmasq[19845]: Connected to system UBus
Sun Jan 14 20:52:14 2024 user.err ssr-rules[20043]: Start failed!
Sun Jan 14 20:52:14 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:52:14 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:52:14 2024 daemon.info dnsmasq[20320]: Connected to system UBus
Sun Jan 14 20:52:44 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:52:48 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:52:48 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:52:48 2024 daemon.info dnsmasq[20688]: Connected to system UBus
Sun Jan 14 20:52:54 2024 user.err ssr-rules[20908]: Start failed!
Sun Jan 14 20:52:54 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:52:54 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:52:55 2024 daemon.info dnsmasq[21162]: Connected to system UBus
Sun Jan 14 20:53:25 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:53:28 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:53:28 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:53:28 2024 daemon.info dnsmasq[21528]: Connected to system UBus
Sun Jan 14 20:53:35 2024 user.err ssr-rules[21747]: Start failed!
Sun Jan 14 20:53:35 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:53:35 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:53:35 2024 daemon.info dnsmasq[22001]: Connected to system UBus
Sun Jan 14 20:54:05 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:54:08 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:54:08 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:54:08 2024 daemon.info dnsmasq[22367]: Connected to system UBus
Sun Jan 14 20:54:15 2024 user.err ssr-rules[22587]: Start failed!
Sun Jan 14 20:54:15 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:54:15 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:54:15 2024 daemon.info dnsmasq[22841]: Connected to system UBus
Sun Jan 14 20:54:45 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:54:49 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:54:49 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:54:49 2024 daemon.info dnsmasq[23207]: Connected to system UBus
Sun Jan 14 20:54:55 2024 user.err ssr-rules[23426]: Start failed!
Sun Jan 14 20:54:55 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:54:55 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:54:56 2024 daemon.info dnsmasq[23680]: Connected to system UBus
Sun Jan 14 20:55:26 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:55:29 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:55:29 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:55:29 2024 daemon.info dnsmasq[24047]: Connected to system UBus
Sun Jan 14 20:55:36 2024 user.err ssr-rules[24268]: Start failed!
Sun Jan 14 20:55:36 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:55:36 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:55:36 2024 daemon.info dnsmasq[24522]: Connected to system UBus
Sun Jan 14 20:56:06 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:56:09 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:56:09 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:56:09 2024 daemon.info dnsmasq[24896]: Connected to system UBus
Sun Jan 14 20:56:16 2024 user.err ssr-rules[25115]: Start failed!
Sun Jan 14 20:56:16 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:56:16 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:56:16 2024 daemon.info dnsmasq[25369]: Connected to system UBus
Sun Jan 14 20:56:46 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:56:50 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:56:50 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:56:50 2024 daemon.info dnsmasq[25735]: Connected to system UBus
Sun Jan 14 20:56:56 2024 user.err ssr-rules[25955]: Start failed!
Sun Jan 14 20:56:57 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:56:57 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:56:57 2024 daemon.info dnsmasq[26209]: Connected to system UBus
Sun Jan 14 20:57:27 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:57:30 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:57:30 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:57:30 2024 daemon.info dnsmasq[26575]: Connected to system UBus
Sun Jan 14 20:57:37 2024 user.err ssr-rules[26794]: Start failed!
Sun Jan 14 20:57:37 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:57:37 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:57:37 2024 daemon.info dnsmasq[27048]: Connected to system UBus
Sun Jan 14 20:58:07 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:58:10 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:58:10 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:58:11 2024 daemon.info dnsmasq[27414]: Connected to system UBus
Sun Jan 14 20:58:17 2024 user.err ssr-rules[27633]: Start failed!
Sun Jan 14 20:58:17 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:58:17 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:58:17 2024 daemon.info dnsmasq[27887]: Connected to system UBus
Sun Jan 14 20:58:47 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:58:51 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:58:51 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:58:51 2024 daemon.info dnsmasq[28255]: Connected to system UBus
Sun Jan 14 20:58:57 2024 user.err ssr-rules[28475]: Start failed!
Sun Jan 14 20:58:58 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:58:58 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:58:58 2024 daemon.info dnsmasq[28729]: Connected to system UBus
Sun Jan 14 20:59:28 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Sun Jan 14 20:59:31 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:59:31 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:59:31 2024 daemon.info dnsmasq[29094]: Connected to system UBus
Sun Jan 14 20:59:38 2024 user.err ssr-rules[29314]: Start failed!
Sun Jan 14 20:59:38 2024 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jan 14 20:59:38 2024 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jan 14 20:59:38 2024 daemon.info dnsmasq[29568]: Connected to system UBus
Sun Jan 14 20:59:51 2024 kern.notice kernel: [  934.434737] 7986@C08L3,ap_peer_auth_req_at_idle_action() 717: AUTH - MBSS(0), Rcv AUTH seq#1, Alg=0, Status=0 from [wcid=1023]f4:70:ab:50:ab:a4
Sun Jan 14 20:59:51 2024 kern.debug kernel: [  934.447631] entrytb_aid_aquire(): found non-occupied aid:2, allocated from:2
Sun Jan 14 20:59:51 2024 kern.warn kernel: [  934.454682] 7986@C13L2,MacTableInsertEntry() 1537: New Sta:f4:70:ab:50:ab:a4
Sun Jan 14 20:59:53 2024 kern.warn kernel: [  936.464862] 7986@C01L2,wifi_sys_disconn_act() 1002:  wdev_idx=0
Sun Jan 14 20:59:53 2024 kern.warn kernel: [  936.471036] 7986@C13L2,MacTableDeleteEntry() 1793: Del Sta:f4:70:ab:50:ab:a4
Sun Jan 14 20:59:53 2024 kern.notice kernel: [  936.478254] 7986@C08L3,ap_peer_deauth_action() 429: AUTH - receive DE-AUTH(seq-3384) from f4:70:ab:50:ab:a4, reason=1
Sun Jan 14 21:00:08 2024 user.notice shadowsocksr: ssrplus redir tcp error.restart!

SSR日志
2024-01-14 20:54:05: ssrplus redir tcp error.restart!
2024-01-14 20:53:35: -----------end------------
2024-01-14 20:53:28: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:53:28: ----------start------------
2024-01-14 20:53:25: ssrplus redir tcp error.restart!
2024-01-14 20:52:55: -----------end------------
2024-01-14 20:52:48: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:52:48: ----------start------------
2024-01-14 20:52:44: ssrplus redir tcp error.restart!
2024-01-14 20:52:14: -----------end------------
2024-01-14 20:52:07: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:52:07: ----------start------------
2024-01-14 20:52:04: ssrplus redir tcp error.restart!
2024-01-14 20:51:34: -----------end------------
2024-01-14 20:51:27: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:51:27: ----------start------------
2024-01-14 20:51:24: ssrplus redir tcp error.restart!
2024-01-14 20:50:54: -----------end------------
2024-01-14 20:50:47: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:50:47: ----------start------------
2024-01-14 20:50:43: ssrplus redir tcp error.restart!
2024-01-14 20:50:13: -----------end------------
2024-01-14 20:50:06: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:50:06: ----------start------------
2024-01-14 20:50:03: ssrplus redir tcp error.restart!
2024-01-14 20:49:33: -----------end------------
2024-01-14 20:49:26: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:49:26: ----------start------------
2024-01-14 20:49:23: ssrplus redir tcp error.restart!
2024-01-14 20:48:53: -----------end------------
2024-01-14 20:48:46: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:48:46: ----------start------------
2024-01-14 20:48:42: ssrplus redir tcp error.restart!
2024-01-14 20:48:12: -----------end------------
2024-01-14 20:48:06: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:48:05: ----------start------------
2024-01-14 20:48:02: ssrplus redir tcp error.restart!
2024-01-14 20:47:41: -----------end------------
2024-01-14 20:47:34: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:47:34: ----------start------------
2024-01-14 20:47:32: -----------end------------
2024-01-14 20:47:25: Main node:Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64) Started!
2024-01-14 20:47:24: ----------start------------
2024-01-14 20:47:13: -----------end------------
2024-01-14 20:47:12: 禁止连接的域名加载完毕。
2024-01-14 20:47:12: 未启动主节点，禁止连接的域名正在加载。
2024-01-14 20:47:12: ----------start------------
2024-01-14 20:44:48: -----------end------------
2024-01-14 20:44:48: 禁止连接的域名加载完毕。
2024-01-14 20:44:48: 未启动主节点，禁止连接的域名正在加载。
2024-01-14 20:44:48: ----------start------------
2024-01-14 20:44:48: boot！

测试了几天，默认配置只编译ssr进固件也不行，vless节点确定是没问题的。无限重启，主界面显示未运行，同样的编译vssr无法导入节点，也不行。插件来源

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

immortalwrt-mt798x

### Device

JDCLOUD-AX6000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by Aes64X** [comment]
你需要去插件来源反馈，hanwckf基本不会管这些。
另外，lean的SSR是可以正常使用的，只需要复制粘贴进来，再移除hanwckf库里面原本的重复依赖就行了。

**Comment by Aes64X** [comment]
同时，建议你将go版本升级到1.21，同样，只需复制粘贴，删除原有的。

**Comment by iseeyou** [comment]
最近编译几次是启动后shadowsocksr没有启动，要到启动项点 重启shadowsocksr，才正常工作。

**Comment by muziling** [comment]
SSR自己的问题，我没用SSR，但是运行了一样的二进制软件，一切运行正常。
反馈问题反馈错地方了，要去SSR那里反馈

**Comment by Ailina0728** [comment]
> SSR自己的问题，我没用SSR，但是运行了一样的二进制软件，一切运行正常。 反馈问题反馈错地方了，要去SSR那里反馈

你用的哪个工具啊

**Comment by Ailina0728** [comment]
> 你需要去插件来源反馈，hanwckf基本不会管这些。 另外，lean的SSR是可以正常使用的，只需要复制粘贴进来，再移除hanwckf库里面原本的重复依赖就行了。

收到，我马上去尝试。感谢回复

**Comment by ATang007ZH** [comment]
> 你需要去插件来源反馈，hanwckf基本不会管这些。 另外，lean的SSR是可以正常使用的，只需要复制粘贴进来，再移除hanwckf库里面原本的重复依赖就行了。

小白一枚。能不能详细说说是哪些内容？
1/复制  哪个目录？   粘贴   到哪个目录下？
2/hanwckf库里面原本的重复依赖，有哪些？怎么移除？
