### ISSUE TITLE
无线配置页面不能配置加密模式

### ISSUE THREAD

**Issue by WHJWNAVY** [hanwckf/immortalwrt-mt798x#232]
### Describe the bug

* 无线配置页面不能配置加密模式，但是直接修改wireless配置文件可以生效
![图片](https://github.com/hanwckf/immortalwrt-mt798x/assets/16632096/6c8ea38c-eedb-4427-aeb4-2d402049cfc6)
![图片](https://github.com/hanwckf/immortalwrt-mt798x/assets/16632096/54390e26-5729-4822-8b42-76a9565a73e7)

### ImmortalWrt version

r20549-dabfebc9a0

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
尝试清空浏览器缓存后刷新一下

**Comment by Canary233** [comment]
同rax3000m emmc,最新源码可复现,清除缓存也不行 @hanwckf

**Comment by nary24** [comment]
> 同rax3000m emmc,最新源码可复现,清除缓存也不行 @hanwckf

你好，请问一下你现在是怎么弄好的，我也是遇到相同问题

**Comment by carrothu-cn** [comment]
我也遇到相同问题，清空缓存也不能设置加密
