### ISSUE TITLE
rax3000M，ipv6中继，能获取ip但不能ping通外网

### ISSUE THREAD

**Issue by ashesofdream** [hanwckf/immortalwrt-mt798x#235]
### Describe the bug

rax3000M，wan口指定为主接口，lan指定为中继模式，成功获取ipv6地址，但无法ping通外网，好像用原版immortal也有这个问题

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT r20499-474b512901

### ImmortalWrt target/subtarget

arm?

### Device

rax3000m

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by waxl** [comment]
入手小米3000t，编译刷机后，一样ipv6中继模式，可以获得地址但是不能连通，目前解决了，可以试试下面方法
https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/network/services/odhcpd/Makefile#L15
更新到版本2023-10-24

https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/mtk/drivers/mt_wifi/Makefile#L11
MT7981_FW_DIR := mt7981-fw-20230330

https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/mtk/drivers/warp/Makefile#L14
MT7981_NEW_WOFW_DIR := mt7981-fw-20230717       //小米出厂固件1.0.47里是这版本日期
mt7981-ax3000.config 添加 CONFIG_WARP_NEW_FW=y

**Comment by ashesofdream** [comment]
> 入手小米3000t，编译刷机后，一样ipv6中继模式，可以获得地址但是不能连通，目前解决了，可以试试下面方法
> 
> https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/network/services/odhcpd/Makefile#L15
> 
> 
> 更新到版本2023-10-24
> https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/mtk/drivers/mt_wifi/Makefile#L11
> 
> 
> MT7981_FW_DIR := mt7981-fw-20230330
> https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/package/mtk/drivers/warp/Makefile#L14
> 
> 
> MT7981_NEW_WOFW_DIR := mt7981-fw-20230717 //小米出厂固件1.0.47里是这版本日期
> mt7981-ax3000.config 添加 CONFIG_WARP_NEW_FW=y

估计不是odhcp版本的问题，我用原本immortal好像也不行....现在nat6暂时顶着
