### ISSUE TITLE
New binary 7.6.7.1 driver in GL-MT6000 beta firmware

### ISSUE THREAD

**Issue by MarvinOl** [hanwckf/immortalwrt-mt798x#236]
### Describe the bug

This is not a bug but information that GL-MT6000 has beta firmware by GL.inet where they are using version 7.6.7.1 driver.
gl-mt6000-sdk-4.5.7-1.29.bin:
https://drive.google.com/file/d/1Ai2H4XBCe_OZhSNYHeyuFiyR6bzPa5Qr/view

**Comment by 0x5826** [comment]
4.5.7 Release note from gl-inet:
**This is snapshot firmware, generated by an automatic compiler, please use caution.**

https://dl.gl-inet.com/?model=mt6000&type=snapshot

**Comment by MarvinOl** [comment]
No, that is not the same. The official snapshot build is still using mt76 driver. But because people were complaining a lot they created a build based on the official sdk driver that I linked above.

**Comment by hanwckf** [comment]
It looks like gl-inet is tormented by mt76 open source driver
