### ISSUE TITLE
bpi-r3 mini 编译报错 /sys/class/pwm/pwmchip0/export: Permission denied

### ISSUE THREAD

**Issue by kevinfay** [hanwckf/immortalwrt-mt798x#237]
不知是哪个环节出了问题
`cp -fpR /home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek /home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root.orig-mediatek
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 8: /sys/class/pwm/pwmchip0/export: Permission denied
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 9: /sys/class/pwm/pwmchip0/pwm0/period: No such file or directory
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 10: /sys/class/pwm/pwmchip0/pwm0/duty_cycle: No such file or directory
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 11: /sys/class/pwm/pwmchip0/pwm0/polarity: No such file or directory
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 12: /sys/class/pwm/pwmchip0/pwm0/enable: No such file or directory
/home/kevin/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/fanspeed: line 22: /sys/class/pwm/pwmchip0/pwm0/duty_cycle: No such file or directory`

**Comment by ggg70** [comment]
@kevinfay Please, could you tell me if you are using eMMC? I succeeded to compile this immortalwrt version for bpi-r3 mini (emmc) but there is no mmc partition table and no fip in the results, only the initramfs and sysupgrade bin files. I do not know how to install them, can you help me? Thank you!
