### ISSUE TITLE
反馈 目前发现 tl-xdr608x系列两个小问题

### ISSUE THREAD

**Issue by 0x5826** [hanwckf/immortalwrt-mt798x#239]
1. 2.5G网口灯在2.5G速率时不亮，猜测需要合并类似 [LED fixed, all works! TODO: reduce unused code and push to mainline](https://github.com/cyyself/xdr608x-rtl8221-fix/commit/9f6fe42c6374f3b0178010caffdaf885ae7c0c95)

2. wifi网口的mac地址是随机生成的，应该是没获取到准确的wifi mac地址

当然上述的问题不影响日常使用

**Comment by hanwckf** [comment]
d3ab1bf5e6ac5f2e0bda875a873f6c1b7a84b7d7

**Comment by 0x5826** [comment]
感谢hanwckf大佬！我这两天测试下

**Comment by 0x5826** [comment]
> [d3ab1bf](https://github.com/hanwckf/immortalwrt-mt798x/commit/d3ab1bf5e6ac5f2e0bda875a873f6c1b7a84b7d7)

经过测试问题 1 已解决，问题2缺少$label_mac导致wifi mac设置依然不生效，我已经提交了一个pr #242 修复了
另外mac地址参考官方的设定，我自己编译固件已经测试通过
