### ISSUE TITLE
外接usb设备启用hnat问题

### ISSUE THREAD

**Issue by CMCCAdmin** [hanwckf/immortalwrt-mt798x#241]
### Describe the bug

首先感谢大佬的辛勤付出，我在使用过程中遇到一些问题: 

1.  插入移远em06 4g模块后(自动加载qmi驱动)，使用modemmanager拨号能正常获取ipv4/v6地址，生成的接口为wwan0，但是只能ping通公网，任何tcp/udp数据都不通，关闭hant后则正常。
2.  使用rtl8156 usb 2.5g网卡作为wan接口(eth2)，为了给这个网卡加速我在ext-devices-prefix 添加了eth前缀，如果把eth作为独立的wan无线速率只有10Mbps，如果把eth2加入br-lan后无线速率最高能跑到1.6Gbps。

### ImmortalWrt version

r0-2f36f44

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

cmcc-rax3000m

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
只测过移远5g模块，4g那速率就关hnat用吧，我们也没4g模块

移远5g的qmi驱动当时测试的是这个 https://github.com/coolsnowwolf/lede/tree/master/package/wwan/driver

**Comment by padavanonly** [comment]
至于第二个，写eth2别只写eth，不然ppd的eth0会被错误识别

**Comment by hanwckf** [comment]
rtl8156这类识别成ethX的usb网卡需要额外补丁改成usbX之类的接口名，在prefix里指定eth开头的话会错误地把gmac加到ext-devices里导致HNAT功能异常

**Comment by hanwckf** [comment]
关于问题2，可以尝试把下面这个补丁命名为`753-usbnet-force-ifname-usbX.patch`，放进`target/linux/mediatek/patches-5.4/`目录后重新编译试一下。

```patch
Index: linux-5.4.255/drivers/net/usb/usbnet.c
===================================================================
--- linux-5.4.255.orig/drivers/net/usb/usbnet.c
+++ linux-5.4.255/drivers/net/usb/usbnet.c
@@ -1735,10 +1735,12 @@ usbnet_probe (struct usb_interface *udev
 		// heuristic:  "usb%d" for links we know are two-host,
 		// else "eth%d" when there's reasonable doubt.  userspace
 		// can rename the link if it knows better.
+		/*
 		if ((dev->driver_info->flags & FLAG_ETHER) != 0 &&
 		    ((dev->driver_info->flags & FLAG_POINTTOPOINT) == 0 ||
 		     (net->dev_addr [0] & 0x02) == 0))
 			strcpy (net->name, "eth%d");
+		*/
 		/* WLAN devices should always be named "wlan%d" */
 		if ((dev->driver_info->flags & FLAG_WLAN) != 0)
 			strcpy(net->name, "wlan%d");
```

**Comment by CMCCAdmin** [comment]
> 关于问题2，可以尝试把下面这个补丁命名为`753-usbnet-force-ifname-usbX.patch`，放进`target/linux/mediatek/patches-5.4/`目录后重新编译试一下。
> 
> ```diff
> Index: linux-5.4.255/drivers/net/usb/usbnet.c
> ===================================================================
> --- linux-5.4.255.orig/drivers/net/usb/usbnet.c
> +++ linux-5.4.255/drivers/net/usb/usbnet.c
> @@ -1735,10 +1735,12 @@ usbnet_probe (struct usb_interface *udev
>  		// heuristic:  "usb%d" for links we know are two-host,
>  		// else "eth%d" when there's reasonable doubt.  userspace
>  		// can rename the link if it knows better.
> +		/*
>  		if ((dev->driver_info->flags & FLAG_ETHER) != 0 &&
>  		    ((dev->driver_info->flags & FLAG_POINTTOPOINT) == 0 ||
>  		     (net->dev_addr [0] & 0x02) == 0))
>  			strcpy (net->name, "eth%d");
> +		*/
>  		/* WLAN devices should always be named "wlan%d" */
>  		if ((dev->driver_info->flags & FLAG_WLAN) != 0)
>  			strcpy(net->name, "wlan%d");
> ```

我尝试make clean并重新编译，刷入后还是识别成eth2

**Comment by hanwckf** [comment]
rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？

**Comment by CMCCAdmin** [comment]
> rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？

r8152的厂商驱动

**Comment by hanwckf** [comment]
> > rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？
> 
> r8152的厂商驱动

需要对r8152驱动进行改动，把下面这个补丁命名为`101-rename-ifname-to-usbX.patch`，放在`/home/hanwckf/immortalwrt-mt798x/package/kernel/r8152/patches/`后重新编译试一下。注意要选择vendor版本的驱动。


```patch
--- a/r8152.c
+++ b/r8152.c
@@ -20599,6 +20599,8 @@ static int rtl8152_probe(struct usb_inte
 		tp->sg_use = true;
 #endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(5,2,3) */
 
+	strcpy(netdev->name, "usb%d");
+
 #if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,29)
 	netdev->open = rtl8152_open;
 	netdev->stop = rtl8152_close;
```
![{22126-x-794383226571}](https://github.com/hanwckf/immortalwrt-mt798x/assets/27666983/2431e408-df62-49d6-a793-85dc3ba3d608)

**Comment by CMCCAdmin** [comment]
> > > rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？
> > 
> > 
> > r8152的厂商驱动
> 
> 需要对r8152驱动进行改动，把下面这个补丁命名为`101-rename-ifname-to-usbX.patch`，放在`/home/hanwckf/immortalwrt-mt798x/package/kernel/r8152/patches/`后重新编译试一下。注意要选择vendor版本的驱动。
> 
> ```diff
> --- a/r8152.c
> +++ b/r8152.c
> @@ -20599,6 +20599,8 @@ static int rtl8152_probe(struct usb_inte
>  		tp->sg_use = true;
>  #endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(5,2,3) */
>  
> +	strcpy(netdev->name, "usb%d");
> +
>  #if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,29)
>  	netdev->open = rtl8152_open;
>  	netdev->stop = rtl8152_close;
> ```
> 
> ![{22126-x-794383226571}](https://private-user-images.githubusercontent.com/27666983/301486529-2431e408-df62-49d6-a793-85dc3ba3d608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIzNjMsIm5iZiI6MTcwNjc5MjA2MywicGF0aCI6Ii8yNzY2Njk4My8zMDE0ODY1MjktMjQzMWU0MDgtZGY2Mi00OWQ2LWE3OTMtODVkYzNiYTNkNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTNhYWU5OTAzYmFmZjNjYTlhM2M2ZDE4YWQ3ZmRmY2Q5NjBkMDhkZDMzNTIzMzU0ZWY3NGU2MTAwZjljNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aN1rSSq1VFUfgN6ZTAZs5X6a32mShRrljnsoaFzqYWg)

这次网卡重命名成功，但是问题旧。usb作为wan(dhcp)到wifi只有10mbps。
之前添加的eth前缀编译前已经删除了

**Comment by hanwckf** [comment]
> > > > rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？
> > > 
> > > 
> > > r8152的厂商驱动
> > 
> > 
> > 需要对r8152驱动进行改动，把下面这个补丁命名为`101-rename-ifname-to-usbX.patch`，放在`/home/hanwckf/immortalwrt-mt798x/package/kernel/r8152/patches/`后重新编译试一下。注意要选择vendor版本的驱动。
> > ```diff
> > --- a/r8152.c
> > +++ b/r8152.c
> > @@ -20599,6 +20599,8 @@ static int rtl8152_probe(struct usb_inte
> >  		tp->sg_use = true;
> >  #endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(5,2,3) */
> >  
> > +	strcpy(netdev->name, "usb%d");
> > +
> >  #if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,29)
> >  	netdev->open = rtl8152_open;
> >  	netdev->stop = rtl8152_close;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![{22126-x-794383226571}](https://private-user-images.githubusercontent.com/27666983/301486529-2431e408-df62-49d6-a793-85dc3ba3d608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIzNjMsIm5iZiI6MTcwNjc5MjA2MywicGF0aCI6Ii8yNzY2Njk4My8zMDE0ODY1MjktMjQzMWU0MDgtZGY2Mi00OWQ2LWE3OTMtODVkYzNiYTNkNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTNhYWU5OTAzYmFmZjNjYTlhM2M2ZDE4YWQ3ZmRmY2Q5NjBkMDhkZDMzNTIzMzU0ZWY3NGU2MTAwZjljNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aN1rSSq1VFUfgN6ZTAZs5X6a32mShRrljnsoaFzqYWg)
> 
> 这次网卡重命名成功，但是问题旧。usb作为wan(dhcp)到wifi只有10mbps。

设备树里面的ext prefix里把eth删除了吗

**Comment by CMCCAdmin** [comment]
> > > > > rtl8156网卡使用的是免驱cdc ncm驱动还是rtl的私有驱动？
> > > > 
> > > > 
> > > > r8152的厂商驱动
> > > 
> > > 
> > > 需要对r8152驱动进行改动，把下面这个补丁命名为`101-rename-ifname-to-usbX.patch`，放在`/home/hanwckf/immortalwrt-mt798x/package/kernel/r8152/patches/`后重新编译试一下。注意要选择vendor版本的驱动。
> > > ```diff
> > > --- a/r8152.c
> > > +++ b/r8152.c
> > > @@ -20599,6 +20599,8 @@ static int rtl8152_probe(struct usb_inte
> > >  		tp->sg_use = true;
> > >  #endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(5,2,3) */
> > >  
> > > +	strcpy(netdev->name, "usb%d");
> > > +
> > >  #if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,29)
> > >  	netdev->open = rtl8152_open;
> > >  	netdev->stop = rtl8152_close;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![{22126-x-794383226571}](https://private-user-images.githubusercontent.com/27666983/301486529-2431e408-df62-49d6-a793-85dc3ba3d608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIzNjMsIm5iZiI6MTcwNjc5MjA2MywicGF0aCI6Ii8yNzY2Njk4My8zMDE0ODY1MjktMjQzMWU0MDgtZGY2Mi00OWQ2LWE3OTMtODVkYzNiYTNkNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTNhYWU5OTAzYmFmZjNjYTlhM2M2ZDE4YWQ3ZmRmY2Q5NjBkMDhkZDMzNTIzMzU0ZWY3NGU2MTAwZjljNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aN1rSSq1VFUfgN6ZTAZs5X6a32mShRrljnsoaFzqYWg)
> > 
> > 
> > 这次网卡重命名成功，但是问题旧。usb作为wan(dhcp)到wifi只有10mbps。
> 
> 设备树里面的ext prefix里把eth删除了吗

是的

**Comment by hanwckf** [comment]
@CMCCAdmin 试下这个固件

[rax3000m.7z.zip](https://github.com/hanwckf/immortalwrt-mt798x/files/14128142/rax3000m.7z.zip)

**Comment by Aes64X** [comment]
> @CMCCAdmin 试下这个固件
> 
> [rax3000m.7z.zip](https://github.com/hanwckf/immortalwrt-mt798x/files/14128142/rax3000m.7z.zip)

似乎是不能这么用吗？无论是直接写死eth2还是提供的固件，都无法跑出很高的速度。
我使用RTL的千兆USB网卡，PC有线连接进行测试，最高也就能达到60M带宽，实际速率6M/s左右。

**Comment by CMCCAdmin** [comment]
> @CMCCAdmin 试下这个固件
> 
> [rax3000m.7z.zip](https://github.com/hanwckf/immortalwrt-mt798x/files/14128142/rax3000m.7z.zip)

下行速率还是老样子，10m左右。不过我发现上行流量速率竟然是正常的，既从wifi到usb的流量能够跑到千兆。

**Comment by Aes64X** [comment]
> > @CMCCAdmin 试下这个固件
> > [rax3000m.7z.zip](https://github.com/hanwckf/immortalwrt-mt798x/files/14128142/rax3000m.7z.zip)
> 
> 下行速率还是老样子，10m左右。不过我发现上行流量速率竟然是正常的，既从wifi到usb的流量能够跑到千兆。

忘了测上行😂

**Comment by hanwckf** [comment]
> > @CMCCAdmin 试下这个固件
> > [rax3000m.7z.zip](https://github.com/hanwckf/immortalwrt-mt798x/files/14128142/rax3000m.7z.zip)
> 
> 下行速率还是老样子，10m左右。不过我发现上行流量速率竟然是正常的，既从wifi到usb的流量能够跑到千兆。

r8152驱动需要更多改动，我收了个rtl8156b网卡后续再调一下

**Comment by CCMeta** [comment]
> > 关于问题2，可以尝试把下面这个补丁命名为`753-usbnet-force-ifname-usbX.patch`，放进`target/linux/mediatek/patches-5.4/`目录后重新编译试一下。
> > ```diff
> > Index: linux-5.4.255/drivers/net/usb/usbnet.c
> > ===================================================================
> > --- linux-5.4.255.orig/drivers/net/usb/usbnet.c
> > +++ linux-5.4.255/drivers/net/usb/usbnet.c
> > @@ -1735,10 +1735,12 @@ usbnet_probe (struct usb_interface *udev
> >  		// heuristic:  "usb%d" for links we know are two-host,
> >  		// else "eth%d" when there's reasonable doubt.  userspace
> >  		// can rename the link if it knows better.
> > +		/*
> >  		if ((dev->driver_info->flags & FLAG_ETHER) != 0 &&
> >  		    ((dev->driver_info->flags & FLAG_POINTTOPOINT) == 0 ||
> >  		     (net->dev_addr [0] & 0x02) == 0))
> >  			strcpy (net->name, "eth%d");
> > +		*/
> >  		/* WLAN devices should always be named "wlan%d" */
> >  		if ((dev->driver_info->flags & FLAG_WLAN) != 0)
> >  			strcpy(net->name, "wlan%d");
> > ```
> 
> 我尝试make clean并重新编译，刷入后还是识别成eth2


题主 我刚收了个8156转USB3.0，
用这个patch加上cdc ncm驱动编译，成功把8156识别成了USB0。
LAN是800M/650M
WLAN是1050M/480M

我以为会有可能跑出大出1G的速度，看来是我天真了。
感觉上就是无论怎么弄，USB的速度都不可能突破1500M 😢

**Comment by CMCCAdmin** [comment]
> > > 关于问题2，可以尝试把下面这个补丁命名为`753-usbnet-force-ifname-usbX.patch`，放进`target/linux/mediatek/patches-5.4/`目录后重新编译试一下。
> > > ```diff
> > > Index: linux-5.4.255/drivers/net/usb/usbnet.c
> > > ===================================================================
> > > --- linux-5.4.255.orig/drivers/net/usb/usbnet.c
> > > +++ linux-5.4.255/drivers/net/usb/usbnet.c
> > > @@ -1735,10 +1735,12 @@ usbnet_probe (struct usb_interface *udev
> > >  		// heuristic:  "usb%d" for links we know are two-host,
> > >  		// else "eth%d" when there's reasonable doubt.  userspace
> > >  		// can rename the link if it knows better.
> > > +		/*
> > >  		if ((dev->driver_info->flags & FLAG_ETHER) != 0 &&
> > >  		    ((dev->driver_info->flags & FLAG_POINTTOPOINT) == 0 ||
> > >  		     (net->dev_addr [0] & 0x02) == 0))
> > >  			strcpy (net->name, "eth%d");
> > > +		*/
> > >  		/* WLAN devices should always be named "wlan%d" */
> > >  		if ((dev->driver_info->flags & FLAG_WLAN) != 0)
> > >  			strcpy(net->name, "wlan%d");
> > > ```
> > 
> > 
> > 我尝试make clean并重新编译，刷入后还是识别成eth2
> 
> 题主 我刚收了个8156转USB3.0， 用这个patch加上cdc ncm驱动编译，成功把8156识别成了USB0。 LAN是800M/650M WLAN是1050M/480M
> 
> 我以为会有可能跑出大出1G的速度，看来是我天真了。 感觉上就是无论怎么弄，USB的速度都不可能突破1500M 😢

USB驱动是有开销的，速度跑到1.5 1.6g时cpu已经快满了。
