### ISSUE TITLE
RAX3000M迅雷有线下载CPU占用问题

### ISSUE THREAD

**Issue by eggydutch** [hanwckf/immortalwrt-mt798x#248]
### Describe the bug

RAX3000M使用迅雷有线下载时，通过htop观察到CPU占用(不定时)可达数十%，而我只是上限150Mbps左右的小水管。
网络加速>MediaTek HNAT 功能已开启同时openclash也开启白名单IP上网模式，而用作迅雷有线下载的PC不走openclash，这会是bug吗？还是说mt7981的闭源mtk驱动跟恩山帖子提及的mt7622同类问题情况一样？即mtk hwnat无法对迅雷部分的udp流量作硬件加速分载？

恩山相关贴文：
https://www.right.com.cn/forum/thread-8226373-2-1.html

### ImmortalWrt version

r20565-d3ab1bf5e6

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
你的设置问题，把clash完全关了再测试。我测过，7981跑千m迅雷有线并没有什么cpu占用

**Comment by hxlls** [comment]
没有问题，你自己检查下你其他设置
![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/43886952/8e91e069-74fc-4889-80a7-19756ab5a791)

**Comment by hanwckf** [comment]
openclash插件问题，与固件没有关系，可能走了tun模式，此时路由器所有加速功能都无效
