### ISSUE TITLE
大家的UPNP功能是否正常

### ISSUE THREAD

**Issue by wyap-echo** [hanwckf/immortalwrt-mt798x#25]
![image](https://user-images.githubusercontent.com/58325947/208011407-733a9e8d-5864-4e9c-afba-e878328e29f9.png)
之前在用360 V6的OP时只要Xbox一连接UPNP就会出现xbox的转发端口，换到T7当主路由时Xbox插网线连接，UPNP就不显示转发的端口，但是在Xbox里面看UPNP是正常的，这难道只是不显示吗？还是说UPNP工作不正常

**Comment by lalasou** [comment]
能用就正常  
pcdn 跑着呢 正常
