### ISSUE TITLE
如何开启MT3000的"外部网络设备（如USB3.0 5G模块、USB-RNDIS/ECM网卡等）到有线和无线的双向hwnat PPE加速"?

### ISSUE THREAD

**Issue by libiunc** [hanwckf/immortalwrt-mt798x#250]
如题.

**Comment by libiunc** [comment]
根据https://github.com/hanwckf/immortalwrt-mt798x/commit/302556c1ac0b05fa9a79f18be4b4e8a7a09eba6d 这个更改,我在mt3000的dts中发现对usb和wwan的加速已经存在,请问我该如何启用呢
https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7981-gl-mt3000.dts#L208-L214

~~还是说已经启用了~~,准备入手一个RM500q,与mt3000组合成为~~手摇~~CPE使用

**Comment by eggydutch** [comment]
> 根据[302556c](https://github.com/hanwckf/immortalwrt-mt798x/commit/302556c1ac0b05fa9a79f18be4b4e8a7a09eba6d) 这个更改,我在mt3000的dts中发现对usb和wwan的加速已经存在,请问我该如何启用呢
> 
> https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7981-gl-mt3000.dts#L208-L214
> 
> ~还是说已经启用了~,准备入手一个RM500q,与mt3000组合成为~手摇~CPE使用

新年好！恭喜发财！请教一下你提到的RM500q是用的高通芯片吗？还是其他国产的芯片？因为看到Lean大那边更推荐高通的芯片，谢谢！

**Comment by hanwckf** [comment]
> 根据[302556c](https://github.com/hanwckf/immortalwrt-mt798x/commit/302556c1ac0b05fa9a79f18be4b4e8a7a09eba6d) 这个更改,我在mt3000的dts中发现对usb和wwan的加速已经存在,请问我该如何启用呢
> 
> https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7981-gl-mt3000.dts#L208-L214
> 
> ~还是说已经启用了~,准备入手一个RM500q,与mt3000组合成为~手摇~CPE使用

已经启用了，目前WAN/LAN口是翻转的，也就是2.5G作为LAN口

**Comment by Canary233** [comment]
> > 根据[302556c](https://github.com/hanwckf/immortalwrt-mt798x/commit/302556c1ac0b05fa9a79f18be4b4e8a7a09eba6d) 这个更改,我在mt3000的dts中发现对usb和wwan的加速已经存在,请问我该如何启用呢
> > https://github.com/hanwckf/immortalwrt-mt798x/blob/24546fd666040cc3e6d894e42bbeffc87d487ee7/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7981-gl-mt3000.dts#L208-L214
> > 
> > ~还是说已经启用了~,准备入手一个RM500q,与mt3000组合成为~手摇~CPE使用
> 
> 已经启用了，目前WAN/LAN口是翻转的，也就是2.5G作为LAN口

请问FM350之类的RNDIS拨号的5G模块可以正常启用HNAT吗？
