### ISSUE TITLE
`iptables-mod-fullconenat` 已默认安装 但未生效

### ISSUE THREAD

**Issue by Pil0tXia** [hanwckf/immortalwrt-mt798x#252]
### Describe the bug

`iptables-mod-fullconenat` opkg 包是 ImmortalWrt 默认安装的包之一，其功能是为 OpenWRT 提供 Full Cone NAT 实现。

### 环境

上游的 NAT 类型为 Full Cone NAT，upnp 开启，使用水星 D196G 路由器时，lan 中设备的 NAT 类型是 Full Cone NAT。

### 问题

在 ImmortalWrt 中，即使在 turboacc（网络 - 网络加速）中选中了`xt_FULLCONENAT`，lan 中设备的 NAT 类型仍是对称型 NAT。

![image](https://github.com/immortalwrt/immortalwrt/assets/41445332/37eb3fad-550c-44a2-8863-d7338461c6e7)

![image](https://github.com/immortalwrt/immortalwrt/assets/41445332/2fc58ba5-8f2a-43eb-b8cf-09cdb849ea48)

“防火墙”页面中也没有看到开启完全锥型 NAT 的选项（原版 OpenWRT 的防火墙页面没有此选项，使用 fullconenat 补丁后会多出此选项）：

![](https://iyzm.net/wp-content/uploads/2020/11/openwrt-213.png)

>图片来自 https://iyzm.net/openwrt/3313.html

### 解决方案

希望 ImmortalWrt 可以支持 Full Cone NAT！

### 相关资料

- [OpenWrt 上实现 NAT1 (Full cone NAT) 的方法，无需 DMZ/UPnP](https://www.right.com.cn/forum/thread-319827-1-1.html)
- [xt_FULLCONENAT -- Implementing RFC 3489 full cone SNAT in OpenWrt](https://forum.openwrt.org/t/xt-fullconenat-implementing-rfc-3489-full-cone-snat-in-openwrt/14816)
- [FS#1738 - Please include Full Cone NAT package · Issue #7021 · openwrt/openwrt](https://github.com/openwrt/openwrt/issues/7021)

### ImmortalWrt version

r0-e1b4487

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

Xiaomi Mi Router AX3000T

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by iamyangyiok** [comment]
我的没问题，FULLCONE是正常的。检查你层级关系。

**Comment by Pil0tXia** [comment]
>检查你层级关系。

光猫是桥接模式，无 NAT 相关设置；小米 AX3000T(immortalwrt) 负责拨号。将小米 AX3000T 切换为水星 D196G（原厂系统，无 Full Cone NAT 相关设置）后，BitComet 的 NAT 检测工具给出的 NAT 类型为全锥型 NAT。将 PC 直连光猫，也是可以得到全锥型 NAT 的。

turboacc 中对 NAT 的设置，应该是用于开启/关闭 NAT 连接的硬件加速吧？而路由本身是否允许 NAT1，可能需要在防火墙中设置？

我只在 turboacc 中见到了 Full Cone NAT 相关的设置，防火墙中没有见到。请问是防火墙页面缺少设置吗？

**Comment by lgs2007m** [comment]
我是光猫桥接，路由器拨号，移动大内网有ipv6公网，网络加速设置和你的一样，upnp开启，BitComet检查NAT类型和[NatTypeTester 8.0.2](https://github.com/HMBSbige/NatTypeTester)显示全锥形NAT。
<img width="378" alt="447eaa581c354ad15b04cb36368b6d86" src="https://github.com/hanwckf/immortalwrt-mt798x/assets/22903593/21910b8f-eb13-4738-aea4-daef7f063b30">
<img width="375" alt="086ff7004a04fc22ed9b90f067600d2c" src="https://github.com/hanwckf/immortalwrt-mt798x/assets/22903593/d18b4526-6b9c-4589-bcdd-a8eb75728f92">

**Comment by chute8427** [comment]
检查win防火墙规则是否添加，关闭防火墙再试

**Comment by Pil0tXia** [comment]
>检查win防火墙规则是否添加，关闭防火墙再试

BitComet自动添加了的，关掉防火墙也还是nat4😂

**Comment by padavanonly** [comment]
自己设置问题，别人都是正常的

**Comment by Pil0tXia** [comment]
昨晚再次排查，确认是上游移动从某一天起将给到的NAT1更改为了NAT4。
