### ISSUE TITLE
GL-MT3000设备USB硬件加速异常

### ISSUE THREAD

**Issue by fevenor** [hanwckf/immortalwrt-mt798x#254]
### Describe the bug

使用 QMI 模式通过 USB2.0 连接 RM500Q-GL 进行5G上网，从 `929cd0f9d2e016fb6856628746145a08e399ab35` 更新至 `24546fd666040cc3e6d894e42bbeffc87d487ee7` 后，可以获取5G的ipv4及ipv6，尝试ping互联网地址正常，但TCP无法通讯。关闭硬件加速或回退至 `929cd0f9d2e016fb6856628746145a08e399ab35` 恢复正常。

### ImmortalWrt version

已回退未记录

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

GL.iNet GL-MT3000

### Image kind

Self-built image

### Steps to reproduce

1. 编译 `24546fd`
2. 刷入设备
3. 配置网络使用`QMI`协议及`/dev/cdc-wdm0`设备上网
4. 等待ip获取完成
5. 使用`ping`命令验证网络连通性
6. 使用`telnet`命令验证TCP连通性

### Actual behaviour

ICMP通讯正常
TCP无法通讯

### Expected behaviour

ICMP通讯正常
TCP通讯正常

### Diffconfig

```text
未手工修改版本控制的任何文件
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
用移远的驱动，别用内核自带的就行，比如这个
https://github.com/coolsnowwolf/lede/tree/master/package/wwan

**Comment by fevenor** [comment]
> 用移远的驱动，别用内核自带的就行，比如这个 https://github.com/coolsnowwolf/lede/tree/master/package/wwan

一开始搞的时候，移远官方手册就建议不要用内核驱动，用他们家的，但是他们的驱动ipv6有着各种奇奇怪怪的问题，调试了一下输出的一些AT指令在手册里也查不到。
家庭宽带ipv4是内网，想要建立vpn又依赖ipv6，所以最终用回内核驱动了。

**Comment by padavanonly** [comment]
> > 用移远的驱动，别用内核自带的就行，比如这个 https://github.com/coolsnowwolf/lede/tree/master/package/wwan
> 
> 一开始搞的时候，移远官方手册就建议不要用内核驱动，用他们家的，但是他们的驱动ipv6有着各种奇奇怪怪的问题，调试了一下输出的一些AT指令在手册里也查不到。 家庭宽带ipv4是内网，想要建立vpn又依赖ipv6，所以最终用回内核驱动了。

那无解，内核的驱动不兼容硬件加速，只有移远自己的驱动才兼容
