### ISSUE TITLE
编译mtk无线失败

### ISSUE THREAD

**Issue by gilgamesh1124** [hanwckf/immortalwrt-mt798x#26]
麻烦各位大佬看下可能的原因，目前编译的是360T7，108M版本固件，选择了mtk ap相关驱动进行编译，-j1报错信息如下，麻烦大佬指正，感谢。

> make[4]: Entering directory '/home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.225'
scripts/Makefile.build:42: /home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/conninfra/Makefile: No such file or directory
make[5]: *** No rule to make target '/home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/conninfra/Makefile'.  Stop.
make[4]: *** [Makefile:1739: /home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/conninfra] Error 2
make[4]: Leaving directory '/home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.225'
make[3]: *** [Makefile:124: /home/james/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/conninfra/.built] Error 2
make[3]: Leaving directory '/home/james/immortalwrt-mt798x/package/mtk/drivers/conninfra'
time: package/mtk/drivers/conninfra/compile#0.36#0.11#0.49
    ERROR: package/mtk/drivers/conninfra failed to build.
make[2]: *** [package/Makefile:116: package/mtk/drivers/conninfra/compile] Error 1
make[2]: Leaving directory '/home/james/immortalwrt-mt798x'
make[1]: *** [package/Makefile:110: /home/james/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/james/immortalwrt-mt798x'
make: *** [/home/james/immortalwrt-mt798x/include/toplevel.mk:230：world] 错误 2

**Comment by lalasou** [comment]
一般默认配置文件就是精简版了 
在这个基础上添加插件就行了
6000和t7差不多 每次都正常编译



--来自小白

**Comment by ningsibuqu** [comment]
> 一般默认配置文件就是精简版了 在这个基础上添加插件就行了 6000和t7差不多 每次都正常编译
> 
> --来自小白

大佬，咋云编译 t7 精简版呀，有现成的不。谢谢。

**Comment by lalasou** [comment]
@hkk666   他这里有

**Comment by ningsibuqu** [comment]
> @hkk666 他这里有

mini 就是精简版默认配置？还需要改啥不。

**Comment by lalasou** [comment]
> > @hkk666 他这里有
> 
> 
> 
> mini 就是精简版默认配置？还需要改啥不。

h大源码defconfig/ax3000  那个就是t7 精简版配置文件照着改

**Comment by acnixuil** [comment]
同编译失败，如果不勾选这些是不是没有wifi驱动

**Comment by hanwckf** [comment]
编译脚本的问题，建议手工编译成功后再制作编译脚本
