### ISSUE TITLE
配置hwnat的网络加速页面不见了

### ISSUE THREAD

**Issue by Unwillingx** [hanwckf/immortalwrt-mt798x#264]
### Describe the bug

用于配置hwnat的 网络-网络加速 页面不见了，删除浏览器缓存、更换浏览器和更换设备均没有解决，固件编译是按照H大博客里的教程进行，插件添加了alist、mosdns、ssrplus、openclash和watchcat，相同的配置在2月22日编译出来还有 网络加速 的页面。
![Snipaste_2024-03-08_19-14-15](https://github.com/hanwckf/immortalwrt-mt798x/assets/125542178/6f6ec46a-8f2a-4c2d-b6d1-84f5e961c69b)

### ImmortalWrt version

openwrt-21.02

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

GL.iNet MT3000

### Image kind

Self-built image

### Expected behaviour

能恢复正常使用

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by nanchuci** [comment]
你选luci-app-turboacc-mtk没得嘛？

**Comment by Unwillingx** [comment]
> 你选luci-app-turboacc-mtk没得嘛？

再三检查了配置文件，确认选择了

**Comment by Unwillingx** [comment]
> https://192.168.1.1/cgi-bin/luci/admin/network/turboacc 直接浏览器打路径打开 显示的是什么呢
打不开，显示内容如下：
![Snipaste_2024-03-12_14-41-59](https://github.com/hanwckf/immortalwrt-mt798x/assets/125542178/077d8895-799c-47a7-b2c0-f32ddaa66317)

**Comment by Unwillingx** [comment]
> https://192.168.1.1/cgi-bin/luci/admin/network/turboacc 直接浏览器打路径打开 显示的是什么呢

报错404，显示内容如下：
![Snipaste_2024-03-12_14-41-59](https://github.com/hanwckf/immortalwrt-mt798x/assets/125542178/a23d9b77-cba4-430f-b231-a3089b854613)

**Comment by padavanonly** [comment]
除了配置文件没选上truboacc，没有其他原因了。或者本地仓库turboacc-mtk被你删了。

**Comment by Unwillingx** [comment]
> 除了配置文件没选上truboacc，没有其他原因了。或者本地仓库turboacc-mtk被你删了。
> 
> 编译的.config发出来

感谢大佬回复，编译的.config文件如下：
https://github.com/Unwillingx/OpenWrt-Build/blob/main/Configs/imm_798x.config

**Comment by Unwillingx** [comment]
> > > 除了配置文件没选上truboacc，没有其他原因了。或者本地仓库turboacc-mtk被你删了。
> > > 编译的.config发出来
> > 
> > 
> > 感谢大佬回复，编译的.config文件如下： https://github.com/Unwillingx/OpenWrt-Build/blob/main/Configs/imm_798x.config
> 
> 云编译的？.config没问题，那应该是 就是你云编译的问题了。源码是正常的，2月22日后的更新没有涉及到硬件加速插件。

对的，是云编译，谢谢大佬排查，我本地编译试试看

**Comment by Unwillingx** [comment]
经测试，本地编译出的固件正常有网络加速页面，应该是云编译出了啥问题，感谢大家的建议！

**Comment by Unwillingx** [comment]
经测试，本地编译出的固件正常有网络加速页面，应该是云编译出了啥问题，感谢大家的建议！
