### ISSUE TITLE
间歇性无法上网，打不开网页

### ISSUE THREAD

**Issue by W4J1e** [hanwckf/immortalwrt-mt798x#265]
### Describe the bug

重庆移动，光猫桥接，360T7拨号上网。正常使用大半年，后来家里设备全部掉线，路由器接口 wan 是连接状态。重启光猫依旧无法上网，重启路由器恢复。

后来遇到的问题是间歇性无法打开网页，在刷 ImmortalWrt 21.02 以前(固件为卖家刷好的 Immortalwrt 18.x) ，表现为频繁出现网页解析慢甚至失败，edge 浏览器显示 `dns_probe_finished_nxdomain`，但是一般不会持续太久，可能十几秒钟恢复正常。

在手机端表现为 APP 时不时帖子图片的预览图不显示，点击时而转圈，时而正常显示。QQ消息一般不受影响。

刷了 ImmortalWrt 21.02 以后(继续本项目云编译的多个固件），时而断网，表现为：浏览器打开网页，edge提示：`DNS_PROBE_STARTED`，电脑有线网卡详情显示 ipv4 和 ipv6 均无法连接到互联网。小爱音响响应“网络好像遇到问题，请检查一下网络吧”。通过手机端米家（5G网络）可以正常开关灯。

### ImmortalWrt version

r20568-3fa9687ca7

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360 T7

### Image kind

Self-built image

### Steps to reproduce

没有特别的步骤，时不时出现。
但在重启 WAN 接口时，经常提示“未知错误（user request）”

### Actual behaviour

刷了 ImmortalWrt 21.02 以后，时而断网，表现为：浏览器打开网页，edge提示：`DNS_PROBE_STARTED`，电脑有线网卡详情显示 ipv4 和 ipv6 均无法连接到互联网。小爱音响响应“网络好像遇到问题，请检查一下网络吧”。通过手机端米家（5G网络）可以正常开关灯。

### Expected behaviour

预期是网络使用正常。

### Additional info

[log.txt](https://github.com/hanwckf/immortalwrt-mt798x/files/14546244/log.txt)
上面的附件是我今天凌晨零点后再次不保留此前数据刷写有一个基于本项目编译的固件后，到我19点多再次遇到问题重启之前。
再次拨号成功后，也有间歇性打不开个别网页（百度知道），同时可以打开淘宝，过十几秒后，百度知道正常打开，nslookup 也恢复正常。
![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/74824162/6b395b63-53c0-44d4-9350-30e2a2b83cbd)
自己尝试过不限于：卸载 mwan3，关闭所有富强插件，自定义DNS，安装使用 `SmartDNS`，重置，不保留数据升级更高版本固件，尝试基于本项目云编译的各种固件，光猫直连正常。

### Diffconfig

```text
root@LonelyGod:~# ./scripts/diffconfig.sh
-ash: ./scripts/diffconfig.sh: not found
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
既然刷固件前就不正常，为什么不考虑下是移动宽带问题？

update:你在论坛说了之前半年都正常，有天宽带断网后才不正常。这种一看就是宽带本身问题，这种关键信息干嘛省略？

**Comment by lbg2008** [comment]
可能是爬墙软件的锅，试试关闭后有无改善。

**Comment by W4J1e** [comment]
@padavanonly 很抱歉，刷21.02固件之前也是 immortal 18.x，是卖家刷好的。问题出现后我各种尝试无效后发现 H 大的项目有更新版本，所以刷了21.02。排除宽带问题是因为直连光猫是正常的。

省略突然断网这个信息是我写 issue 时搞丢了，很抱歉。突然断网后，我回家首先重启的光猫，还是无法上网，看路由器接口还是正常连接状态，所以重启了路由器才恢复上网。

**Comment by W4J1e** [comment]
> 可能是爬墙软件的锅，试试关闭后有无改善。

试过这方面，包括刷了高版本固件后没有开启和设置这类软件。

**Comment by W4J1e** [comment]
我提这个 issue 的目的是想请大佬们指点，因为我能力有限，我所了解过的方法都试过了，没有起效。
在提 issue 的时候只能选择 bug 标签，这不代表我认为是项目和固件有问题，请见谅。
此 issue 暂时中止，后续问题得以解决我再更新。

**Comment by nantayo** [comment]
我帮我的朋友搞过一台 RAX3000M 用作主路由，没有发生过无故断网，提供一些我的使用信息，看能不能对你有帮助：
1. 固件是我帮忙编译的，同样 GitHub 云编译生成，比较精简，插件只有 mtwifi-cfg、passwall、turboacc-mtk、zerotier
<details> <summary>完整.config</summary>

# 机型
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_mt7981=y
CONFIG_TARGET_mediatek_mt7981_DEVICE_cmcc_rax3000m=y
CONFIG_TARGET_ROOTFS_INITRAMFS=n

# 优化设置
CONFIG_AFALG_FALLBACK=n
CONFIG_AFALG_UPDATE_CTR_IV=y
CONFIG_BUSYBOX_CONFIG_BLKID=y
CONFIG_BUSYBOX_CONFIG_FEATURE_BLKID_TYPE=y
CONFIG_BUSYBOX_CONFIG_VOLUMEID=y
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_CONNINFRA_AUTO_UP=y
CONFIG_CONNINFRA_EMI_SUPPORT=y
CONFIG_DEVEL=y
CONFIG_first_card_name="MT7981"
CONFIG_first_card=y
CONFIG_GDB=n
CONFIG_INCLUDE_CONFIG=y
CONFIG_JSON_OVERVIEW_IMAGE_INFO=y
CONFIG_KERNEL_BLK_DEV_THROTTLING=n
CONFIG_KERNEL_CFS_BANDWIDTH=n
CONFIG_KERNEL_CGROUP_DEVICE=y
CONFIG_KERNEL_CGROUP_FREEZER=y
CONFIG_KERNEL_DEVMEM=y
CONFIG_KERNEL_KEYS=n
CONFIG_KERNEL_MEMCG_SWAP=n
CONFIG_KERNEL_NET_CLS_CGROUP=y
CONFIG_MTK_ACK_CTS_TIMEOUT_SUPPORT=y
CONFIG_MTK_AIR_MONITOR=y
CONFIG_MTK_AMPDU_CONF_SUPPORT=y
CONFIG_MTK_ANTENNA_CONTROL_SUPPORT=y
CONFIG_MTK_APCLI_SUPPORT=y
CONFIG_MTK_ATE_SUPPORT=y
CONFIG_MTK_BACKGROUND_SCAN_SUPPORT=y
CONFIG_MTK_BAND_STEERING=n
CONFIG_MTK_CAL_BIN_FILE_SUPPORT=y
CONFIG_MTK_CFG_SUPPORT_FALCON_MURU=y
CONFIG_MTK_CFG_SUPPORT_FALCON_PP=y
CONFIG_MTK_CFG_SUPPORT_FALCON_SR=y
CONFIG_MTK_CFG_SUPPORT_FALCON_TXCMD_DBG=y
CONFIG_MTK_CHIP_MT7981=y
CONFIG_MTK_CON_WPS_SUPPORT=y
CONFIG_MTK_CONNINFRA_APSOC_MT7981=y
CONFIG_MTK_CONNINFRA_APSOC=y
CONFIG_MTK_DBDC_MODE=y
CONFIG_MTK_DEFAULT_5G_PROFILE=n
CONFIG_MTK_DOT11_HE_AX=y
CONFIG_MTK_DOT11_N_SUPPORT=y
CONFIG_MTK_DOT11_VHT_AC=y
CONFIG_MTK_DOT11K_RRM_SUPPORT=y
CONFIG_MTK_DOT11R_FT_SUPPORT=y
CONFIG_MTK_DOT11W_PMF_SUPPORT=y
CONFIG_MTK_FAST_NAT_SUPPORT=y
CONFIG_MTK_FIRST_IF_EEPROM_FLASH=y
CONFIG_MTK_FIRST_IF_IPAILNA=y
CONFIG_MTK_FIRST_IF_MT7981=y
CONFIG_MTK_G_BAND_256QAM_SUPPORT=y
CONFIG_MTK_GREENAP_SUPPORT=y
CONFIG_MTK_HDR_TRANS_RX_SUPPORT=y
CONFIG_MTK_HDR_TRANS_TX_SUPPORT=y
CONFIG_MTK_ICAP_SUPPORT=y
CONFIG_MTK_IGMP_SNOOP_SUPPORT=y
CONFIG_MTK_INTERWORKING=y
CONFIG_MTK_MAC_REPEATER_SUPPORT=n
CONFIG_MTK_MAP_R2_VER_SUPPORT=y
CONFIG_MTK_MAP_R3_VER_SUPPORT=y
CONFIG_MTK_MAP_SUPPORT=y
CONFIG_MTK_MBSS_DTIM_SUPPORT=y
CONFIG_MTK_MBSS_SUPPORT=y
CONFIG_MTK_MCAST_RATE_SPECIFIC=y
CONFIG_MTK_MEMORY_SHRINK_AGGRESS=y
CONFIG_MTK_MEMORY_SHRINK=y
CONFIG_MTK_MGMT_TXPWR_CTRL=y
CONFIG_MTK_MLME_MULTI_QUEUE_SUPPORT=y
CONFIG_MTK_MT_AP_SUPPORT=m
CONFIG_MTK_MT_DFS_SUPPORT=y
CONFIG_MTK_MT_MAC=y
CONFIG_MTK_MT_WIFI_PATH="mt_wifi"
CONFIG_MTK_MT_WIFI=m
CONFIG_MTK_MT7981_NEW_FW=y
CONFIG_MTK_MU_RA_SUPPORT=y
CONFIG_MTK_MULTI_PROFILE_SUPPORT=n
CONFIG_MTK_MUMIMO_SUPPORT=y
CONFIG_MTK_OFFCHANNEL_SCAN_FEATURE=y
CONFIG_MTK_OWE_SUPPORT=y
CONFIG_MTK_PCIE_ASPM_DYM_CTRL_SUPPORT=n
CONFIG_MTK_PRE_CAL_TRX_SET1_SUPPORT=n
CONFIG_MTK_PRE_CAL_TRX_SET2_SUPPORT=n
CONFIG_MTK_QOS_R1_SUPPORT=y
CONFIG_MTK_RA_PHY_RATE_SUPPORT=y
CONFIG_MTK_RED_SUPPORT=y
CONFIG_MTK_RLM_CAL_CACHE_SUPPORT=n
CONFIG_MTK_RT_FIRST_CARD_EEPROM="flash"
CONFIG_MTK_RT_FIRST_IF_RF_OFFSET=0xc0000
CONFIG_MTK_RTMP_FLASH_SUPPORT=y
CONFIG_MTK_SCS_FW_OFFLOAD=y
CONFIG_MTK_SECOND_IF_NONE=y
CONFIG_MTK_SMART_CARRIER_SENSE_SUPPORT=y
CONFIG_MTK_SNIFFER_RADIOTAP_SUPPORT=n
CONFIG_MTK_SPECTRUM_SUPPORT=y
CONFIG_MTK_SUPPORT_OPENWRT=y
CONFIG_MTK_THIRD_IF_NONE=y
CONFIG_MTK_TPC_SUPPORT=y
CONFIG_MTK_TXBF_SUPPORT=y
CONFIG_MTK_UAPSD=y
CONFIG_MTK_VLAN_SUPPORT=y
CONFIG_MTK_VOW_SUPPORT=y
CONFIG_MTK_WARP_V2=y
CONFIG_MTK_WDS_SUPPORT=y
CONFIG_MTK_WHNAT_SUPPORT=m
CONFIG_MTK_WIFI_BASIC_FUNC=y
CONFIG_MTK_WIFI_DRIVER=y
CONFIG_MTK_WIFI_EAP_FEATURE=y
CONFIG_MTK_WIFI_FW_BIN_LOAD=y
CONFIG_MTK_WIFI_MODE_AP=m
CONFIG_MTK_WIFI_MT_MAC=y
CONFIG_MTK_WIFI_TWT_SUPPORT=y
CONFIG_MTK_WLAN_HOOK=y
CONFIG_MTK_WLAN_SERVICE=y
CONFIG_MTK_WNM_SUPPORT=y
CONFIG_MTK_WPA3_SUPPORT=y
CONFIG_MTK_WSC_INCLUDED=y
CONFIG_MTK_WSC_V2_SUPPORT=y
CONFIG_OPENSSL_ENGINE_BUILTIN=n
CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=n
CONFIG_OPENSSL_WITH_NPN=y
CONFIG_PKG_CHECK_FORMAT_SECURITY=n
CONFIG_PKG_FORTIFY_SOURCE_1=n
CONFIG_PKG_FORTIFY_SOURCE_2=y
CONFIG_TARGET_PER_DEVICE_ROOTFS=y
CONFIG_TOOLCHAINOPTS=y
CONFIG_WARP_CHIPSET="mt7981"
CONFIG_WARP_DBG_SUPPORT=y
CONFIG_WARP_VERSION=2
CONFIG_WED_HW_RRO_SUPPORT=y
CONFIG_WOLFSSL_HAS_ECC25519=n

# ipv6
CONFIG_PACKAGE_ip6tables-extra=y
CONFIG_PACKAGE_ip6tables-mod-nat=y
CONFIG_PACKAGE_ipv6helper=y

# kmod
CONFIG_PACKAGE_kmod-conninfra=y
CONFIG_PACKAGE_kmod-crypto-acompress=y
CONFIG_PACKAGE_kmod-crypto-ccm=y
CONFIG_PACKAGE_kmod-crypto-cmac=y
CONFIG_PACKAGE_kmod-crypto-crc32c=y
CONFIG_PACKAGE_kmod-crypto-ctr=y
CONFIG_PACKAGE_kmod-crypto-des=y
CONFIG_PACKAGE_kmod-crypto-gcm=y
CONFIG_PACKAGE_kmod-crypto-gf128=y
CONFIG_PACKAGE_kmod-crypto-ghash=y
CONFIG_PACKAGE_kmod-crypto-hmac=y
CONFIG_PACKAGE_kmod-crypto-md4=y
CONFIG_PACKAGE_kmod-crypto-md5=y
CONFIG_PACKAGE_kmod-crypto-rng=y
CONFIG_PACKAGE_kmod-crypto-seqiv=y
CONFIG_PACKAGE_kmod-crypto-sha256=y
CONFIG_PACKAGE_kmod-crypto-sha512=y
CONFIG_PACKAGE_kmod-inet-diag=y
CONFIG_PACKAGE_kmod-ipt-offload=y
CONFIG_PACKAGE_kmod-ipt-raw6=y
CONFIG_PACKAGE_kmod-lib-crc32c=y
CONFIG_PACKAGE_kmod-lib-lzo=y
CONFIG_PACKAGE_kmod-mediatek_hnat=y
CONFIG_PACKAGE_kmod-mt_wifi=y
CONFIG_PACKAGE_kmod-nf-flow=y
CONFIG_PACKAGE_kmod-nls-base=y
CONFIG_PACKAGE_kmod-nls-cp437=y
CONFIG_PACKAGE_kmod-nls-iso8859-1=y
CONFIG_PACKAGE_kmod-nls-utf8=y
CONFIG_PACKAGE_kmod-usb-net-rndis=n
CONFIG_PACKAGE_kmod-warp=y

# luci
CONFIG_PACKAGE_luci-app-filetransfer=n
CONFIG_PACKAGE_luci-app-mtwifi-cfg=y
CONFIG_PACKAGE_luci-app-passwall=y
CONFIG_PACKAGE_luci-app-samba4=n
CONFIG_PACKAGE_luci-app-turboacc-mtk=y
CONFIG_PACKAGE_luci-app-usb-printer=n
CONFIG_PACKAGE_luci-app-zerotier=y

# packages
CONFIG_PACKAGE_ip-bridge=y
CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_iptables-mod-filter=y
CONFIG_PACKAGE_iptables-mod-hashlimit=y
CONFIG_PACKAGE_iptables-mod-iface=y
CONFIG_PACKAGE_iptables-mod-ipmark=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-mod-iprange=y
CONFIG_PACKAGE_iptables-mod-ipv4options=y
CONFIG_PACKAGE_iptables-mod-nat-extra=y
CONFIG_PACKAGE_iptables-mod-proto=y
CONFIG_PACKAGE_iptables-mod-tee=y
CONFIG_PACKAGE_iptables-mod-tproxy=y
CONFIG_PACKAGE_iptables-mod-u32=y
CONFIG_PACKAGE_libblkid=y
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcbor=y
CONFIG_PACKAGE_libevdev=y
CONFIG_PACKAGE_libfido2=y
CONFIG_PACKAGE_libipset=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnl=y
CONFIG_PACKAGE_libnl-core=y
CONFIG_PACKAGE_libnl-genl=y
CONFIG_PACKAGE_libnl-nf=y
CONFIG_PACKAGE_libnl-route=y
CONFIG_PACKAGE_libopenssl-afalg_sync=y
CONFIG_PACKAGE_libopenssl-devcrypto=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libudev-zero=y
CONFIG_PACKAGE_libuuid=y
CONFIG_PACKAGE_mii_mgr=y
CONFIG_PACKAGE_regs=y
CONFIG_PACKAGE_swconfig=y
CONFIG_PACKAGE_switch=y
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_PACKAGE_wireless-tools=y
</details>

2. 朋友家用的是移动宽带，光猫桥接、路由器拨号。据我观察，移动宽带通常每7天会强制要求重拨，并且偶尔路由器反应不过来，需要手动重拨甚至重启才能恢复正常，所以我设置了每周一凌晨重启，避开强制重拨的周期。

3. 对于上网相关的插件，我认为简单家用没必要套娃太多，国内交给运营商DNS一般很少出问题了，海外单独设置一下科学插件就行，dnsmasq设置更是基本不用改什么，越多越容易有问题。或许你把你现在用的固件拿出来大家看看怎么回事？

**Comment by W4J1e** [comment]
@nantayo 感谢大佬的关注。
恰好在昨天晚上，通过各位大佬们的帮助，我抓包 LAN 口发现了问题所在，简单来说就是抓包发现，局域网设备的域名解析请求经过了局域网中的群晖（作为 DNS 服务器），又在设置群晖 DNS 的时候不小心输错了一位导致，是我自己傻逼，跟硬件、固件和插件没有关系。
详情见：https://hin.cool/posts/opdns2synology.html

**Comment by nantayo** [comment]
> @nantayo 感谢大佬的关注。 恰好在昨天晚上，通过各位大佬们的帮助，我抓包 LAN 口发现了问题所在，简单来说就是抓包发现，局域网设备的域名解析请求经过了局域网中的群晖（作为 DNS 服务器），又在设置群晖 DNS 的时候不小心输错了一位导致，是我自己傻逼，跟硬件、固件和插件没有关系。 详情见：https://hin.cool/posts/opdns2synology.html

🧐问题解决了就好，虽然根源确实有点无厘头……群晖居然也可以作为 DHCP Server 啊，感觉意义真是不大，莫非是默认开启这个功能的吗

**Comment by W4J1e** [comment]
> > @nantayo 感谢大佬的关注。 恰好在昨天晚上，通过各位大佬们的帮助，我抓包 LAN 口发现了问题所在，简单来说就是抓包发现，局域网设备的域名解析请求经过了局域网中的群晖（作为 DNS 服务器），又在设置群晖 DNS 的时候不小心输错了一位导致，是我自己傻逼，跟硬件、固件和插件没有关系。 详情见：https://hin.cool/posts/opdns2synology.html
> 
> 🧐问题解决了就好，虽然根源确实有点无厘头……群晖居然也可以作为 DHCP Server 啊，感觉意义真是不大，莫非是默认开启这个功能的吗

不是特别清楚，去翻了一下群晖的文档，发现用群晖做 DNS 服务器的是 DNS server 而不是 DHCP server。但是群晖里手动设置的 DNS 确实是输错了一位，在抓包的数据中看到群晖比较频繁的解析请求，不知道是不是这样影响了网关。或许也只是误打误撞吧。
