### ISSUE TITLE
关于CMCC Rax3000-emmc的“接口:ra0|接口类型: AP|SSID: 错误:dat文件中未指定SSID值|信道: 0无线已禁用或未关联”

### ISSUE THREAD

**Issue by oceange8** [hanwckf/immortalwrt-mt798x#267]
### Describe the bug

最近一个月，我几次重新编译，启动后发现WiFi的功能失效。显示

接口:ra0|接口类型: AP|SSID: 错误:dat文件中未指定SSID值|信道: 0无线已禁用或未关联

接口:ra0处于未启用状态，同时接口:rax0不可见。启用后重启，又恢复如上。

不知道问题出在哪了？

谢谢
![84807733e11bd6804dd8a004de59658](https://github.com/hanwckf/immortalwrt-mt798x/assets/77355776/0ec2a65b-0e7d-49f3-98f3-b7f4a6d66a00)

### ImmortalWrt version

r0-3fa9687

### ImmortalWrt target/subtarget

r0-3fa9687

### Device

CMCC Rax3000-emmc

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by oceange8** [comment]
我发现了引起问题的所在了。
默认配置是这样的
#CONFIG_PACKAGE_luci-app-mtk is not set
CONFIG_PACKAGE_luci-app-mtwifi-cfg=y
因为不明白各个插件的作用，我就勾选了 luci-app-mtk，同时自动取消了luci-app-mtwifi-cfg
从而引起上面的问题。恢复默认后就正常了。

另外，请教下luci-app-mtk的作用是什么？
暂时不关闭本issue

**Comment by iamsxm** [comment]
[该文章里面有介绍](https://cmi.hanwckf.top/p/immortalwrt-mt798x/)
luci-app-mtk：源自mtk-sdk提供的配置工具，需要配合wifi-profile脚本使用，可调整无线驱动的几乎所有参数，配置界面较为简陋
mtwifi-cfg与luci-app-mtk不能在固件里共存，编译时必须选择其中之一，目前最新源码已默认使用mtwifi-cfg作为无线配置工具，如需使用旧版luci-app-mtk，请选择defconfig/luci-app-mtk-deprecated目录里的配置模板文件进行编译

**Comment by oceange8** [comment]
已解决
