### ISSUE TITLE
支持BPI R3吗

### ISSUE THREAD

**Issue by iiio051031448** [hanwckf/immortalwrt-mt798x#27]
BPI R3 和 RedMi AX6000 方案差不多。这个项目能支持吗？

**Comment by AlphaAnother** [comment]
你提供台机器咯 没机器怎么适配

**Comment by cherinyy** [comment]
可以自行尝试合并[相关代码](https://github.com/search?q=repo%3Aimmortalwrt%2Fimmortalwrt+BPI-R3&type=commits)进行编译，欢迎[提交拉取请求](https://github.com/hanwckf/immortalwrt-mt798x/compare)。

**Comment by potatoigit** [comment]
R3 Mini已适配成功，预计新开Repo，然后可以合并回此Repo，相信R3不会有太大变动

**Comment by Kasazaki4090** [comment]
参考楼上大佬的，目前R3（不是mini）差不多了，还差按纽还没弄好，要测试，可以去我Repo自己拉下来编译
