### ISSUE TITLE
请问有办法在编译中删除"交换机"功能么?

### ISSUE THREAD

**Issue by jt8823** [hanwckf/immortalwrt-mt798x#273]
我以前使用的openwrt固件,  一直是在设备-物理接口里面进行指定设置的.
第一次看到交换机功能,刚刚折腾了一下,导致路由器进不去了,还好刷了uboot

在编译过程中,  需要调整哪些选项,   才能恢复为 物理接口那个窗口 进行配置呢?

求指教..
谢过!!!!

**Comment by M48A1** [comment]
强烈建议不要immortalwrt 不要搞这个交换机

都不懂这个交换机怎么设置的， 搜索了一大圈都没有什么文档说明的。

这个交换机功能真的是很烦， 都不知道那个网口是wan口。
