### ISSUE TITLE
大佬求适配 Nokia EA0326GMP

### ISSUE THREAD

**Issue by wenpo1975** [hanwckf/immortalwrt-mt798x#274]
### Describe the bug

add Nokia EA0326GMP support
https://github.com/coolsnowwolf/lede/commit/2a4194fa4b4d5e703bfee519306c2b6f7a811198

### ImmortalWrt version

/

### ImmortalWrt target/subtarget

/

### Device

Nokia EA0326GMP

### Image kind

Official downloaded image

### Steps to reproduce

/

### Actual behaviour

/

### Expected behaviour

/

### Additional info

/

### Diffconfig

```text
/
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by benboguan** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/pull/270#issue-2203864671

**Comment by wujun4code** [comment]
@wenpo1975 https://github.com/easy-programming-guide/NOKIA-EA0326GMP/tree/main 我搞定了。
