### ISSUE TITLE
RAX3000M编译完刷入交换机配置页面不正常

### ISSUE THREAD

**Issue by ctrget** [hanwckf/immortalwrt-mt798x#279]
### Describe the bug

使用自带的配置添加几个插件 编译Uboot刷入后 无法拨号 交换机页面显示不正常 无法配置VLAN 手动复制360 T7的配置后可拨号正常上网 但VLAN无效 页面配置依旧不正常
![111](https://github.com/hanwckf/immortalwrt-mt798x/assets/6408095/84779acf-d5f7-4ffe-89eb-08b9078e3a82)
图为更改配置后RAX3000M的交换机页面 显示依旧不正常 两个接口都已接入 WAN口对应交换机也显示错误
360 T7默认配置添加插件后刷入一切正常 

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT r0-3fa9687

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by AlphaAnother** [comment]
RAX3000M的配置就和T7不一样 T7是7531交换机连着两个GMAC 他的WAN口是从CPU的千兆PHY接出来的 直接接上GMAC2 所以交换机正常状态下是没有WAN口的 你得从接口那里加VLAN

**Comment by ctrget** [comment]
> RAX3000M的配置就和T7不一样 T7是7531交换机连着两个GMAC 他的WAN口是从CPU的千兆PHY接出来的 直接接上GMAC2 所以交换机正常状态下是没有WAN口的 你得从接口那里加VLAN

好的 谢谢菊苣
