### ISSUE TITLE
Redmi_AX6000 mt_wifi 编译出错

### ISSUE THREAD

**Issue by bxyun0** [hanwckf/immortalwrt-mt798x#280]
### Describe the bug

make[3]: Entering directory '/home/acc/immortalwrt-mt798x/package/mtk/drivers/mt_wifi'
rm -f /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built
touch /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built_check
make -C "/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255" KCFLAGS="-fmacro-prefix-map=/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/acc/immortalwrt-mt798x/staging_dir/host/include -I/home/acc/immortalwrt-mt798x/staging_dir/hostpkg/include -I/home/acc/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Feb 25 04:28:13 2024" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/acc/immortalwrt-mt798x/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/acc/immortalwrt-mt798x/staging_dir/host/lib" CONFIG_SHELL="bash" V='' cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/conninfra.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/cryptodev-linux.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/gpio-button-hotplug.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/leds-ws2812b.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/warp.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/xtables-addons.symvers" KERNELRELEASE=5.4.255 M="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap" LINUX_DIR="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986" CONFIG_RT_FIRST_IF_RF_OFFSET=0xc0000 CONFIG_MT_WIFI=m CONFIG_WIFI_BASIC_FUNC=y CONFIG_MT_WIFI_PATH="mt_wifi" CONFIG_FIRST_IF_EEPROM_FLASH=y CONFIG_RT_FIRST_CARD_EEPROM="flash" CONFIG_SECOND_IF_NONE=y CONFIG_WIFI_BASIC_FUNC=y CONFIG_DOT11_N_SUPPORT=y CONFIG_DOT11_VHT_AC=y CONFIG_DOT11_HE_AX=y CONFIG_CFG_SUPPORT_FALCON_MURU=y CONFIG_CFG_SUPPORT_FALCON_TXCMD_DBG=y CONFIG_CFG_SUPPORT_FALCON_SR=y CONFIG_CFG_SUPPORT_FALCON_PP=y CONFIG_WIFI_DRIVER=y CONFIG_G_BAND_256QAM_SUPPORT=y CONFIG_ICAP_SUPPORT=y CONFIG_MT_AP_SUPPORT=m CONFIG_BACKGROUND_SCAN_SUPPORT=y CONFIG_SMART_CARRIER_SENSE_SUPPORT=y CONFIG_SCS_FW_OFFLOAD=y CONFIG_THERMAL_PROTECT_SUPPORT=y CONFIG_MT_DFS_SUPPORT=y CONFIG_HDR_TRANS_TX_SUPPORT=y CONFIG_HDR_TRANS_RX_SUPPORT=y CONFIG_DBDC_MODE=y CONFIG_WSC_INCLUDED=y CONFIG_WSC_V2_SUPPORT=y CONFIG_DOT11W_PMF_SUPPORT=y CONFIG_TXBF_SUPPORT=y CONFIG_IGMP_SNOOP_SUPPORT=y CONFIG_RTMP_FLASH_SUPPORT=y CONFIG_ATE_SUPPORT=y CONFIG_WLAN_SERVICE=y CONFIG_UAPSD=y CONFIG_WIFI_MODE_AP=m CONFIG_WDS_SUPPORT=y CONFIG_MBSS_SUPPORT=y CONFIG_APCLI_SUPPORT=y CONFIG_CON_WPS_SUPPORT=y CONFIG_VOW_SUPPORT=y CONFIG_WIFI_MT_MAC=y CONFIG_MT_MAC=y CONFIG_SUPPORT_OPENWRT=y CONFIG_MUMIMO_SUPPORT=y CONFIG_MU_RA_SUPPORT=y CONFIG_GREENAP_SUPPORT=y CONFIG_TPC_SUPPORT=y CONFIG_CAL_BIN_FILE_SUPPORT=y CONFIG_RED_SUPPORT=y CONFIG_FIRST_IF_IPAILNA=y CONFIG_DOT11K_RRM_SUPPORT=y CONFIG_DOT11R_FT_SUPPORT=y CONFIG_WIFI_EAP_FEATURE=y CONFIG_ANTENNA_CONTROL_SUPPORT=y CONFIG_MGMT_TXPWR_CTRL=y CONFIG_RA_PHY_RATE_SUPPORT=y CONFIG_MBSS_DTIM_SUPPORT=y CONFIG_AMPDU_CONF_SUPPORT=y CONFIG_ACK_CTS_TIMEOUT_SUPPORT=y CONFIG_VLAN_SUPPORT=y CONFIG_MAP_SUPPORT=y CONFIG_MAP_R2_VER_SUPPORT=y CONFIG_MAP_R3_VER_SUPPORT=y CONFIG_QOS_R1_SUPPORT=y CONFIG_WPA3_SUPPORT=y CONFIG_OWE_SUPPORT=y CONFIG_FIRST_IF_MT7986=y CONFIG_THIRD_IF_NONE=y CONFIG_CHIP_MT7986=y CONFIG_SPECTRUM_SUPPORT=y CONFIG_PHY_ICS_SUPPORT=y CONFIG_MCAST_RATE_SPECIFIC=y CONFIG_WLAN_HOOK=y CONFIG_AIR_MONITOR=y CONFIG_OFFCHANNEL_SCAN_FEATURE=y CONFIG_WNM_SUPPORT=y CONFIG_INTERWORKING=y CONFIG_WHNAT_SUPPORT=m CONFIG_FAST_NAT_SUPPORT=y CONFIG_WIFI_TWT_SUPPORT=y CONFIG_WARP_V2=y CONFIG_WIFI_FW_BIN_LOAD=y CONFIG_CONNINFRA_APSOC=y CONFIG_MLME_MULTI_QUEUE_SUPPORT=y CONFIG_WIFI_SKU_TYPE="AX6000" modules
make[4]: Entering directory '/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255'
CC [M] /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.o
In file included from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rtmp_os.h:46,
from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rtmp_comm.h:92,
from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rt_config.h:34,
from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:21:
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c: In function 'ExtEventPhyIcsUnSolicitDataHandler':
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/include/os/rt_linux.h:313:49: error: 'return' with a value, in function returning void [-Werror=return-type]
313 | #define NDIS_STATUS_FAILURE 0x01
| ^~~~
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:1362:10: note: in expansion of macro 'NDIS_STATUS_FAILURE'
1362 | return NDIS_STATUS_FAILURE;
| ^~~~~~~~~~~~~~~~~~~
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:1315:6: note: declared here
1315 | VOID ExtEventPhyIcsUnSolicitDataHandler(
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At top level:
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:2648:13: warning: 'ext_event_get_cr4_tx_statistics' defined but not used [-Wunused-function]
2648 | static VOID ext_event_get_cr4_tx_statistics(RTMP_ADAPTER *pAd, UINT8 *data, UINT32 len)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:262: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.o] Error 1
make[4]: *** [Makefile:1750: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap] Error 2
make[4]: Leaving directory '/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255'
make[3]: *** [Makefile:371: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built] Error 2
make[3]: Leaving directory '/home/acc/immortalwrt-mt798x/package/mtk/drivers/mt_wifi'
time: package/mtk/drivers/mt_wifi/compile#1.95#1.27#3.19
ERROR: package/mtk/drivers/mt_wifi failed to build.
make[2]: *** [package/Makefile:120: package/mtk/drivers/mt_wifi/compile] Error 1
make[2]: Leaving directory '/home/acc/immortalwrt-mt798x'
make[1]: *** [package/Makefile:114: /home/acc/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/acc/immortalwrt-mt798x'
make: *** [/home/acc/immortalwrt-mt798x/include/toplevel.mk:230：world] 错误 2

### ImmortalWrt version

r0-3fa9687

### ImmortalWrt target/subtarget

mediatek/mt7986

### Device

Redmi_AX6000

### Image kind

Official downloaded image

### Steps to reproduce

编译Redmi AX6000到mt_wifi就出错，使用gcc9和gcc10都过不了，编译360t7就没问题，只能使用默认的gcc8

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by benboguan** [comment]
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
信息不完整，你是不是打了什么驱动补丁？没看到其他人有问题！

**Comment by bxyun0** [comment]
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cc1: some warnings being treated as errors 信息不完整，你是不是打了什么驱动补丁？没看到其他人有问题！

重新clone了一份，导入配置make menuconfig后保存，还是会报错，使用的defconfig/luci-app-mtk-deprecated下的配置模板

make[3]: Entering directory '/home/acc/immortalwrt-mt798x/package/mtk/drivers/mt_wifi'
rm -f /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built
touch /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built_check
make  -C "/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255" KCFLAGS="-fmacro-prefix-map=/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/acc/immortalwrt-mt798x/staging_dir/host/include -I/home/acc/immortalwrt-mt798x/staging_dir/hostpkg/include -I/home/acc/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Feb 25 04:28:13 2024" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/acc/immortalwrt-mt798x/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/acc/immortalwrt-mt798x/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/conninfra.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/cryptodev-linux.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/gpio-button-hotplug.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/leds-ws2812b.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/warp.symvers /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/symvers/xtables-addons.symvers" KERNELRELEASE=5.4.255 M="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap" LINUX_DIR="/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986"    CONFIG_RT_FIRST_IF_RF_OFFSET=0xc0000  CONFIG_MT_WIFI=m CONFIG_WIFI_BASIC_FUNC=y CONFIG_MT_WIFI_PATH="mt_wifi"  CONFIG_FIRST_IF_EEPROM_FLASH=y  CONFIG_RT_FIRST_CARD_EEPROM="flash" CONFIG_SECOND_IF_NONE=y      CONFIG_WIFI_BASIC_FUNC=y    CONFIG_DOT11_N_SUPPORT=y CONFIG_DOT11_VHT_AC=y CONFIG_DOT11_HE_AX=y CONFIG_CFG_SUPPORT_FALCON_MURU=y CONFIG_CFG_SUPPORT_FALCON_TXCMD_DBG=y CONFIG_CFG_SUPPORT_FALCON_SR=y CONFIG_CFG_SUPPORT_FALCON_PP=y CONFIG_WIFI_DRIVER=y CONFIG_G_BAND_256QAM_SUPPORT=y  CONFIG_ICAP_SUPPORT=y CONFIG_MT_AP_SUPPORT=m CONFIG_BACKGROUND_SCAN_SUPPORT=y CONFIG_SMART_CARRIER_SENSE_SUPPORT=y CONFIG_SCS_FW_OFFLOAD=y CONFIG_THERMAL_PROTECT_SUPPORT=y CONFIG_MT_DFS_SUPPORT=y CONFIG_HDR_TRANS_TX_SUPPORT=y  CONFIG_HDR_TRANS_RX_SUPPORT=y CONFIG_DBDC_MODE=y    CONFIG_WSC_INCLUDED=y  CONFIG_WSC_V2_SUPPORT=y CONFIG_DOT11W_PMF_SUPPORT=y  CONFIG_TXBF_SUPPORT=y CONFIG_IGMP_SNOOP_SUPPORT=y   CONFIG_RTMP_FLASH_SUPPORT=y CONFIG_ATE_SUPPORT=y CONFIG_WLAN_SERVICE=y CONFIG_UAPSD=y          CONFIG_WIFI_MODE_AP=m     CONFIG_WDS_SUPPORT=y CONFIG_MBSS_SUPPORT=y CONFIG_APCLI_SUPPORT=y       CONFIG_CON_WPS_SUPPORT=y CONFIG_VOW_SUPPORT=y         CONFIG_WIFI_MT_MAC=y   CONFIG_MT_MAC=y  CONFIG_SUPPORT_OPENWRT=y  CONFIG_MUMIMO_SUPPORT=y CONFIG_MU_RA_SUPPORT=y      CONFIG_GREENAP_SUPPORT=y  CONFIG_TPC_SUPPORT=y  CONFIG_CAL_BIN_FILE_SUPPORT=y   CONFIG_RED_SUPPORT=y  CONFIG_FIRST_IF_IPAILNA=y            CONFIG_DOT11K_RRM_SUPPORT=y CONFIG_DOT11R_FT_SUPPORT=y  CONFIG_WIFI_EAP_FEATURE=y  CONFIG_ANTENNA_CONTROL_SUPPORT=y CONFIG_MGMT_TXPWR_CTRL=y    CONFIG_RA_PHY_RATE_SUPPORT=y CONFIG_MBSS_DTIM_SUPPORT=y CONFIG_AMPDU_CONF_SUPPORT=y CONFIG_ACK_CTS_TIMEOUT_SUPPORT=y    CONFIG_VLAN_SUPPORT=y           CONFIG_MAP_SUPPORT=y CONFIG_MAP_R2_VER_SUPPORT=y CONFIG_MAP_R3_VER_SUPPORT=y CONFIG_QOS_R1_SUPPORT=y CONFIG_WPA3_SUPPORT=y CONFIG_OWE_SUPPORT=y        CONFIG_FIRST_IF_MT7986=y      CONFIG_THIRD_IF_NONE=y      CONFIG_CHIP_MT7986=y        CONFIG_SPECTRUM_SUPPORT=y CONFIG_PHY_ICS_SUPPORT=y    CONFIG_MCAST_RATE_SPECIFIC=y CONFIG_WLAN_HOOK=y    CONFIG_AIR_MONITOR=y CONFIG_OFFCHANNEL_SCAN_FEATURE=y CONFIG_WNM_SUPPORT=y CONFIG_INTERWORKING=y       CONFIG_WHNAT_SUPPORT=m CONFIG_FAST_NAT_SUPPORT=y              CONFIG_WIFI_TWT_SUPPORT=y        CONFIG_WARP_V2=y      CONFIG_WIFI_FW_BIN_LOAD=y CONFIG_CONNINFRA_APSOC=y CONFIG_MLME_MULTI_QUEUE_SUPPORT=y CONFIG_WIFI_SKU_TYPE="AX6000"      modules
make[4]: Entering directory '/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255'
  CC [M]  /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.o
In file included from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rtmp_os.h:46,
                 from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rtmp_comm.h:92,
                 from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/include/rt_config.h:34,
                 from /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:21:
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c: In function 'ExtEventPhyIcsUnSolicitDataHandler':
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/include/os/rt_linux.h:313:49: error: 'return' with a value, in function returning void [-Werror=return-type]
  313 | #define NDIS_STATUS_FAILURE                     0x01
      |                                                 ^~~~
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:1362:10: note: in expansion of macro 'NDIS_STATUS_FAILURE'
 1362 |   return NDIS_STATUS_FAILURE;
      |          ^~~~~~~~~~~~~~~~~~~
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:1315:6: note: declared here
 1315 | VOID ExtEventPhyIcsUnSolicitDataHandler(
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At top level:
/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.c:2648:13: warning: 'ext_event_get_cr4_tx_statistics' defined but not used [-Wunused-function]
 2648 | static VOID ext_event_get_cr4_tx_statistics(RTMP_ADAPTER *pAd, UINT8 *data, UINT32 len)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:262: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.o] Error 1
make[4]: *** [Makefile:1750: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap] Error 2
make[4]: Leaving directory '/home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.255'
make[3]: *** [Makefile:371: /home/acc/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built] Error 2
make[3]: Leaving directory '/home/acc/immortalwrt-mt798x/package/mtk/drivers/mt_wifi'
time: package/mtk/drivers/mt_wifi/compile#1.95#1.27#3.19
    ERROR: package/mtk/drivers/mt_wifi failed to build.
make[2]: *** [package/Makefile:120: package/mtk/drivers/mt_wifi/compile] Error 1
make[2]: Leaving directory '/home/acc/immortalwrt-mt798x'
make[1]: *** [package/Makefile:114: /home/acc/immortalwrt-mt798x/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/acc/immortalwrt-mt798x'
make: *** [/home/acc/immortalwrt-mt798x/include/toplevel.mk:230：world] 错误 2

**Comment by bxyun0** [comment]
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cc1: some warnings being treated as errors 信息不完整，你是不是打了什么驱动补丁？没看到其他人有问题！

怪事了，使用默认的gcc8就能过，gcc10就过不了，gcc9也过不了

**Comment by czkwg8** [comment]
你换了编译器当然就有不一样的行为。。。
最简单的就cflags里面把这些警告都忽略就好了

**Comment by bxyun0** [comment]
> 你换了编译器当然就有不一样的行为。。。 最简单的就cflags里面把这些警告都忽略就好了

关键是我编译360T7一直使用的gcc10，没想到换了ax6000就只能用gcc8了，既然是包里面提供的就应该是兼容的啊
