### ISSUE TITLE
移动rax3000m算力版,无法设置无线密码

### ISSUE THREAD

**Issue by nary24** [hanwckf/immortalwrt-mt798x#288]
### Describe the bug

作者您好，我使用移动rax3000m算力版,按照教程自编译选择了个别固件如openclash、openvpn等，其他都是默认，然后在刷入路由器后无法设置无线密码，也不能对无线进入一些常规的操作，请问我这种情况是编译时少选择了什么操作吗，希望帮忙解答一下，谢谢
![反馈问题1](https://github.com/hanwckf/immortalwrt-mt798x/assets/15990601/b2a0e415-26fd-411e-82f2-fca22a05a43b)

### ImmortalWrt version

r20568-3fa9687ca7

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

CMCC RAX3000M eMMC version

### Image kind

Self-built image

### Terms

- [ ] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by nary24** [comment]
翻看其他人之前的提问，尝试清空了浏览器缓存等还是没有显示，所以最终无奈使用了在线编译
https://firmware-selector.immortalwrt.org/

**Comment by carrothu-cn** [comment]
遇到同样的问题，机器是jcg q30 pro，无线安全只能选择无加密。信道没有auto选项。按照h大的提示清空了所有浏览器记录，和更换手机浏览器都未能解决。对比其他人的config没发现可疑的异常，不知是少编译了什么。

**Comment by carrothu-cn** [comment]
感谢h大关注，附上.config供排查。
[mt7981-jcg-q30.config.txt](https://github.com/user-attachments/files/17096855/mt7981-jcg-q30.config.txt)

**Comment by hanwckf** [comment]
> 感谢h大关注，附上.config供排查。 [mt7981-jcg-q30.config.txt](https://github.com/user-attachments/files/17096855/mt7981-jcg-q30.config.txt)

你的.config里没有`CONFIG_PACKAGE_luci-app-mtwifi-cfg`，使用的配置文件不正确，按照编译说明重新使用defconfig重新生成。
另外不要去修改target devices，默认是使用`CONFIG_TARGET_MULTI_PROFILE`编译所有同CPU的路由器固件，你手动只选择JCG-Q30会让其它配置项目变动，导致无线需要的软件包没有编译进去

**Comment by carrothu-cn** [comment]
> > 感谢h大关注，附上.config供排查。 [mt7981-jcg-q30.config.txt](https://github.com/user-attachments/files/17096855/mt7981-jcg-q30.config.txt)
> 
> 你的.config里没有`CONFIG_PACKAGE_luci-app-mtwifi-cfg`，使用的配置文件不正确，按照编译说明重新使用defconfig重新生成。 另外不要去修改target devices，默认是使用`CONFIG_TARGET_MULTI_PROFILE`编译所有同CPU的路由器固件，你手动只选择JCG-Q30会让其它配置项目变动，导致无线需要的软件包没有编译进去

感谢大佬指导，重新检查，发现我的menuconfig里没有luci-app-mtwifi-cfg和luci-app-turboacc-mtk包，清理后重新安装feeds，终于出现了。问题应该就出现在这里，正在重新编译中。感谢！
~
更新，编译后问题解决。看来关键就在于之前没有成功安上luci-app-mtwifi-cfg和luci-app-turboacc-mtk包
