### ISSUE TITLE
luci界面卡顿

### ISSUE THREAD

**Issue by hkk666** [hanwckf/immortalwrt-mt798x#3]
luci界面卡顿，无响应，必须重启才能恢复

**Comment by lalasou** [comment]
> luci界面卡顿，无响应，必须重启才能恢复

就这样一句话 ？

**Comment by hkk666** [comment]
> > luci界面卡顿，无响应，必须重启才能恢复
> 
> 就这样一句话 ？

不是，就是页面用着用着就加载不出来东西了，现在重新编译出来，没这种情况了
