### ISSUE TITLE
upnp功能不生效，软件始终无法添加upnp转发

### ISSUE THREAD

**Issue by sunnyday666** [hanwckf/immortalwrt-mt798x#30]
![QQ图片20221218221141](https://user-images.githubusercontent.com/75302068/208303087-698f2935-86cb-4746-a600-2ba3f5cfa3df.jpg)
比特彗星始终添加失败，甜糖环境检测也过不了，使用xwrt和237大佬的固件倒是可以正常添加
我的网络环境是上级路由器(公网)DMZ给红米6000，固件是我自己编译的，编译进upnp只是在软件包里勾选的，没有动其他的，不知道是否和这个有关。
![QQ图片](https://user-images.githubusercontent.com/75302068/208303211-8b162092-2870-4416-85ce-d09fb32ab269.jpg)
xwrt和237大佬的在此网络环境下可以正常添加端口映射

**Comment by ubitsp** [comment]
同样是红米ax6000也是自己编译的固件  upnp正常工作  看看系统日志有没有报错

**Comment by sunnyday666** [comment]
> 

能看一下你的配置文件吗，我怀疑是我缺少了某些东西。系统进程里upnp是正常运行的，后台也没有任何报错，比特彗星添加就是提示失败，日志上也没任何提示。

**Comment by ubitsp** [comment]
> > 
> 
> 能看一下你的配置文件吗，我怀疑是我缺少了某些东西。系统进程里upnp是正常运行的，后台也没有任何报错，比特彗星添加就是提示失败，日志上也没任何提示。


把.txt去掉,我加了个额外的包luci-app-turboacc-mtk,不过应该和upnp没关系
[.config.txt](https://github.com/hanwckf/immortalwrt-mt798x/files/10299551/default.config.txt)

**Comment by TKTick** [comment]
好像说是UPNP识别到没有公网IP就关闭了。https://github.com/coolsnowwolf/lede/issues/5020

**Comment by 1715173329** [comment]
should be fixed by immortalwrt/packages@4b0a52a62b36e9e9af6ffbf401b640408679975c

**Comment by sunnyday666** [comment]
> should be fixed by [immortalwrt/packages@4b0a52a](https://github.com/immortalwrt/packages/commit/4b0a52a62b36e9e9af6ffbf401b640408679975c)

![图片](https://user-images.githubusercontent.com/75302068/211300028-b2acf044-7905-4479-ba3f-3bffdc070644.png)

![图片](https://user-images.githubusercontent.com/75302068/211299639-33c694f6-19fd-4c2f-ac2b-8eadd77b9db5.png)
我的网络环境是公网主路由DMZ给二级op路由，op路由里有比特彗星添加成功的upnp重定向，但是比特彗星检测过不了，还是黄灯。

**Comment by 1715173329** [comment]
stun.qq.com 改成 stun.miwifi.com 呢

**Comment by sunnyday666** [comment]
> stun.qq.com 改成 stun.miwifi.com 呢

没有效果，同样是有重定向，检测为端口堵塞

**Comment by sunnyday666** [comment]
替换为2.0版本upnp问题得到解决
