### ISSUE TITLE
AN8855

### ISSUE THREAD

**Issue by mrrdmr** [hanwckf/immortalwrt-mt798x#318]
### Describe the bug

Could you add AN8855 switch support for new AX3000T revision please?
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/ac95e9fe1b014ad01c18256465f6519696858fbf

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

AX3000T 

### Device

AX3000T

### Image kind

Self-built image

### Additional info

https://forum.openwrt.org/t/openwrt-support-for-xiaomi-ax3000t/180490/1176

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by warriorpaw** [comment]
@mrrdmr  Hi, have you fixed this AN8855 issue? 
I tried to pick all an8855 changes from mtk-openwrt-feeds to immortalwrt-mt798x, and the compilation passed. But, it failed to bootup after flashing into ax3000t, and ax3000t automatically rolled back to the stock firmware.
