### ISSUE TITLE
红米ax6000 编译后启动不了无线 ,手机可以搜到无线ssid,但是连不上,获取不了ip地址,在网络无线界面看不到网卡

### ISSUE THREAD

**Issue by ubitsp** [hanwckf/immortalwrt-mt798x#32]
Wed Dec 21 16:39:52 2022 kern.info kernel: [   88.028908] warp_msg_wait_rsp(), uni_id:18(cmd_id:5), timeout
Wed Dec 21 16:39:55 2022 kern.info kernel: [   91.100910] warp_msg_wait_rsp(), uni_id:19(cmd_id:5), timeout
Wed Dec 21 16:39:58 2022 kern.info kernel: [   94.172908] warp_msg_wait_rsp(), uni_id:20(cmd_id:5), timeout
Wed Dec 21 16:40:00 2022 kern.err kernel: [   95.708918] WiFi@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:5,ID:45, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:40:01 2022 kern.info kernel: [   97.244908] warp_msg_wait_rsp(), uni_id:21(cmd_id:6), timeout
Wed Dec 21 16:40:04 2022 kern.info kernel: [  100.316907] warp_msg_wait_rsp(), uni_id:22(cmd_id:5), timeout
Wed Dec 21 16:40:08 2022 kern.info kernel: [  103.388910] warp_msg_wait_rsp(), uni_id:23(cmd_id:5), timeout
Wed Dec 21 16:40:08 2022 kern.notice kernel: [  103.394791] WiFi@C08L3,hw_ctrl_flow_v2_connt_act() 215: wdev_idx=1
Wed Dec 21 16:40:10 2022 kern.err kernel: [  105.948917] WiFi@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:5,ID:47, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:40:10 2022 kern.err kernel: [  105.960804] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  105.970924] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  105.981061] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  105.991202] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.001414] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.011527] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.021618] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.031728] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.041826] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.051976] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.062102] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.072199] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.082306] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.092399] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.102568] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.112673] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.122807] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000ee7a0623
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.132914] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001e41136e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.142992] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.153073] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000086840e6
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.163167] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001e41136e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.173245] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000086840e6
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.183350] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001e41136e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.193456] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000e92f1dba
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.203539] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000086840e6
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.213676] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000e92f1dba
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.223802] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.233922] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 000000001053144e
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.244006] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 0000000002914034
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.254104] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000992584a9
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.264184] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 0000000098ca3b81
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.274282] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 0000000098ca3b81
Wed Dec 21 16:40:10 2022 kern.err kernel: [  106.284362] WiFi@C14L1,ba_resrc_rec_add() 1395: ba_resrc_rec_add Freeing previous Debug BA Rec 00000000992584a9
Wed Dec 21 16:40:10 2022 kern.warn kernel: [  106.294554] WiFi@C01L2,wifi_sys_disconn_act() 1002:  wdev_idx=1
Wed Dec 21 16:40:11 2022 kern.info kernel: [  106.460899] warp_msg_wait_rsp(), uni_id:24(cmd_id:6), timeout
Wed Dec 21 16:40:14 2022 kern.info kernel: [  109.532910] warp_msg_wait_rsp(), uni_id:25(cmd_id:5), timeout
Wed Dec 21 16:40:17 2022 kern.info kernel: [  112.604907] warp_msg_wait_rsp(), uni_id:26(cmd_id:5), timeout
Wed Dec 21 16:40:20 2022 kern.info kernel: [  115.676907] warp_msg_wait_rsp(), uni_id:27(cmd_id:5), timeout
Wed Dec 21 16:40:21 2022 kern.err kernel: [  116.700949] WiFi@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:5,ID:46, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:40:21 2022 kern.warn kernel: [  116.712828] WiFi@C13L2,MacTableDeleteEntry() 1793: Del Sta:62:81:43:b7:85:cd
Wed Dec 21 16:40:21 2022 kern.notice kernel: [  116.720143] WiFi@C08L3,ap_peer_deauth_action() 429: AUTH - receive DE-AUTH(seq-2113) from 62:81:43:b7:85:cd, reason=3
Wed Dec 21 16:40:21 2022 kern.err kernel: [  116.730774] WiFi@C08L1,ap_send_mlme_pkt() 803: pkt from non-connected sta, type=0, sub_type=13 to ACQ, drop
Wed Dec 21 16:40:23 2022 kern.info kernel: [  118.748906] warp_msg_wait_rsp(), uni_id:28(cmd_id:5), timeout
Wed Dec 21 16:40:26 2022 kern.info kernel: [  121.820909] warp_msg_wait_rsp(), uni_id:29(cmd_id:6), timeout
Wed Dec 21 16:40:26 2022 user.info : luci: accepted login on / for root from 192.168.1.133
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:40:28 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:40:29 2022 kern.info kernel: [  124.892903] warp_msg_wait_rsp(), uni_id:30(cmd_id:5), timeout
Wed Dec 21 16:40:32 2022 kern.info kernel: [  127.964906] warp_msg_wait_rsp(), uni_id:31(cmd_id:5), timeout
Wed Dec 21 16:40:35 2022 kern.info kernel: [  131.036906] warp_msg_wait_rsp(), uni_id:32(cmd_id:5), timeout
Wed Dec 21 16:40:38 2022 kern.info kernel: [  134.108908] warp_msg_wait_rsp(), uni_id:33(cmd_id:5), timeout
Wed Dec 21 16:40:38 2022 kern.err kernel: [  134.108914] 7986@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:0,ID:16, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:40:41 2022 kern.info kernel: [  137.180908] warp_msg_wait_rsp(), uni_id:34(cmd_id:6), timeout
Wed Dec 21 16:40:44 2022 kern.info kernel: [  140.252906] warp_msg_wait_rsp(), uni_id:35(cmd_id:6), timeout
Wed Dec 21 16:40:47 2022 kern.info kernel: [  143.324904] warp_msg_wait_rsp(), uni_id:36(cmd_id:6), timeout
Wed Dec 21 16:40:51 2022 kern.info kernel: [  146.396911] warp_msg_wait_rsp(), uni_id:37(cmd_id:6), timeout
Wed Dec 21 16:40:54 2022 kern.info kernel: [  149.468907] warp_msg_wait_rsp(), uni_id:38(cmd_id:6), timeout
Wed Dec 21 16:40:57 2022 kern.info kernel: [  152.540952] warp_msg_wait_rsp(), uni_id:39(cmd_id:6), timeout
Wed Dec 21 16:41:00 2022 kern.info kernel: [  155.612907] warp_msg_wait_rsp(), uni_id:40(cmd_id:6), timeout
Wed Dec 21 16:41:03 2022 kern.info kernel: [  158.684906] warp_msg_wait_rsp(), uni_id:41(cmd_id:6), timeout
Wed Dec 21 16:41:06 2022 kern.info kernel: [  161.756905] warp_msg_wait_rsp(), uni_id:42(cmd_id:6), timeout
Wed Dec 21 16:41:09 2022 kern.info kernel: [  164.828905] warp_msg_wait_rsp(), uni_id:43(cmd_id:6), timeout
Wed Dec 21 16:41:12 2022 kern.info kernel: [  167.904908] warp_msg_wait_rsp(), uni_id:44(cmd_id:6), timeout
Wed Dec 21 16:41:15 2022 kern.info kernel: [  170.972906] warp_msg_wait_rsp(), uni_id:45(cmd_id:6), timeout
Wed Dec 21 16:41:18 2022 kern.info kernel: [  174.044906] warp_msg_wait_rsp(), uni_id:46(cmd_id:6), timeout
Wed Dec 21 16:41:21 2022 kern.info kernel: [  177.116906] warp_msg_wait_rsp(), uni_id:47(cmd_id:6), timeout
Wed Dec 21 16:41:24 2022 kern.info kernel: [  180.188908] warp_msg_wait_rsp(), uni_id:48(cmd_id:6), timeout
Wed Dec 21 16:41:27 2022 kern.info kernel: [  183.260909] warp_msg_wait_rsp(), uni_id:49(cmd_id:6), timeout
Wed Dec 21 16:41:30 2022 kern.info kernel: [  186.332907] warp_msg_wait_rsp(), uni_id:50(cmd_id:6), timeout
Wed Dec 21 16:41:34 2022 kern.info kernel: [  189.404908] warp_msg_wait_rsp(), uni_id:51(cmd_id:6), timeout
Wed Dec 21 16:41:37 2022 kern.info kernel: [  192.476933] warp_msg_wait_rsp(), uni_id:52(cmd_id:6), timeout
Wed Dec 21 16:41:40 2022 kern.info kernel: [  195.548906] warp_msg_wait_rsp(), uni_id:53(cmd_id:6), timeout
Wed Dec 21 16:41:43 2022 kern.info kernel: [  198.620906] warp_msg_wait_rsp(), uni_id:54(cmd_id:6), timeout
Wed Dec 21 16:41:46 2022 kern.info kernel: [  201.692906] warp_msg_wait_rsp(), uni_id:55(cmd_id:6), timeout
Wed Dec 21 16:41:49 2022 kern.info kernel: [  204.764905] warp_msg_wait_rsp(), uni_id:56(cmd_id:6), timeout
Wed Dec 21 16:41:52 2022 kern.info kernel: [  207.836961] warp_msg_wait_rsp(), uni_id:57(cmd_id:6), timeout
Wed Dec 21 16:41:55 2022 kern.info kernel: [  210.908901] warp_msg_wait_rsp(), uni_id:58(cmd_id:6), timeout
Wed Dec 21 16:41:58 2022 kern.info kernel: [  213.980906] warp_msg_wait_rsp(), uni_id:59(cmd_id:6), timeout
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:41:59 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:42:01 2022 kern.info kernel: [  217.052907] warp_msg_wait_rsp(), uni_id:60(cmd_id:6), timeout
Wed Dec 21 16:42:04 2022 kern.info kernel: [  220.124905] warp_msg_wait_rsp(), uni_id:61(cmd_id:6), timeout
Wed Dec 21 16:42:07 2022 kern.info kernel: [  223.196904] warp_msg_wait_rsp(), uni_id:62(cmd_id:6), timeout
Wed Dec 21 16:42:09 2022 kern.err kernel: [  224.988925] 7986@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:0,ID:16, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:42:10 2022 kern.info kernel: [  226.268907] warp_msg_wait_rsp(), uni_id:63(cmd_id:6), timeout
Wed Dec 21 16:42:14 2022 kern.info kernel: [  229.340907] warp_msg_wait_rsp(), uni_id:64(cmd_id:6), timeout
Wed Dec 21 16:42:17 2022 kern.info kernel: [  232.417339] warp_msg_wait_rsp(), uni_id:65(cmd_id:6), timeout
Wed Dec 21 16:42:20 2022 kern.info kernel: [  235.484909] warp_msg_wait_rsp(), uni_id:66(cmd_id:6), timeout
Wed Dec 21 16:42:23 2022 kern.info kernel: [  238.556907] warp_msg_wait_rsp(), uni_id:67(cmd_id:6), timeout
Wed Dec 21 16:42:26 2022 kern.info kernel: [  241.628906] warp_msg_wait_rsp(), uni_id:68(cmd_id:6), timeout
Wed Dec 21 16:42:29 2022 kern.info kernel: [  244.700912] warp_msg_wait_rsp(), uni_id:69(cmd_id:6), timeout
Wed Dec 21 16:42:32 2022 kern.info kernel: [  247.776946] warp_msg_wait_rsp(), uni_id:70(cmd_id:6), timeout
Wed Dec 21 16:42:35 2022 kern.info kernel: [  250.844922] warp_msg_wait_rsp(), uni_id:71(cmd_id:6), timeout
Wed Dec 21 16:42:35 2022 kern.notice kernel: [  250.850811] 7986@C08L3,hw_ctrl_flow_v2_disconnt_act() 172: wdev_idx=1
Wed Dec 21 16:42:38 2022 kern.info kernel: [  253.916915] warp_msg_wait_rsp(), uni_id:72(cmd_id:6), timeout
Wed Dec 21 16:42:41 2022 kern.info kernel: [  256.988916] warp_msg_wait_rsp(), uni_id:73(cmd_id:5), timeout
Wed Dec 21 16:42:44 2022 kern.info kernel: [  260.060920] warp_msg_wait_rsp(), uni_id:74(cmd_id:5), timeout
Wed Dec 21 16:42:47 2022 kern.info kernel: [  263.132908] warp_msg_wait_rsp(), uni_id:75(cmd_id:5), timeout
Wed Dec 21 16:42:50 2022 kern.info kernel: [  266.204907] warp_msg_wait_rsp(), uni_id:76(cmd_id:5), timeout
Wed Dec 21 16:42:53 2022 kern.info kernel: [  269.276908] warp_msg_wait_rsp(), uni_id:77(cmd_id:5), timeout
Wed Dec 21 16:42:57 2022 kern.info kernel: [  272.348930] warp_msg_wait_rsp(), uni_id:78(cmd_id:5), timeout
Wed Dec 21 16:43:00 2022 kern.info kernel: [  275.420909] warp_msg_wait_rsp(), uni_id:79(cmd_id:5), timeout
Wed Dec 21 16:43:03 2022 kern.info kernel: [  278.492907] warp_msg_wait_rsp(), uni_id:80(cmd_id:5), timeout
Wed Dec 21 16:43:06 2022 kern.info kernel: [  281.564906] warp_msg_wait_rsp(), uni_id:81(cmd_id:5), timeout
Wed Dec 21 16:43:09 2022 kern.info kernel: [  284.636906] warp_msg_wait_rsp(), uni_id:82(cmd_id:5), timeout
Wed Dec 21 16:43:12 2022 kern.info kernel: [  287.708907] warp_msg_wait_rsp(), uni_id:83(cmd_id:5), timeout
Wed Dec 21 16:43:15 2022 kern.info kernel: [  290.780906] warp_msg_wait_rsp(), uni_id:84(cmd_id:5), timeout
Wed Dec 21 16:43:18 2022 kern.info kernel: [  293.852913] warp_msg_wait_rsp(), uni_id:85(cmd_id:5), timeout
Wed Dec 21 16:43:21 2022 kern.info kernel: [  296.924909] warp_msg_wait_rsp(), uni_id:86(cmd_id:5), timeout
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwconfig: not found
Wed Dec 21 16:43:24 2022 daemon.err uhttpd[3028]: sh: iwpriv: not found
Wed Dec 21 16:43:24 2022 kern.info kernel: [  299.996908] warp_msg_wait_rsp(), uni_id:87(cmd_id:5), timeout
Wed Dec 21 16:43:27 2022 kern.info kernel: [  303.068919] warp_msg_wait_rsp(), uni_id:88(cmd_id:5), timeout
Wed Dec 21 16:43:30 2022 kern.info kernel: [  306.140906] warp_msg_wait_rsp(), uni_id:89(cmd_id:5), timeout
Wed Dec 21 16:43:33 2022 kern.info kernel: [  309.212906] warp_msg_wait_rsp(), uni_id:90(cmd_id:5), timeout
Wed Dec 21 16:43:34 2022 kern.err kernel: [  309.468906] 7986@C02L1,HwCtrlEnqueueCmd() 840: HwCtrl CmdTimeout, TYPE:0,ID:16, adjust_total_wait_time=2500, old_wait_time=2500!!
Wed Dec 21 16:43:36 2022 kern.info kernel: [  312.288921] warp_msg_wait_rsp(), uni_id:91(cmd_id:5), timeout

**Comment by hanwckf** [comment]
你的.config不对，有些软件包没选上

**Comment by ubitsp** [comment]
把wireless-tools和ipv6helper选上可解决
