### ISSUE TITLE
最新主线编译，不保留配置刷入第一次开机2.4g正常，改个ssid+密码后保存 提示已禁用，无法启用。

### ISSUE THREAD

**Issue by ningsibuqu** [hanwckf/immortalwrt-mt798x#324]
### Describe the bug

最新主线编译
https://github.com/hanwckf/immortalwrt-mt798x/commit/aa2041c012d91b86f9a247a8c9425e0441e900d4
不保留配置刷入第一次开机2.4g正常，改个ssid+密码后保存 提示已禁用，无法启用。

5ghz可以正常改ssid+密码

https://github.com/ningsibuqu/360T7/releases/tag/360T7-hanwckf-OpenWrt-mini-2024.09.21

0829 版正常
https://github.com/hanwckf/immortalwrt-mt798x/commit/522de4896a4f0376a7e238bb2d529e8394802520
### ImmortalWrt version

aa2041c012d91b86f9a247a8c9425e0441e900d4

### ImmortalWrt target/subtarget

X

### Device

T7

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
luci更改设置后自动刷新时，无线接口可能还没启动，所以要再等待一会刷新页面后应该可以正常工作。
你的问题我刚才无法复现，可再具体描述下操作流程

**Comment by ningsibuqu** [comment]
> luci更改设置后自动刷新时，无线接口可能还没启动，所以要再等待一会刷新页面后应该可以正常工作。 你的问题我刚才无法复现，可再具体描述下操作流程

我这边也复现不了了，好奇怪。

就是我原来是这个版本
https://github.com/ningsibuqu/360T7/releases/tag/360T7-hanwckf-OpenWrt-mini-2024.08.31

然后不保留配置刷了
https://github.com/ningsibuqu/360T7/releases/tag/360T7-hanwckf-OpenWrt-mini-2024.09.21

2.4g改完ssid+密码2.4g就显示禁用，但也没有启用按钮，这里显示的一直是禁用
![image](https://github.com/user-attachments/assets/50ffa906-1dfc-45d8-b4a4-1658e3cd86ba)

你说无法复现后我再刷了一次 不过这次是保留配置刷入再恢复出厂，也无法复现了

**Comment by hanwckf** [comment]
经过排查，问题定位在ubus-rpcd在调用iwinfo freqlist时偶发性返回错误的结果，导致无线的uci关键配置项被删除，并非mtwifi_cfg的问题。

现在临时解决方案在是luci无线配置里对channel htmode进行非空检查，且不再修改band配置项，应该不会再导致无线配置被误删除

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/0bbf681b2049b74a4e8f4ee71dd5885907da0b80
