### ISSUE TITLE
尝试切换到gcc10编译报错

### ISSUE THREAD

**Issue by mirthlesslk** [hanwckf/immortalwrt-mt798x#332]
### Describe the bug

cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:262: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/mcu/andes_mt.o] Error 1
make[4]: *** [Makefile:1750: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/mt_wifi_ap] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/linux-5.4.284'
make[3]: *** [Makefile:372: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/package/mtk/drivers/mt_wifi'
time: package/mtk/drivers/mt_wifi/compile#2.54#0.96#3.49
    ERROR: package/mtk/drivers/mt_wifi failed to build.
make[2]: *** [package/Makefile:120: package/mtk/drivers/mt_wifi/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:114: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

### ImmortalWrt version

最新代码

### ImmortalWrt target/subtarget

7986

### Device

6086

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by zheshifandian** [comment]
换这个
https://github.com/zheshifandian/immortalwrt-mt798x
支持gcc11-13

**Comment by mirthlesslk** [comment]
> 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13

好厉害的佬，这是融合了主线吧（震惊）

**Comment by zheshifandian** [comment]
> > 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13
> 
> 好厉害的佬，这是融合了主线吧（震惊）

差不多吧

**Comment by benboguan** [comment]
只晓得驱动编译失败了，你把cc1: some warnings being treated as errors前面的日志贴出来看看啊！

**Comment by mirthlesslk** [comment]
[错误.txt](https://github.com/user-attachments/files/17430140/default.txt)
小白献丑了

**Comment by mirthlesslk** [comment]
> 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13

这个昨晚试了，编译可以过，但是luci会炸，好像是新的luci改动不兼容

**Comment by zheshifandian** [comment]
> > 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13
> 
> 这个昨晚试了，编译可以过，但是luci会炸，好像是新的luci改动不兼容

主题别乱加，乱加肯定炸

**Comment by mirthlesslk** [comment]
> > > 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13
> > 
> > 
> > 这个昨晚试了，编译可以过，但是luci会炸，好像是新的luci改动不兼容
> 
> 主题别乱加，乱加肯定炸

没加，就用默认的boost那个

**Comment by Eternalklk** [comment]
> > > 换这个 https://github.com/zheshifandian/immortalwrt-mt798x 支持gcc11-13
> > 
> > 
> > 这个昨晚试了，编译可以过，但是luci会炸，好像是新的luci改动不兼容
> 
> 主题别乱加，乱加肯定炸

好了，GGC11是正常的，12编译不过，13编译能过，刷进去会炸LUCI，以上（感谢分享

**Comment by zheshifandian** [comment]
我没有，我不会，别瞎说
