### ISSUE TITLE
增加 AX3000T v2支持（AN8855交换机）

### ISSUE THREAD

**Issue by WXR-SEU** [hanwckf/immortalwrt-mt798x#335]
### Describe the bug

8月后的AX3000T（出厂版本1.0.84）均使用AN8855 Switch，如果不含驱动会导致刷机后LAN和WAN均无法工作。
[](https://openwrt.org/inbox/toh/xiaomi/ax3000t)

### ImmortalWrt version

ImmortalWrt_2024.10.25

### ImmortalWrt target/subtarget

AX3000T

### Device

小米 AX3000T

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by zjuahhy** [comment]
hanwckf已经自费买一台在适配了，mtk提供了驱动

**Comment by hanwckf** [comment]
固件的话问题不大，openwrt论坛已经有老外用git01的源码适配成功了，现在正在移植uboot驱动，估计过段时间就能全部搞完

**Comment by sandsly2023** [comment]
> 固件的话问题不大，openwrt论坛已经有老外用git01的源码适配成功了，现在正在移植uboot驱动，估计过段时间就能全部搞完

8月后购买的AX3000T是否支持大佬编译的uboot呢？是否已经支持？之前的uboot刷进去了，但是没有办法刷入现在的固件，只能刷入过度固件，无法升级更新固件，不知道跟uboot是否有关系？

**Comment by hanwckf** [comment]
已经适配好an8855的uboot，过段时间再适配固件

**Comment by hanwckf** [comment]
固件已经适配好了，测试正常
