### ISSUE TITLE
hnat导致通过vlan划分2个lan,第2个lan访问wan的转发速度极慢

### ISSUE THREAD

**Issue by ubitsp** [hanwckf/immortalwrt-mt798x#34]
通过vlan的方式划分了2个lan,再由mwan分流,多wan是通过单线多拨macvlan创建的接口, lan1 to wan1,wan2 速度都正常,但是lan2 to wan1,wan2速度都极慢,上传10mbps,下载只有2mbps,通过
echo 0 > /sys/kernel/debug/hnat/hook_toggle 关闭硬件加速后转发速度恢复正常

**Comment by ubitsp** [comment]
通过vlan的方式划分2个wan,症状和情况一样,vlan划分情况如下图  vlan12是lan2,   vlan13  vlan14是wan1  wan2。lan2  to lan1的速率也正常，只有转发到wan不太正常，猜测和pppoe有关系
![image](https://user-images.githubusercontent.com/24799898/209455698-661a5321-64f1-4094-8c81-a22018fa9e58.png)
![image](https://user-images.githubusercontent.com/24799898/209456021-9d21f72b-cba3-40e3-8756-6c36a973e6ed.png)

**Comment by lalasou** [comment]
> 通过vlan的方式划分2个wan,症状和情况一样,vlan划分情况如下图  vlan12是lan2,   vlan13  vlan14是wan1  wan2
> 
> ![image](https://user-images.githubusercontent.com/24799898/209455698-661a5321-64f1-4094-8c81-a22018fa9e58.png)
> 
> ![image](https://user-images.githubusercontent.com/24799898/209456021-9d21f72b-cba3-40e3-8756-6c36a973e6ed.png)
> 
> 

你好  像我光猫路由器一根线  单线复用回传 光猫lan


![image](https://user-images.githubusercontent.com/7440313/209456059-cdafcde2-8667-4d46-a2fd-c6968303e82d.png)

这样  4031那个 cpu eth1 是untag 还是应该tag啊

**Comment by ubitsp** [comment]
> > 通过vlan的方式划分2个wan,症状和情况一样,vlan划分情况如下图  vlan12是lan2,   vlan13  vlan14是wan1  wan2
> > ![image](https://user-images.githubusercontent.com/24799898/209455698-661a5321-64f1-4094-8c81-a22018fa9e58.png)
> > ![image](https://user-images.githubusercontent.com/24799898/209456021-9d21f72b-cba3-40e3-8756-6c36a973e6ed.png)
> 
> 你好 像我光猫路由器一根线 单线复用回传 光猫lan
> 
> ![image](https://user-images.githubusercontent.com/7440313/209456059-cdafcde2-8667-4d46-a2fd-c6968303e82d.png)
> 
> 这样 4031那个 cpu eth1 是untag 还是应该tag啊

要不要tag  取决于你要不要多建立一个vlan，如果要建立，那就tag，你这种情况应该不用

**Comment by lalasou** [comment]
谢谢👍🙏

**Comment by MeIsReallyBa** [comment]
lan用eth0，别用eth1

**Comment by MeIsReallyBa** [comment]
测试了下，lan2的那个接口你勾上桥接应该就正常了。
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/38341209/222672477-9ff604eb-059f-4a0a-b943-0cdf3f68a0e9.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/38341209/222672561-a20578b8-85f6-4311-8a23-9a64968837c5.png">

**Comment by ubitsp** [comment]
> 接口你勾上桥接应该就正常

我看了下,好像没有 物理设置-桥接接口这个选项

**Comment by ubitsp** [comment]
> 测试了下，lan2的那个接口你勾上桥接应该就正常了。 


非常感谢,按照你的思路测试正常了, 我这个界面有点不一样,需要新建网桥设备

![image](https://user-images.githubusercontent.com/24799898/223461164-95644749-3ffa-4f8d-90e7-d15869d0283f.png)
