### ISSUE TITLE
请问红米 AX6000 的MTK无线驱动选项默认值为空，应怎么选择？

### ISSUE THREAD

**Issue by chika0801** [hanwckf/immortalwrt-mt798x#35]
如图，它们默认全没选（不选，编译出来就没有WIFI驱动）

请问要如何选？

看了下比如（ https://github.com/padavanonly/immortalwrtARM/tree/mt7986 ）的源码，这部分的默认值是给选好了的。

请问大家是如何处理这些选项的？

![1](https://user-images.githubusercontent.com/88967758/209463501-270163f3-905c-4600-9ddf-3204a6193d26.jpg)
![2](https://user-images.githubusercontent.com/88967758/209463503-2766b34e-963f-4687-9900-023525d80ba5.jpg)

**Comment by chika0801** [comment]
请问是不是上面的菜单不用管，选中这里，无线驱动会自己安装上？
![3](https://user-images.githubusercontent.com/88967758/209463687-9279d410-5d47-4a1a-9cff-1ae4e526c6a5.jpg)
我先编译固件测试一下，感谢

**Comment by sdf8057** [comment]
cp -f defconfig/mt7986-ax6000.config .config

**Comment by chika0801** [comment]
> cp -f defconfig/mt7986-ax6000.config .config

感谢你的回答。我明白用官方的defconfig/mt7986-ax6000.config 是肯定能成功的，只是想自己选和改一下插件。

**Comment by AlphaAnother** [comment]
> > cp -f defconfig/mt7986-ax6000.config .config
> 
> 感谢你的回答。我明白用官方的defconfig/mt7986-ax6000.config 是肯定能成功的，只是想自己选和改一下插件。

你复制这个defconfig后一样可以menuconfig···

**Comment by chika0801** [comment]
> > > cp -f defconfig/mt7986-ax6000.config .config
> > 
> > 
> > 感谢你的回答。我明白用官方的defconfig/mt7986-ax6000.config 是肯定能成功的，只是想自己选和改一下插件。
> 
> 你复制这个defconfig后一样可以menuconfig···

谢谢帮助，我试试。学到了。
