### ISSUE TITLE
支持kvr吗？

### ISSUE THREAD

**Issue by muziling** [hanwckf/immortalwrt-mt798x#36]
看了luci配置，有 启用 802.11k，但没看到802.11r， 也没有地方配置信号弱于多少则踢掉终端。

**Comment by w22gb8** [comment]
信号弱于多少则踢掉终端这功能很鸡肋啊，能设置漫游阀值让路由器通知手机自助漫游到其它节点才是正确的方法。

**Comment by muziling** [comment]
> 信号弱于多少则踢掉终端这功能很鸡肋啊，能设置漫游阀值让路由器通知手机自助漫游到其它节点才是正确的方法。

有这功能吗？luci界面没找到。 现在是两个路由刷了，路由不踢，手机也不会自动切换。

**Comment by w22gb8** [comment]
> > 信号弱于多少则踢掉终端这功能很鸡肋啊，能设置漫游阀值让路由器通知手机自助漫游到其它节点才是正确的方法。
> 
> 有这功能吗？luci界面没找到。 现在是两个路由刷了，路由不踢，手机也不会自动切换。

没有，有这功能的路由很少，ac/ap标配，连各大厂商炒作的假mesh都没。

**Comment by wuyu165** [comment]
支持，可以下个winfi看一下

**Comment by muziling** [comment]
> 支持，可以下个winfi看一下

没地方设置信号弱于多少则踢出去，两个路由要怎么实现KV自动漫游？ 设置成一样的SSID？

**Comment by wuyu165** [comment]
相同ssid 加密方式和密码就行了吧，你可以用WiFi魔盒的漫游测试测一下。
