### ISSUE TITLE
iperf3测速只能跑800多，正常吗?

### ISSUE THREAD

**Issue by muziling** [hanwckf/immortalwrt-mt798x#37]
无线设置默认，加密选WPA2PSKWPA3PSK  AES， 笔记本电脑的网卡是intel AX200，无线协商速率是1.2Gbps，  iperf3测速只能跑800多，正常吗？是信道太拥挤了吗? 
使用的命令是 iperf3 -c 192.168.1.1 -b 1g -u -i 1 -P 30 -t 3600

一跑命令就ping会丢包

**Comment by ubitsp** [comment]
无线的损失一般比较大,而且是半双工的,  AC时代我的经验是极速只能做到协商速率的一半多一点,  现在你能跑到800+应该还是MU-MIMO的功劳

**Comment by lalasou** [comment]
新特性要新手机才行   老iPhone XR 我试最高跑700

**Comment by wuyu165** [comment]
请问你ax200 ping路由器会发生丢包现象吗？
我这里只要设置了AES加密，就会丢包，七个包丢三个

**Comment by muziling** [comment]
> 请问你ax200 ping路由器会发生丢包现象吗？ 我这里只要设置了AES加密，就会丢包，七个包丢三个

无线无负载时基本不会丢，跑iperf3时ping 会

**Comment by wuyu165** [comment]
能参照一下你的wifi设置吗，能不能发一下你现在用的固件，我这里ax200如果连接用了360t7，启用了aes加密的5gWiFi，就开始丢包。

**Comment by muziling** [comment]
恩山帖子ID 8263499 ，无线就是默认的，也是aes,  wpa2pskwpa3psk 加密
