### ISSUE TITLE
云编译失败提示warp找不到

### ISSUE THREAD

**Issue by sherlsenlinmu** [hanwckf/immortalwrt-mt798x#38]

**Comment by sherlsenlinmu** [comment]
![Screenshot_20230102-082731](https://user-images.githubusercontent.com/71514869/210188674-a181ef22-cb98-4c40-8a4e-ea7a328f406d.png)

**Comment by ubitsp** [comment]
这个我也遇到过，后来我看了warp的makefile  手动解压dl文件夹里的对应版本的驱动到对应的编译文件夹里可以继续编译

**Comment by sherlsenlinmu** [comment]
感谢！使用源码给的config（cp -f defconfig/mt7986-ax6000.config .config）然后配置（make menuconfig）云编译正常了
