### ISSUE TITLE
你好  不知道可不可以出个releases 固件

### ISSUE THREAD

**Issue by lalasou** [hanwckf/immortalwrt-mt798x#4]
大神固件非常好用👍👍👍
不知道可不可以放在releases  方便下载
或者  有个github  action   
降低门槛

毕竟对于大多数小白来说  编译固件太困难😭

红米ax6000 急需大神固件😀
现在6000没有uboot
希望能适配小米原厂分区 有问题了还可以用小米救砖工具
x-wrt适配分区说明
https://github.com/x-wrt/x-wrt/commit/6ef69f9d4a05811acb584b0e8736d91e97a91b5c

**Comment by hcym** [comment]
试试编译一次

**Comment by hkk666** [comment]
云编译，我仓库弄好了，你可以先下载试试能不能开机😋

**Comment by lalasou** [comment]
> 云编译，我仓库弄好了，你可以先下载试试能不能开机😋


谢谢 

一定开不了机
我是红米6000😂

**Comment by lalasou** [comment]
releases版 基本插件+内核模块

只需要基本插件就行了
精简纯净
😀
🙏🏻 
@hanwckf

**Comment by siren202101** [comment]
> 试试编译一次

360T7每次编译都失败

**Comment by hkk666** [comment]
> > 试试编译一次
> 
> 360T7每次编译都失败
yml文件那里 24行 加上这个
REPO_BRANCH: openwrt-21.02

**Comment by lalasou** [comment]
各位大佬 来个action示范
学习学习
我虽然编译正常 但是这里有个错误
![image](https://user-images.githubusercontent.com/7440313/206189703-63e46248-16da-45ff-bf68-e417b9df5dc1.jpeg)

**Comment by hkk666** [comment]
> 各位大佬 来个action示范 学习学习 我虽然编译正常 但是这里有个错误 ![image](https://user-images.githubusercontent.com/7440313/206189703-63e46248-16da-45ff-bf68-e417b9df5dc1.jpeg)

自己去我仓库看啊

**Comment by lalasou** [comment]
> > 各位大佬 来个action示范 学习学习 我虽然编译正常 但是这里有个错误 ![image](https://user-images.githubusercontent.com/7440313/206189703-63e46248-16da-45ff-bf68-e417b9df5dc1.jpeg)
> 
> 
> 
> 自己去我仓库看啊

好的  我去学习学习

**Comment by lalasou** [comment]
@hkk666 完美 
谢谢  用你的改了改
正常编译了

**Comment by lalasou** [comment]
@hkk666 stock 是不是官方分区固件
但是 怎么刷不进去啊
