### ISSUE TITLE
360t7 5gwifi 设置AES加密后，与ax200网卡冲突

### ISSUE THREAD

**Issue by wuyu165** [hanwckf/immortalwrt-mt798x#40]
### Describe the bug

5gwifi在无论使用wpa3 wpa2还是wpa，设置密码后使用ax200链接，ping丢包，具体七个包丢四个

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT

### ImmortalWrt target/subtarget

ImmortalWrt 21.02-SNAPSHOT

### Device

360T7

### Image kind

Official downloaded image

### Steps to reproduce

打开5g wifi的加密
使用带有ax200/ax210网卡的电脑连接该WiFi
ping路由器地址
七个包丢四个
分别为1ms 1ms 1ms 10+ms 20+ms 30+ms 1ms 1ms 1ms 10+ms 20+ms 30+ms ~~循环

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by wuyu165** [comment]
![20221231_172543](https://user-images.githubusercontent.com/122026439/210785308-037787ce-fab9-4a6d-b1e4-92dbde33d8b2.jpg)

**Comment by wuyu165** [comment]
目前设置为80MHZ，使用149信道解决了这个问题

**Comment by AlphaAnother** [comment]
你是丢包还是跳PING？这图根本没有丢包
根据你说的解决方法 有没有可能纯粹是你用36-64频道有冲突和别人抢工作时间？

**Comment by lalasou** [comment]
今天不知道为什么突然 频率变成20mhz 了  设置的是160啊 
我把2.4g 固定40mhz  5g这边也恢复了...
然后 我把5g固定80mhz了   反正苹果设备多 160没什么用

**Comment by wuyu165** [comment]
ax200更新22.190.0.4驱动后解决问题
