### ISSUE TITLE
可以移植到op 22.03吗？ 我成功移植到op官方21.02了

### ISSUE THREAD

**Issue by muziling** [hanwckf/immortalwrt-mt798x#41]
移植到op官方21.02的方法，见我的编译方法，已测试各个功能都正常：
https://github.com/muziling/openwrt-autocompile/blob/master/.github/workflows/build-360t7.yml

尝试移植到op官方22.03，但是内核版本5.4认不到。  是否可以把无线驱动移植到 5.10内核，这样就可以用新版op了

**Comment by sdf8057** [comment]
meaningless work

**Comment by muziling** [comment]
> meaningless work

对对对，你说的都对，OP那帮老外尽做 meaningless work，还在规划 meaningless  的 23.xx版本

**Comment by britneyjeanspears** [comment]
meaningless work

**Comment by paldier** [comment]
meaningless work

**Comment by hanwckf** [comment]
> 移植到op官方21.02的方法，见我的编译方法，已测试各个功能都正常： https://github.com/muziling/openwrt-autocompile/blob/master/.github/workflows/build-360t7.yml
> 
> 尝试移植到op官方22.03，但是内核版本5.4认不到。 是否可以把无线驱动移植到 5.10内核，这样就可以用新版op了

5.10理论上可以，但是短期内还是跟随mtk官方5.4内核，因为5.4的LTS还能支持到2025年底

**Comment by muziling** [comment]
好的，谢谢H大。
