### ISSUE TITLE
修改dnsmasq参数后web界面主机名显示为bogon

### ISSUE THREAD

**Issue by w22gb8** [hanwckf/immortalwrt-mt798x#42]
### Describe the bug

删除dhcp选项resolvfile或添加选项no-resolv或修改resolvfile为其它文件都会导致web界面和无线管理界面显示主机名为bogon

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT

### ImmortalWrt target/subtarget

ImmortalWrt 21.02-SNAPSHOT

### Device

360 T7

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
这就是预期行为。

**Comment by w22gb8** [comment]
> 这就是预期行为。

哦
