### ISSUE TITLE
如何编译不带无线驱动的固件

### ISSUE THREAD

**Issue by MikeMiao** [hanwckf/immortalwrt-mt798x#43]
由于家里已经有一套成熟的Mesh组网方案，所以买了小米AX6000刷机，只是为了做一个纯粹的有线路由器，替代x86软路由，附带搞个tailscale内网穿透和passwall爬长城，同时使用HWNAT提升网络稳定性，即使是爬长城流量大，CPU高了，也基本不影响非爬墙的终端上网。请问如果不需要无线功能的话，在make menuconfig的时候，去掉哪些选项，可以不编译无线驱动，同时保留有线网的HWNAT加速？

**Comment by muziling** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commits?author=hanwckf  看下更新记录就知道要去掉哪个了

**Comment by hanwckf** [comment]
去掉`MTK Properties`下面的warp、conninfra、mt_wifi、wifi-profile、luci-app-mtk就可以了

**Comment by MikeMiao** [comment]
> 去掉`MTK Properties`下面的warp、conninfra、mt_wifi、wifi-profile、luci-app-mtk就可以了
感谢作者亲自回复
