### ISSUE TITLE
IPv6无法ping通外部地址

### ISSUE THREAD

**Issue by JAM2199562** [hanwckf/immortalwrt-mt798x#48]
ping外部地址时报错如下

![image](https://user-images.githubusercontent.com/10511667/214380806-b280c044-28bc-4068-9bed-3bd33a3266c3.png)
使用的配置如下
![image](https://user-images.githubusercontent.com/10511667/214380860-cd734fc4-1178-4c3f-b180-bcf7f49b8cd2.png)
![image](https://user-images.githubusercontent.com/10511667/214380873-cfb986e3-e217-4906-8d7d-1936dafb3f19.png)
![image](https://user-images.githubusercontent.com/10511667/214380892-c12cee53-f6ec-4875-86f2-db89a2db30ff.png)

上面的配置使用x-wrt源码编译的固件工作正常
执行ip -6 route 并把地址手动对齐对比如下

下图是sirpdboy源码编译的x86和H大源码编译的ax6000的对比
![image](https://user-images.githubusercontent.com/10511667/214385438-b976d693-b297-4df2-b27b-e25158a8c56a.png)

下面是x-wrt源码编译的ax6000和H大源码编译的ax6000的对比
![image](https://user-images.githubusercontent.com/10511667/214385757-10d608a9-c287-451e-9a47-a6208793a5eb.png)

编译的时候没有修改过IPv6相关的设置，v6这块懂得很少。这个问题感觉不一定是bug，但自己实在不懂怎么解决了，求指导。
H大的固件很棒，但是现在用不上lucky很苦恼，谢谢！
请帮忙看看，缺啥信息我再贴

**Comment by JAM2199562** [comment]
补充：使用下面这个移植编译出来的固件IPv6也是可以使用的，没有做特殊配置，设置完拨号连接就可以了
https://github.com/muziling/openwrt-autocompile/blob/master/.github/workflows/build-360t7.yml

**Comment by lgs2007m** [comment]
我使用大佬源码编译的红米AX6000的固件，IPv6没有问题。建议你看下大佬博客的[项目介绍](https://cmi.hanwckf.top/p/immortalwrt-mt798x/)，编译使用推荐config
对于mt7981，推荐使用mt7981-ax3000.config
<code>cp -f defconfig/mt7981-ax3000.config .config</code>
对于mt7986，推荐使用mt7986-ax6000.config
<code>cp -f defconfig/mt7986-ax6000.config .config</code>

**Comment by Bubblingo0** [comment]
同样碰到了这个问题，不过代码reset到https://github.com/hanwckf/immortalwrt-mt798x/commit/c1ff9bd6acbb40d7b4f871d20b3c2d16a7b7ec73 编译的固件没问题。

**Comment by JAM2199562** [comment]
感谢两位的回复，找到原因了，是luci-app-mwan3的问题，把它卸载了都不用重新编译就正常了。
