### ISSUE TITLE
360T7最新源码编译完，路由器无法正常启动

### ISSUE THREAD

**Issue by JCCER** [hanwckf/immortalwrt-mt798x#54]
### Describe the bug

![image](https://user-images.githubusercontent.com/75477419/220812929-d6f9b9c7-b96a-46f2-b8c8-d38411421537.png)
![image](https://user-images.githubusercontent.com/75477419/220812937-40a9a82f-3b49-455c-a04e-e9521a5ca2a8.png)
![image](https://user-images.githubusercontent.com/75477419/220812949-f6a11b8c-9722-4758-88ed-5efa27b5a03a.png)
![image](https://user-images.githubusercontent.com/75477419/220812957-36c79952-4c2c-4f99-90ed-447d589b4bde.png)
![image](https://user-images.githubusercontent.com/75477419/220812967-716e507f-a594-4237-94ae-e30110c9dd8b.png)
make menuconfig后在luci-applications里开启如上的一些插件后，刷入固件路由器无限重启，去掉一些插件后正常启动。是不是有哪些插件有冲突吗。

### ImmortalWrt version

r19998-d91d2a8f42

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360 T7

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by thankeyes** [comment]
只要添加kmod-netem ,编译出来的固件就启动不了

**Comment by yuanlun1983** [comment]
基本就不能加插件，不然启动不了

**Comment by qnnnnez** [comment]
我也遇到类似的问题，增加一些内核模块之后编译出来的固件会 panic。
怀疑是 mt_wifi 驱动问题，这个驱动是以 .o 文件提供的，需要编译参数等完全一致，才能做到编译出来的二进制和他提供的二进制兼容。
#64 作者说有计划提供源代码，到时候应该就可以随意增加内核模块了。

**Comment by yuanlun1983** [comment]
> 我也遇到类似的问题，增加一些内核模块之后编译出来的固件会 panic。 怀疑是 mt_wifi 驱动问题，这个驱动是以 .o 文件提供的，需要编译参数等完全一致，才能做到编译出来的二进制和他提供的二进制兼容。 #64 作者说有计划提供源代码，到时候应该就可以随意增加内核模块了。

  应该就是wifi驱动的问题，试了不加wifi驱动加什么插件加多少插件都能启动，一旦加了wifi驱动就算只是一个裸系统都是红灯不停重启

**Comment by levenwindy** [comment]
@thankeyes @qnnnnez @

> > 我也遇到类似的问题，增加一些内核模块之后编译出来的固件会 panic。 怀疑是 mt_wifi 驱动问题，这个驱动是以 .o 文件提供的，需要编译参数等完全一致，才能做到编译出来的二进制和他提供的二进制兼容。 #64 作者说有计划提供源代码，到时候应该就可以随意增加内核模块了。
> 
> 应该就是wifi驱动的问题，试了不加wifi驱动加什么插件加多少插件都能启动，一旦加了wifi驱动就算只是一个裸系统都是红灯不停重启

是的，我这也是 mt_wifi 启动失败，红灯常亮
CONFIG_PACKAGE_kmod-mt_wifi=m，360T7-108M 才能正常启动

**Comment by yuanlun1983** [comment]
> @thankeyes @qnnnnez @
> 
> > > 我也遇到类似的问题，增加一些内核模块之后编译出来的固件会 panic。 怀疑是 mt_wifi 驱动问题，这个驱动是以 .o 文件提供的，需要编译参数等完全一致，才能做到编译出来的二进制和他提供的二进制兼容。 #64 作者说有计划提供源代码，到时候应该就可以随意增加内核模块了。
> > 
> > 
> > 应该就是wifi驱动的问题，试了不加wifi驱动加什么插件加多少插件都能启动，一旦加了wifi驱动就算只是一个裸系统都是红灯不停重启
> 
> 是的，我这也是 mt_wifi 启动失败，红灯常亮 CONFIG_PACKAGE_kmod-mt_wifi=m，360T7-108M 才能正常启动

是能启动，但没wifi

**Comment by levenwindy** [comment]
@yuanlun1983 
请问现在又替代方法吗？听说有其它开源的 wifi 的？

**Comment by yuanlun1983** [comment]
> @yuanlun1983 请问现在又替代方法吗？听说有其它开源的 wifi 的？
不知道怎么弄，我只是会用现成代码编译而已

**Comment by levenwindy** [comment]
@yuanlun1983 

[【20230501更新】360T7基于H大ImmortalWrt编译固件](https://www.right.com.cn/forum/thread-8270615-1-2.html)
> > 20230501：同步更新源码
> > 20230416：同步更新源码，完善WiFi翻译
> > ......
> > 20230106：
> > 注：1.编译时某些插件选择会导致启动不了，目前还未找到那些插件导致，某些插件可以在线安装（系统--软件包）

恩山不同人几个固件都能正常使用 mt-wifi，难道真的去掉某些【 插件 | 内核 】就行了？

**Comment by hcym** [comment]
无线一直可以，就是5G不能用160，容易断

**Comment by yuanlun1983** [comment]
>

**Comment by yuanlun1983** [comment]
> @yuanlun1983
> 
> [【20230501更新】360T7基于H大ImmortalWrt编译固件](https://www.right.com.cn/forum/thread-8270615-1-2.html)
> 
> > > 20230501：同步更新源码
> > > 20230416：同步更新源码，完善WiFi翻译
> > > ......
> > > 20230106：
> > > 注：1.编译时某些插件选择会导致启动不了，目前还未找到那些插件导致，某些插件可以在线安装（系统--软件包）
> 
> 恩山不同人几个固件都能正常使用 mt-wifi，难道真的去掉某些【 插件 | 内核 】就行了？
或许要怎么设置才能启动，方法人家不说

**Comment by levenwindy** [comment]
@yuanlun1983 @qnnnnez
mt-wifi 成功启动！
 [360T7固件，hanwckf源码编译，WIFI闭源驱动，有线，无线跑满千兆。](https://www.right.com.cn/forum/thread-8263499-1-1.html)  发表于 2022-11-18
直接用他的  [.config](https://url23.ctfile.com/f/40699723-804683009-746226?p=1108 ) 编译成功

去掉 LuCI_Applications 下所有的 luci-app-* ，也能正常启动。

之前是用这个做模板，应该是某个内核冲突了。
```
# 对于mt7981，推荐使用mt7981-ax3000.config
cp -f defconfig/mt7981-ax3000.config .config
```
2023.05.16
**mt-wifi** 与 **kmod-sched-core** 冲突导致不能开机

**Comment by yuanlun1983** [comment]
> @yuanlun1983 @qnnnnez mt-wifi 成功启动！ [360T7固件，hanwckf源码编译，WIFI闭源驱动，有线，无线跑满千兆。](https://www.right.com.cn/forum/thread-8263499-1-1.html) 发表于 2022-11-18 直接用他的 [.config](https://url23.ctfile.com/f/40699723-804683009-746226?p=1108) 编译成功
> 
> 去掉 LuCI_Applications 下所有的 luci-app-* ，也能正常启动。
> 
> 之前是用这个做模板，应该是某个内核冲突了。
> 
> ```
> # 对于mt7981，推荐使用mt7981-ax3000.config
> cp -f defconfig/mt7981-ax3000.config .config
> ```
> 
> 2023.05.16 **mt-wifi** 与 **kmod-sched-core** 冲突导致不能开机
感谢，确实是这个插件导致不能开机，但新问题又来了，没有有线接口了，唉

**Comment by levenwindy** [comment]
@yuanlun1983 
> > 感谢，确实是这个插件导致不能开机，但新问题又来了，没有有线接口了，唉

用了 1 个礼拜，没遇到。immortalwrt 官方支持 [360T7](https://github.com/immortalwrt/immortalwrt/issues/948) 了

**Comment by gdzhujun** [comment]
同样的问题，放弃了

**Comment by yuanlun1983** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hanwckf** [comment]
> 我也遇到类似的问题，增加一些内核模块之后编译出来的固件会 panic。 怀疑是 mt_wifi 驱动问题，这个驱动是以 .o 文件提供的，需要编译参数等完全一致，才能做到编译出来的二进制和他提供的二进制兼容。 #64 作者说有计划提供源代码，到时候应该就可以随意增加内核模块了。

https://github.com/hanwckf/immortalwrt-mt798x/commit/61700ed7eb836f9ba03763b6bbbfd6d0d129a7ed
