### ISSUE TITLE
有人遇到过重新拨号时没设置默认路由吗？

### ISSUE THREAD

**Issue by w22gb8** [hanwckf/immortalwrt-mt798x#57]
### Describe the bug

运行了几个月一直很稳定，今天早上没网，查看pppoe-wan接口正常，能ping通远程地址，就是没设置默认路由，查看日志ppp拨号成功也获取到本地和远程ipv4地址了，和之前区别ipv6地址获取失败，不知为啥没设置默认ipv4默认路由，重新拨号后正常，这问题也没法复现。

### ImmortalWrt version

21.02-SNAPSHOT

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360t7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by w22gb8** [comment]
odhcp6c unbound结束晚于bound。

**Comment by sumn255** [comment]
> odhcp6c unbound结束晚于bound。

@w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6

**Comment by w22gb8** [comment]
> > odhcp6c unbound结束晚于bound。
> 
> @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6

我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。

在文件/lib/netifd/ppp-down末尾添加等待几秒：
```
sleep 3
```
或循环判断wan_6接口是否关闭：
```
while true;do
  if ubus -S list "network.interface.wan_6";then
        #ubus call network.interface.wan_6 down
        sleep 1
  else
        break
  fi
done
```

然后可以重新拨号几次测试是否正常了
```
kill -s HUP `pidof pppd`
```

**Comment by Kudryavka03** [comment]
> > > odhcp6c unbound结束晚于bound。
> > 
> > 
> > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> 
> 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> 
> 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> 
> ```
> sleep 3
> ```
> 
> 或循环判断wan_6接口是否关闭：
> 
> ```
> while true;do
>   if ubus -S list "network.interface.wan_6";then
>         #ubus call network.interface.wan_6 down
>         sleep 1
>   else
>         break
>   fi
> done
> ```
> 
> 然后可以重新拨号几次测试是否正常了
> 
> ```
> kill -s HUP `pidof pppd`
> ```

这个解决方案很好，再也不用走去iface_down那边手动添加了脚本

**Comment by lialosiu** [comment]
我原版openwrt 22.03.5也遇到这个问题，电信0时会踢pppoe下线，概率性丢失默认路由

参考楼上大佬的信息，发现`/lib/netifd/ppp-down`这个脚本是会去调用`/etc/ppp/ip-down.d/*`下的所有脚本的，为了更新系统固件时不用重新修改文件，可以楼上大佬的脚本
```sh
#!/bin/sh
while true; do
  if ubus -S list "network.interface.wan_6"; then
    # ubus call network.interface.wan_6 down
    logger "waiting wan_6 down..."
    sleep 1
  else
    break
  fi
done
```

放到 `/etc/ppp/ip-down.d/check_wan6_down` 下面，并给它`chmod +x`，然后
```sh
echo "/etc/ppp/ip-down.d/check_wan6_down" >> /etc/sysupgrade.conf
```

加入到系统升级时要保存的配置文件和目录的清单中，就可以快乐的折腾了（

**Comment by lalasou** [comment]
> > > odhcp6c unbound结束晚于bound。
> > 
> > 
> > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> 
> 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> 
> 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> 
> ```
> sleep 3
> ```
> 
> 或循环判断wan_6接口是否关闭：
> 
> ```
> while true;do
>   if ubus -S list "network.interface.wan_6";then
>         #ubus call network.interface.wan_6 down
>         sleep 1
>   else
>         break
>   fi
> done
> ```
> 
> 然后可以重新拨号几次测试是否正常了
> 
> ```
> kill -s HUP `pidof pppd`
> ```

我发现  pppoe  ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接
pppoe 重新拨号后   dropbear ipv6 还是无法连接   需要手动重启 dropbear
请教下大佬 这个怎么办，，

**Comment by w22gb8** [comment]
> > > > odhcp6c unbound结束晚于bound。
> > > 
> > > 
> > > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> > 
> > 
> > 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> > 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> > ```
> > sleep 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或循环判断wan_6接口是否关闭：
> > ```
> > while true;do
> >   if ubus -S list "network.interface.wan_6";then
> >         #ubus call network.interface.wan_6 down
> >         sleep 1
> >   else
> >         break
> >   fi
> > done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后可以重新拨号几次测试是否正常了
> > ```
> > kill -s HUP `pidof pppd`
> > ```
> 
> 我发现 pppoe ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接 pppoe 重新拨号后 dropbear ipv6 还是无法连接 需要手动重启 dropbear 请教下大佬 这个怎么办，，

设置dropbear不监听任何接口，和能否获取ipv6没啥关系。

**Comment by lalasou** [comment]
但是每次7天左右 pppoe重新拨号 
ipv6变动后 ipv6 连接ssh 都无法连接


开机后pppoe   ipv4和ipv6获取到了
不重启下dropbear   ssh 也是无法连接

（用的是ipv6地址的形式   管理网页都正常打开了  就是ssh 无法连接 重启dropbear就正常）

> > > > > odhcp6c unbound结束晚于bound。
> 
> > > > 
> 
> > > > 
> 
> > > > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> 
> > > 
> 
> > > 
> 
> > > 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> 
> > > 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> 
> > > ```
> 
> > > sleep 3
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > 或循环判断wan_6接口是否关闭：
> 
> > > ```
> 
> > > while true;do
> 
> > >   if ubus -S list "network.interface.wan_6";then
> 
> > >         #ubus call network.interface.wan_6 down
> 
> > >         sleep 1
> 
> > >   else
> 
> > >         break
> 
> > >   fi
> 
> > > done
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > 然后可以重新拨号几次测试是否正常了
> 
> > > ```
> 
> > > kill -s HUP `pidof pppd`
> 
> > > ```
> 
> > 
> 
> > 我发现 pppoe ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接 pppoe 重新拨号后 dropbear ipv6 还是无法连接 需要手动重启 dropbear 请教下大佬 这个怎么办，，
> 
> 
> 
> 设置dropbear不监听任何接口，和能否获取ipv6没啥关系。
> 
>

**Comment by w22gb8** [comment]
> 但是每次7天左右 pppoe重新拨号 ipv6变动后 ipv6 连接ssh 都无法连接
> 
> 开机后pppoe ipv4和ipv6获取到了 不重启下dropbear ssh 也是无法连接
> 
> （用的是ipv6地址的形式 管理网页都正常打开了 就是ssh 无法连接 重启dropbear就正常）
> 
> > > > > > odhcp6c unbound结束晚于bound。
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> > 
> > 
> > > > 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> > 
> > 
> > > >
> > 
> > 
> > > > sleep 3
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 或循环判断wan_6接口是否关闭：
> > 
> > 
> > > >
> > 
> > 
> > > > while true;do
> > 
> > 
> > > > if ubus -S list "network.interface.wan_6";then
> > 
> > 
> > > > ```
> > > >     #ubus call network.interface.wan_6 down
> > > > ```
> > 
> > 
> > > > ```
> > > >     sleep 1
> > > > ```
> > 
> > 
> > > > else
> > 
> > 
> > > > ```
> > > >     break
> > > > ```
> > 
> > 
> > > > fi
> > 
> > 
> > > > done
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 然后可以重新拨号几次测试是否正常了
> > 
> > 
> > > >
> > 
> > 
> > > > kill -s HUP `pidof pppd`
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > 我发现 pppoe ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接 pppoe 重新拨号后 dropbear ipv6 还是无法连接 需要手动重启 dropbear 请教下大佬 这个怎么办，，
> > 
> > 
> > 设置dropbear不监听任何接口，和能否获取ipv6没啥关系。

出问题时内网ipv4能连接吗？查看dropbear是否监听:::22？

**Comment by lalasou** [comment]
ipv4 正常 内外网ipv6都不能连接 重启dropbear 马上就能连接  

刚好昨晚重新拨号连不上 我看看绑定的是上个ipv6地址 不是绑定::22

如图
![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/7440313/25df1631-36dc-4080-8bba-cf0d25f119f7)


> > 但是每次7天左右 pppoe重新拨号 ipv6变动后 ipv6 连接ssh 都无法连接
> 
> > 
> 
> > 开机后pppoe ipv4和ipv6获取到了 不重启下dropbear ssh 也是无法连接
> 
> > 
> 
> > （用的是ipv6地址的形式 管理网页都正常打开了 就是ssh 无法连接 重启dropbear就正常）
> 
> > 
> 
> > > > > > > odhcp6c unbound结束晚于bound。
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> 
> > > 
> 
> > > 
> 
> > > > > 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > sleep 3
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 或循环判断wan_6接口是否关闭：
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > while true;do
> 
> > > 
> 
> > > 
> 
> > > > > if ubus -S list "network.interface.wan_6";then
> 
> > > 
> 
> > > 
> 
> > > > > ```
> 
> > > > >     #ubus call network.interface.wan_6 down
> 
> > > > > ```
> 
> > > 
> 
> > > 
> 
> > > > > ```
> 
> > > > >     sleep 1
> 
> > > > > ```
> 
> > > 
> 
> > > 
> 
> > > > > else
> 
> > > 
> 
> > > 
> 
> > > > > ```
> 
> > > > >     break
> 
> > > > > ```
> 
> > > 
> 
> > > 
> 
> > > > > fi
> 
> > > 
> 
> > > 
> 
> > > > > done
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 然后可以重新拨号几次测试是否正常了
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > kill -s HUP `pidof pppd`
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我发现 pppoe ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接 pppoe 重新拨号后 dropbear ipv6 还是无法连接 需要手动重启 dropbear 请教下大佬 这个怎么办，，
> 
> > > 
> 
> > > 
> 
> > > 设置dropbear不监听任何接口，和能否获取ipv6没啥关系。
> 
> 
> 
> 出问题时内网ipv4能连接吗？查看dropbear是否监听:::22？

**Comment by w22gb8** [comment]
> ipv4 正常 内外网ipv6都不能连接 重启dropbear 马上就能连接
> 
> 刚好昨晚重新拨号连不上 我看看绑定的是上个ipv6地址 不是绑定::22
> 
> 如图 ![image](https://private-user-images.githubusercontent.com/7440313/303561861-25df1631-36dc-4080-8bba-cf0d25f119f7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NjQ5MDAsIm5iZiI6MTcwNzQ2NDYwMCwicGF0aCI6Ii83NDQwMzEzLzMwMzU2MTg2MS0yNWRmMTYzMS0zNmRjLTQwODAtOGJiYS1jZjBkMjVmMTE5ZjcuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDA3NDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFkMjI0ZTk4NGM5MTAxMTY1MWUxZmE5MGFlOTM2NmNhNzQ5MGE5NDU4NWNjZDRjNjNhMzAxODg1N2I3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cu0LSrNjWGuzW75bw3lINnhAtTsgGiBzAP4p42cpt8M)
> 
> > > 但是每次7天左右 pppoe重新拨号 ipv6变动后 ipv6 连接ssh 都无法连接
> > 
> > 
> > > 
> > 
> > 
> > > 开机后pppoe ipv4和ipv6获取到了 不重启下dropbear ssh 也是无法连接
> > 
> > 
> > > 
> > 
> > 
> > > （用的是ipv6地址的形式 管理网页都正常打开了 就是ssh 无法连接 重启dropbear就正常）
> > 
> > 
> > > 
> > 
> > 
> > > > > > > > odhcp6c unbound结束晚于bound。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > @w22gb8 请教下这个是如何解决的？我这边也是概率性出现这个问题，现象一致，环境是移动家宽，开启v6
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 我这查看原因是偶尔pppoe认证很快，wan_6接口关闭晚于重新拨号建立的pppoe-wan接口。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 在文件/lib/netifd/ppp-down末尾添加等待几秒：
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > sleep 3
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 或循环判断wan_6接口是否关闭：
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > while true;do
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > if ubus -S list "network.interface.wan_6";then
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > ```
> > > > > > #ubus call network.interface.wan_6 down
> > > > > > ```
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > ```
> > > > > > sleep 1
> > > > > > ```
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > else
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > ```
> > > > > > break
> > > > > > ```
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > fi
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > done
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 然后可以重新拨号几次测试是否正常了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > kill -s HUP `pidof pppd`
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 我发现 pppoe ipv6地址获取 比dropbear启动慢 这样 dropbear 就需要手动重启才能连接 pppoe 重新拨号后 dropbear ipv6 还是无法连接 需要手动重启 dropbear 请教下大佬 这个怎么办，，
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 设置dropbear不监听任何接口，和能否获取ipv6没啥关系。
> > 
> > 
> > 出问题时内网ipv4能连接吗？查看dropbear是否监听:::22？

你这dropbear监听特定ipv6接口了，当ipv6改变后要重启dropbear才能连接，设置不监听任何接口:::22不受ip变动影响

**Comment by iamxiaojianzheng** [comment]
即使增加了sleep配置，然后重启了WAN接口。`WAN-6`依然无法获取到IPv6地址，还有救吗？

也是同样的问题，之前一直都可以获取到，在刷机之前使用小米原厂系统（AX3000T）没有遇到过这个问题，IPv6很稳定。

**Comment by w22gb8** [comment]
> 即使增加了sleep配置，然后重启了WAN接口。`WAN-6`依然无法获取到IPv6地址，还有救吗？
> 
> 也是同样的问题，之前一直都可以获取到，在刷机之前使用小米原厂系统（AX3000T）没有遇到过这个问题，IPv6很稳定。

这解决的是偶尔不能获取ipv6的问题，如果是一直不能获取是其它原因。

**Comment by iamxiaojianzheng** [comment]
> > 即使增加了sleep配置，然后重启了WAN接口。`WAN-6`依然无法获取到IPv6地址，还有救吗？
> > 也是同样的问题，之前一直都可以获取到，在刷机之前使用小米原厂系统（AX3000T）没有遇到过这个问题，IPv6很稳定。
> 
> 这解决的是偶尔不能获取ipv6的问题，如果是一直不能获取是其它原因。

感谢回复，已经解决了。
