### ISSUE TITLE
upnp not working 

### ISSUE THREAD

**Issue by Beaverfffan** [hanwckf/immortalwrt-mt798x#59]
### Describe the bug

upnp didn‘t work with glinet-mt3000

SYSTEM LOG
Thu Mar  9 20:21:52 2023 kern.warn kernel: [88853.952809]
Thu Mar  9 20:21:56 2023 kern.notice kernel: [88858.078240] 7981@C15L3,MlmeDeAuthAction() 1404: Send DEAUTH frame with ReasonCode(16) to e6:20:c5:6f:e5:4e
Thu Mar  9 20:21:56 2023 kern.warn kernel: [88858.087998] 7981@C01L2,wifi_sys_disconn_act() 1002:  wdev_idx=1
Thu Mar  9 20:21:56 2023 kern.err kernel: [88858.088072] 7981@C15L1,WpaEAPOLRetryAction() 7735: WpaEAPOLRetryAction::Group rekey timeout from E6:20:C5:6F:E5:4E
Thu Mar  9 20:21:56 2023 kern.notice kernel: [88858.105574] 7981@C08L3,hw_ctrl_flow_v2_disconnt_act() 172: wdev_idx=1
Thu Mar  9 20:21:56 2023 kern.warn kernel: [88858.112841] 7981@C13L2,MacTableDeleteEntry() 1921: Del Sta:e6:20:c5:6f:e5:4e
Thu Mar  9 20:26:05 2023 daemon.notice ttyd[10425]: HTTP / - 192.168.8.247
Thu Mar  9 20:26:05 2023 daemon.notice ttyd[10425]: HTTP /token - 192.168.8.247
Thu Mar  9 20:26:05 2023 daemon.notice ttyd[10425]: WS   /ws - 192.168.8.247, clients: 1
Thu Mar  9 20:26:05 2023 daemon.notice ttyd[10425]: started process, pid: 22818
Thu Mar  9 20:26:10 2023 auth.info login[22818]: root login on 'pts/0'
Thu Mar  9 20:26:18 2023 daemon.notice ttyd[10425]: WS closed from 192.168.8.247, clients: 0
Thu Mar  9 20:26:18 2023 daemon.notice ttyd[10425]: killing process 22818 with signal: 1 (SIGHUP)
Thu Mar  9 20:26:18 2023 daemon.notice ttyd[10425]: process killed with signal 1 (SIGHUP), pid: 22818
Thu Mar  9 20:27:02 2023 daemon.err miniupnpd[23967]: STUN: Performing STUN failed: No such device or address
Thu Mar  9 20:27:02 2023 daemon.err miniupnpd[23967]: Performing STUN failed. EXITING

### ImmortalWrt version

immortalwrt-mt798x

### ImmortalWrt target/subtarget

mt7981

### Device

mt3000

### Image kind

Self-built image

### Steps to reproduce

just open upnp.not seeing any new links

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by lalasou** [comment]
他们都是替换18.06里面的2.x版本正常工作

**Comment by xlighting2017** [comment]
文件 ```/etc/config/upnpd```, 编辑， 找到
```option stun_host```这一行
改成
```option stun_host 	stunserver.stunprotocol.org```


参考这个commit: https://github.com/immortalwrt/packages/commit/94cb78dfea01ef129c50d2f347c807dd395ff882

**Comment by lalasou** [comment]
> 文件 ```/etc/config/upnpd```, 编辑， 找到
> 
> ```option stun_host```这一行
> 
> 改成
> 
> ```option stun_host 	stunserver.stunprotocol.org```
> 
> 
> 
> 
> 
> 参考这个commit: https://github.com/immortalwrt/packages/commit/94cb78dfea01ef129c50d2f347c807dd395ff882

这个试了  貌似没用

**Comment by lalasou** [comment]
编译时候这样就行了
rm -rf feeds/packages/net/miniupnpd && svn co https://github.com/immortalwrt/packages/branches/openwrt-18.06/net/miniupnpd feeds/packages/net/miniupnpd

**Comment by chika0801** [comment]
> rm -rf feeds/packages/net/miniupnpd && svn co https://github.com/immortalwrt/packages/branches/openwrt-18.06/net/miniupnpd feeds/packages/net/miniupnpd

感谢你的分享

**Comment by 0neday** [comment]
mt-3000 wifi is worked ?

**Comment by Beaverfffan** [comment]
miniupnp 18.06 work normal

**Comment by Azbuzz** [comment]
> 编译时候这样就行了 RM -RF feeds/packages/net/miniupnpd && svn co https://github.com/immortalwrt/packages/branches/openwrt-18.06/net/miniupnpd feeds/packages/net/miniupnpd

感谢分享

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/packages/commit/8830f9671173b4dcf8f1ebdb7613f4c86895401e
finally i decide to downgrade it... anyway for your network security you should never use it

**Comment by Beaverfffan** [comment]
thanks
