### ISSUE TITLE
编译报错；

### ISSUE THREAD

**Issue by alterem** [hanwckf/immortalwrt-mt798x#60]
### Describe the bug

编译报错

Error: Invalid format 'mt7981-360-t7-108M'

### ImmortalWrt version

latest

### ImmortalWrt target/subtarget

latest

### Device

360t7

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by xlighting2017** [comment]
action 编的吧， yaml要改

啥时候开始流行  一行报错就提issue了， 那我也一行回复

**Comment by alterem** [comment]
> 
因为我不知道哪里联系你啊，然后我又想解决这个问题

**Comment by alterem** [comment]
> action 编的吧， yaml要改
> 
> 啥时候开始流行 一行报错就提issue了， 那我也一行回复

因为我不知道哪里联系你啊，然后我又想解决这个问题
