### ISSUE TITLE
mt_wifi 能提供编译方法吗

### ISSUE THREAD

**Issue by 0neday** [hanwckf/immortalwrt-mt798x#64]
### Describe the bug

RT

看了 下 https://github.com/hanwckf/immortalwrt-mt798x/tree/openwrt-21.02/package/mtk/drivers 目录下 mt_wifi 的依赖 [conninfra](https://github.com/hanwckf/immortalwrt-mt798x/tree/openwrt-21.02/package/mtk/drivers/conninfra) 提供了源码编译。

而 mt_wifi 和 warp 都是提供 obj 编译。

所以，想请教下 有没有 类似 https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/ 编译 kmod-mediatek_hnat.ko ,编译 mt_wifi.ko 的方法。谢谢！

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

21.02

### Device

gl-inet mt-3000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
@0neday 近期应该会上传驱动代码

**Comment by 0neday** [comment]
> @0neday 近期应该会上传驱动代码

谢谢

**Comment by ningsibuqu** [comment]
> @0neday 近期应该会上传驱动代码

https://github.com/openwrt/mt76/pull/771

对大佬有帮助吗，可以看看

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/61700ed7eb836f9ba03763b6bbbfd6d0d129a7ed

**Comment by ningsibuqu** [comment]
> [61700ed](https://github.com/hanwckf/immortalwrt-mt798x/commit/61700ed7eb836f9ba03763b6bbbfd6d0d129a7ed)

![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/51028975/356345e2-d075-4be7-ba52-5203a096dd6a)
这里怎么显示 2500mb/s 是不是显示错了。
