### ISSUE TITLE
VLAN功能无法正常使用

### ISSUE THREAD

**Issue by InspoOnU** [hanwckf/immortalwrt-mt798x#66]
### Describe the bug

在交换机里设置3个或以上个VLAN（用于分割访客网络），虚拟VLAN的接口访问网络的速度会非常慢，不到3Mbps

### ImmortalWrt version

r11870-09a1f6fb3

### ImmortalWrt target/subtarget

. /etc/openwrt_release && echo $DISTRIB_TARGET

### Device

360 T7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by padavanonly** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/issues/34

**Comment by InspoOnU** [comment]
> #34
没注意到，感谢
