### ISSUE TITLE
无线AP+CLI模式，WAN6无法获取IPv6地址

### ISSUE THREAD

**Issue by RiddMa** [hanwckf/immortalwrt-mt798x#74]
### Describe the bug

校园网有时分配/128的v6地址，整体参照[这个教程](https://sustech.online/service/network/ipv6/)配置的（但是发现这个固件里没有“使用内置的IPv6管理”这个选项），之前已经配了两台机器，一个是AX6S+原版OpenWrt，一个是x86软路由+高大全固件，均正常使用。而且基本上是一插上网线WAN6不需要额外配置就有v6地址了。这次用的是AX6000，因为没有网口，用无线接入校园网，再发射一个AP信号供设备接入。但是无论怎么配置都没有上游IPv6，而用手机电脑直接连校园网热点是可以拿到v6的。我在[这里](https://github.com/immortalwrt/immortalwrt/discussions/773)看到说需要额外安装ipv6helper才能支持ipv6，是这样吗？

固件是在[恩山这个链接](https://www.right.com.cn/forum/thread-6352752-1-1.html)下的。

![image](https://user-images.githubusercontent.com/49595662/230097874-10f72881-9714-4ff2-aee9-309623d671b8.png)

![image](https://user-images.githubusercontent.com/49595662/230098242-4c401a01-5819-4f11-8ead-ac972a3584c5.png)

![image](https://user-images.githubusercontent.com/49595662/230098413-fed54725-538f-4a19-9014-833298f15b88.png)

![image](https://user-images.githubusercontent.com/49595662/230108479-430124ba-0edb-4844-8a23-f3b896318160.png)

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT r20109-3451ac6453 / LuCI openwrt-21.02 branch git-23.079.62176-116cfc7

### ImmortalWrt target/subtarget

mediatek/mt7986

### Device

Xiaomi Redmi Router AX6000

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cherinyy** [comment]
https://openwrt.org/docs/guide-user/network/ipv6/ipv6.nat6

https://evanzj.com/2021/12/20/NAT6/

https://zhuanlan.zhihu.com/p/492774540

**Comment by cherinyy** [comment]
尝试了下，`force` 可能会导致无法获取 IPv6 地址，使用 `try` 试试？

**Comment by RiddMa** [comment]
我的表述可能有些不清楚，您可能有些误解。

我AX6000目前的配置在WAN口直插网线的情况下，均正常，路由器可以获取v6，连接路由的客户端可以通过nat6获取到地址并上网。

但是（因为拿回宿舍使用没有墙壁网口）当改为使用AP+CLI模式，WAN通过无线连接校园网AP时，路由器本身的WAN6却拿不到v6地址了。也就导致下联设备没有v6地址。

> https://openwrt.org/docs/guide-user/network/ipv6/ipv6.nat6
> 
> 
> 
> https://evanzj.com/2021/12/20/NAT6/
> 
> 
> 
> https://zhuanlan.zhihu.com/p/492774540

**Comment by cherinyy** [comment]
> 路由器本身的WAN6却拿不到v6地址了

https://github.com/hanwckf/immortalwrt-mt798x/issues/74#issuecomment-1627562816

我这边网络环境对无线中继的测试结果是 `force` 有问题，会导致获取不到 IPv6 地址。

**Comment by RiddMa** [comment]
> > 路由器本身的WAN6却拿不到v6地址了
> 
> [#74 (comment)](https://github.com/hanwckf/immortalwrt-mt798x/issues/74#issuecomment-1627562816)
> 
> 我这边网络环境对无线中继的测试结果是 `force` 有问题，会导致获取不到 IPv6 地址。

WAN6 设置成 try 之后确实可以获取 v6 地址了，感谢您的时间。

Closing this issue as completed.
