### ISSUE TITLE
cmi.hanwckf.top/p/immortalwrt-mt798x无法访问

### ISSUE THREAD

**Issue by GuiDeJuShi** [hanwckf/immortalwrt-mt798x#78]
### Describe the bug

cmi.hanwckf.top/p/immortalwrt-mt798x无法访问，打不开

### ImmortalWrt version

1

### ImmortalWrt target/subtarget

1

### Device

1

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by rootphantomer** [comment]
404 Not Found

**Comment by chika0801** [comment]
cmi.hanwckf.top/p/immortalwrt-mt798x

打得开

**Comment by Demonstrations** [comment]
真的打不开了。。。

**Comment by wykdg** [comment]
昨天打不开，现在好了

**Comment by hanwckf** [comment]
建议挂梯子访问
