### ISSUE TITLE
无线两个频率的接口都关闭后，这一段时间自己又开了

### ISSUE THREAD

**Issue by fengchen-github** [hanwckf/immortalwrt-mt798x#79]
### Describe the bug

如上

### ImmortalWrt version

ImmortalWrt 21.02-SNAPSHOT r20110-eab0d53b0d / LuCI openwrt-21.02 branch git-23.098.38725-847bd6b

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

mediatek/mt7981

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cherinyy** [comment]
往 `/etc/rc.local` 添加：

```
sleep 30
ifconfig ra0 down
ifconfig rax0 down
```

试试，设备名称不对的话请自行替换。
