### ISSUE TITLE
您好，如何从源码中禁用硬件加速功能

### ISSUE THREAD

**Issue by Lollipop907** [hanwckf/immortalwrt-mt798x#8]
本人需要用ua2f和ipid修改模块，因此需要禁用硬件加速功能，请问如何禁用

**Comment by hanwckf** [comment]
由于目前无线驱动依赖mtkhnat，所以在开启无线的时候必须加载mtkhnat驱动，可用以下方法临时禁用hnat hook
```
echo 0 > /sys/kernel/debug/hnat/hook_toggle
```

如果需要关闭WiFi的warp加速，在无线芯片配置页面关闭`WiFi硬件加速`选项即可

**Comment by Lollipop907** [comment]
好的，谢谢
