### ISSUE TITLE
能不能适配H3C NX30 PRO

### ISSUE THREAD

**Issue by Qs315490** [hanwckf/immortalwrt-mt798x#85]
### Describe the bug

cpu也是mt7981
目前第三方固件只有https://github.com/padavanonly/immortalwrtARM/tree/mt7981

### ImmortalWrt version

18.07

### ImmortalWrt target/subtarget

mt7981

### Device

nx30pro

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 0x5826** [comment]
支持！

**Comment by cherinyy** [comment]
https://github.com/immortalwrt/immortalwrt/compare/73de418...e78d1a0

可以自行尝试合并相关参数进行编译，欢迎[提交拉取请求](https://github.com/hanwckf/immortalwrt-mt798x/compare)。

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/b0360ffa94838457e6da7a692572c21fd1ff1335
