### ISSUE TITLE
可否适配小米WR30U，感谢

### ISSUE THREAD

**Issue by iamyangyiok** [hanwckf/immortalwrt-mt798x#86]
### Describe the bug

可否适配小米WR30U，感谢

### ImmortalWrt version

1

### ImmortalWrt target/subtarget

1

### Device

WR30U

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by ningsibuqu** [comment]
237 适配了。

**Comment by hank9999** [comment]
看看 PR 里，提交了
