### ISSUE TITLE
在软件库里面安装的zerotier无法运行

### ISSUE THREAD

**Issue by qstzs** [hanwckf/immortalwrt-mt798x#88]
### Describe the bug

报错情况如下
Error relocating /usr/bin/zerotier-idtool: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/bin/zerotier-idtool: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/bin/zerotier-idtool: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

### ImmortalWrt version

openwrt-06.04.2023-mediatek-mt7986-xiaomi_redmi-router-ax6000-squashfs-sysupgrade

### ImmortalWrt target/subtarget

AX6000-0604固件

### Device

AX6000-0604固件

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cherinyy** [comment]
openwrt/packages#20340

https://github.com/openwrt/openwrt/commit/c0b4303d2e2f4a9e1d4684fd584e6b6548666f0f

https://github.com/hanwckf/immortalwrt-mt798x/blob/722aef9de1e75bff9949552a7eea306e7cf10fe7/toolchain/gcc/common.mk#L121
