### ISSUE TITLE
mt2500 usb 口无供电

### ISSUE THREAD

**Issue by fromthink** [hanwckf/immortalwrt-mt798x#92]
### Describe the bug

加入了所有的驱动，编译好后插入的usb设备始终无法识别。但是如果中间接一个有供电的usb hub就能正常设备下面的usb设备

### ImmortalWrt version

r20194-722aef9de1

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

GL.iNet GL-MT2500

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by hanwckf** [comment]
请尝试使用最新的源码重新编译，之前的版本没有gpio-export驱动

**Comment by fromthink** [comment]
正常了 ，谢谢！
