### ISSUE TITLE
mt7981编译失败, 缺少warp_wifi.h

### ISSUE THREAD

**Issue by abu9** [hanwckf/immortalwrt-mt798x#93]
### Describe the bug

编译日志:
`
make[3]: Entering directory '/home/runner/work/BuildWRT/BuildWRT/openwrt/package/mtk/drivers/mt_wifi'
rm -f /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/.built
touch /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/.built_check
make  -C "/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.248" KCFLAGS="-fmacro-prefix-map=/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/host/include -I/home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/hostpkg/include -I/home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Wed Jul 12 13:45:04 2023" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/symvers/conninfra.symvers /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/symvers/cryptodev-linux.symvers /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/symvers/gpio-button-hotplug.symvers /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/symvers/warp.symvers" KERNELRELEASE=5.4.248 M="/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap" LINUX_DIR="/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981"    CONFIG_RT_FIRST_IF_RF_OFFSET=0xc0000  CONFIG_MT_WIFI=m CONFIG_WIFI_BASIC_FUNC=y CONFIG_MT_WIFI_PATH="mt_wifi"  CONFIG_FIRST_IF_EEPROM_FLASH=y  CONFIG_RT_FIRST_CARD_EEPROM="flash" CONFIG_SECOND_IF_NONE=y      CONFIG_WIFI_BASIC_FUNC=y    CONFIG_DOT11_N_SUPPORT=y CONFIG_DOT11_VHT_AC=y CONFIG_DOT11_HE_AX=y CONFIG_CFG_SUPPORT_FALCON_MURU=y CONFIG_CFG_SUPPORT_FALCON_TXCMD_DBG=y CONFIG_CFG_SUPPORT_FALCON_SR=y CONFIG_CFG_SUPPORT_FALCON_PP=y CONFIG_WIFI_DRIVER=y CONFIG_G_BAND_256QAM_SUPPORT=y  CONFIG_ICAP_SUPPORT=y CONFIG_MT_AP_SUPPORT=m CONFIG_BACKGROUND_SCAN_SUPPORT=y CONFIG_SMART_CARRIER_SENSE_SUPPORT=y CONFIG_SCS_FW_OFFLOAD=y  CONFIG_MT_DFS_SUPPORT=y CONFIG_HDR_TRANS_TX_SUPPORT=y  CONFIG_HDR_TRANS_RX_SUPPORT=y CONFIG_DBDC_MODE=y    CONFIG_WSC_INCLUDED=y  CONFIG_WSC_V2_SUPPORT=y CONFIG_DOT11W_PMF_SUPPORT=y  CONFIG_TXBF_SUPPORT=y CONFIG_IGMP_SNOOP_SUPPORT=y   CONFIG_RTMP_FLASH_SUPPORT=y CONFIG_ATE_SUPPORT=y CONFIG_WLAN_SERVICE=y CONFIG_UAPSD=y          CONFIG_WIFI_MODE_AP=m     CONFIG_WDS_SUPPORT=y CONFIG_MBSS_SUPPORT=y CONFIG_APCLI_SUPPORT=y       CONFIG_CON_WPS_SUPPORT=y CONFIG_VOW_SUPPORT=y         CONFIG_WIFI_MT_MAC=y   CONFIG_MT_MAC=y  CONFIG_SUPPORT_OPENWRT=y  CONFIG_MUMIMO_SUPPORT=y CONFIG_MU_RA_SUPPORT=y      CONFIG_GREENAP_SUPPORT=y  CONFIG_TPC_SUPPORT=y  CONFIG_CAL_BIN_FILE_SUPPORT=y   CONFIG_RED_SUPPORT=y  CONFIG_FIRST_IF_IPAILNA=y            CONFIG_DOT11K_RRM_SUPPORT=y CONFIG_DOT11R_FT_SUPPORT=y  CONFIG_WIFI_EAP_FEATURE=y  CONFIG_ANTENNA_CONTROL_SUPPORT=y CONFIG_MGMT_TXPWR_CTRL=y    CONFIG_RA_PHY_RATE_SUPPORT=y CONFIG_MBSS_DTIM_SUPPORT=y CONFIG_AMPDU_CONF_SUPPORT=y CONFIG_ACK_CTS_TIMEOUT_SUPPORT=y    CONFIG_VLAN_SUPPORT=y           CONFIG_MAP_SUPPORT=y CONFIG_MAP_R2_VER_SUPPORT=y CONFIG_MAP_R3_VER_SUPPORT=y CONFIG_QOS_R1_SUPPORT=y CONFIG_WPA3_SUPPORT=y CONFIG_OWE_SUPPORT=y         CONFIG_FIRST_IF_MT7981=y     CONFIG_THIRD_IF_NONE=y       CONFIG_CHIP_MT7981=y       CONFIG_SPECTRUM_SUPPORT=y     CONFIG_MCAST_RATE_SPECIFIC=y CONFIG_WLAN_HOOK=y    CONFIG_AIR_MONITOR=y CONFIG_OFFCHANNEL_SCAN_FEATURE=y CONFIG_WNM_SUPPORT=y CONFIG_INTERWORKING=y    CONFIG_MEMORY_SHRINK=y CONFIG_MEMORY_SHRINK_AGGRESS=y  CONFIG_WHNAT_SUPPORT=m CONFIG_FAST_NAT_SUPPORT=y              CONFIG_WIFI_TWT_SUPPORT=y        CONFIG_WARP_V2=y      CONFIG_WIFI_FW_BIN_LOAD=y CONFIG_CONNINFRA_APSOC=y CONFIG_MLME_MULTI_QUEUE_SUPPORT=y       modules
make[4]: Entering directory '/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.248'
  CC [M]  /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in/warp_proxy/warp_proxy.o
In file included from /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in/warp_proxy/warp_proxy.c:3:
/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in/warp_proxy/warp_proxy.h:33:10: fatal error: warp_wifi.h: No such file or directory
 #include <warp_wifi.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[7]: *** [scripts/Makefile.build:262: /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in/warp_proxy/warp_proxy.o] Error 1
make[6]: *** [scripts/Makefile.build:497: /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in/warp_proxy] Error 2
make[5]: *** [scripts/Makefile.build:497: /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap/../mt_wifi/embedded/plug_in] Error 2
make[4]: *** [Makefile:1750: /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/mt_wifi_ap] Error 2
make[4]: Leaving directory '/home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.248'
make[3]: *** [Makefile:344: /home/runner/work/BuildWRT/BuildWRT/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/mt_wifi/.built] Error 2
make[3]: Leaving directory '/home/runner/work/BuildWRT/BuildWRT/openwrt/package/mtk/drivers/mt_wifi'
time: package/mtk/drivers/mt_wifi/compile#1.00#0.34#1.33
    ERROR: package/mtk/drivers/mt_wifi failed to build.
make[2]: *** [package/Makefile:120: package/mtk/drivers/mt_wifi/compile] Error 1
make[2]: Leaving directory '/home/runner/work/BuildWRT/BuildWRT/openwrt'
make[1]: *** [package/Makefile:114: /home/runner/work/BuildWRT/BuildWRT/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/BuildWRT/BuildWRT/openwrt'
make: *** [/home/runner/work/BuildWRT/BuildWRT/openwrt/include/toplevel.mk:230: world] Error 2
`

### ImmortalWrt version

main

### ImmortalWrt target/subtarget

mt7981

### Device

360T7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cherinyy** [comment]
先复制配置模板 `cp -f defconfig/mt7981-ax3000.config .config`

再 `make menuconfig` 然后 `make V=s`。

Duplicate of #80

**Comment by abu9** [comment]
Fix by remove CONFIG_AUTOREMOVE=y in config.
