### ISSUE TITLE
使用最新代码编译固件，passwall 插件报错 iptables透明代理基础依赖 iptables-mod-socket 未安装

### ISSUE THREAD

**Issue by chika0801** [hanwckf/immortalwrt-mt798x#97]
固件编译好后，passwall 插件里点击查看日志显示如下，passwall是最新源码版本

```
2023-07-20 20:36:31: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-07-20 20:36:31: 运行完成！
```

问过GPT了，没找到有效的解决办法。

大约7天多前的源码编译好固件， passwall 插件里面都没这一个报错。请问有具体解决方法吗？

**Comment by BGzEroll** [comment]
其实，21.02压根没着依赖。自一年前的4.51版本开始passwall就加上了这依赖，只是最近passwall加了个依赖检测功能才提示这个问题的，[可以看看这个issues](https://github.com/xiaorouji/openwrt-passwall/issues/2659)，虽然开发者说不用管，但也不知道到底会不会漏规则，头疼

**Comment by chika0801** [comment]
感谢你的回复，原来是passwall那边的问题。再次感谢你。

https://github.com/xiaorouji/openwrt-passwall/issues/2659
