### ISSUE TITLE
360 T7 IPv6硬件加速失效

### ISSUE THREAD

**Issue by InspoOnU** [hanwckf/immortalwrt-mt798x#99]
### Describe the bug

之前版本IPv6转发加速是可以用的，今天编译了一个发现IPv6加速失效了，转发流量会占用CPU

### ImmortalWrt version

r20215-ef7f8d4997

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360 T7

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cherinyy** [comment]
方便的话，可以自行还原更改来测试是哪一个提交导致的问题，应该是与 `hnat` 相关的改动有关。

https://github.com/search?q=repo%3Ahanwckf%2Fimmortalwrt-mt798x+hnat&type=commits&s=committer-date&o=desc

如果是每次更改后都有进行编译的话，按时间来看，也有可能是这个：https://github.com/hanwckf/immortalwrt-mt798x/commit/063918b58fcb94b74d2cf80e95ce03950a1ec962

**Comment by hanwckf** [comment]
之前一个能用的版本大约是什么时候编译的固件？我这边没有v6环境不太好测试，粗略看了下没发现有跟v6加速有关的问题

**Comment by BGzEroll** [comment]
> 之前一个能用的版本大约是什么时候编译的固件？我这边没有v6环境不太好测试，粗略看了下没发现有跟v6加速有关的问题

经测试确实失效了，但不知道是哪个commit导致的，我上一个固件编译的日期为7月3日，ipv6硬件加速是正常的。今天编译的固件ipv6加速异常
![屏幕截图 2023-07-26 200939](https://github.com/hanwckf/immortalwrt-mt798x/assets/104726856/f2b78050-0db5-4837-b346-d01b008b4891)

**Comment by cherinyy** [comment]
![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/9050713/1f459a90-31eb-40d7-b63b-fe591df855bf)

成功复现，我是路由器无线中继——网线接入终端，IPv6 也是中继模式。

**Comment by hanwckf** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/commit/4354230eb385528a6bf064b06accb138d05e61fb
回退这个commit就可以了

**Comment by cherinyy** [comment]
> [4354230](https://github.com/hanwckf/immortalwrt-mt798x/commit/4354230eb385528a6bf064b06accb138d05e61fb) 回退这个commit就可以了

![image](https://github.com/hanwckf/immortalwrt-mt798x/assets/9050713/fcf91ad3-66f8-42c6-9f78-314944f01382)
确实正常了
